### ISSUE TITLE
Define context of `task.if` expression

### ISSUE THREAD

**Issue by matthias-pichler** [serverlessworkflow/specification#1001]
**What would you like to be added**:

Currently the `task.if` expression is not fully documented .. at which point in the data-flow is it evaluated and on what?

My intuition would say the raw input?

Furthermore if a task is skipped, is the context transformation (`export.as`) still applied? I would say no

**Why is this needed**:

**Comment by cdavernas** [comment]
> My intuition would say the raw input?

That's my understanding, yes, as we clarified that the input transforation is part of a task's feature.

> Furthermore if a task is skipped, is the context transformation (export.as) still applied? I would say no

IMHO, of course no: if the task is skipped, so are all the associated features

**Comment by cdavernas** [comment]
Closed as completed by #1005
