### ISSUE TITLE
Update the CI/CD pipeline to generate the JSON equivalency of the DSL schema

### ISSUE THREAD

**Issue by cdavernas** [serverlessworkflow/specification#1003]
**What would you like to be added**:

Update the CI/CD pipeline to generate the JSON equivalency of the DSL schema

**Why is this needed**:

Even though we should be working on the YAML version of the DSL schema, which is both cleaner and easier to read and maintain, programatic approaches (of course) typically favor the JSON format of the so called JSON Schemas. Making sure said format is available to users and implementers is a must have convenience.

**Comment by JBBianchi** [comment]
There is a JSON version of the released DSL schema on serverlessworkflow.io (https://github.com/serverlessworkflow/serverlessworkflow.github.io/tree/main/static/schemas)

Automatically generating a JSON version each time the YAML schema is updated in this repo would be feasible, and probably a plus for "early implementers" trying to keep up to date before a version is released, but it would also create quite a lot of noise in the git history.

**Comment by cdavernas** [comment]
@JBBianchi right! Closing for now, we'll reopen if we need it later for early implementers!
