### ISSUE TITLE
Add a flag to configure whether or not an OIDC discovery request requires HTTPS

### ISSUE THREAD

**Issue by cdavernas** [serverlessworkflow/specification#1006]
**What would you like to be added**:

Add a flag to configure whether or not an OIDC discovery request requires HTTPS.

**Why is this needed**:

Most OIDC discovery libraries provide the ability to enforce or ignore HTTPS when performing discovery requests. Disabling it always might create security issues, while enforcing it always forbids basic use cases such as an IDP hosted whithin Docker.

**The proposal**:

Add a new (boolean) `requireHttps` property, which defaults to `true`, to the `OpenIDConnectAuthenticationPolicy`. Better name suggestions are most welcome!

**Comment by JBBianchi** [comment]
I might be missing something I don't really understand the point or added value of such a property.

The protocole in the `authority` URI already carries the information.

Maybe if the authority URI is secured but the discovered endpoints are not (which *shouldn't* happen), then should it be a runtime configuration to allow that calling those endpoints or an author concern in the workflow itself?

**Comment by ricardozanini** [comment]
Yeah, I'm also curious about this requirement since the discovery endpoint should have the protocol.

**Comment by cdavernas** [comment]
It's not a discovery protocol or a documentation issue, rather a client one (i.e. Microsoft's IdentityModel discovery client). 

However, I'll close this issue for now as it can be mitigated by checking the host's scheme, even though that might not (but should, as mentioned by @JBBianchi ) be enough in some specific use cases.
