### ISSUE TITLE
Ongoing - workflow model optimization

### ISSUE THREAD

**Issue by tsurdilo** [serverlessworkflow/specification#114]
**What would you like to be added**:
Issue to discuss workflow optimization ideas.
We should look into things like:
1) reducing the model complexity
2) reducing the model verbosity but still keeping it as descriptive as possible
3) Look into alternative approaches for certain model definitions
4) Any other ideas/thoughts etc
**Why is this needed**:

**Comment by ricardozanini** [comment]
Great! I think we can bring to discussion a way to specify the Workflow with Kubernetes types. To me right now the most difficult part to represent in a Kubernetes types are the states definition.

**Comment by tsurdilo** [comment]
@ricardozanini +1 !!
