### ISSUE TITLE
Add a parameter classifier to the Function definition scheme

### ISSUE THREAD

**Issue by ricardozanini** [serverlessworkflow/specification#127]
**What would you like to be added**:
A way to classify the parameter in the `function` definition (optional) so implementations could have a hint of how to handle the parameter when executing a given function.

For example a given operation state:

```json
 "functions": [
        {
            "name": "userAuthServiceCall",
            "resource": "http://authservice.com",
            "type": "rest",
            "parameters": [
                {"name": "user", "classifier": "querystring"},
                {"name": "token", "classifier": "header"}
            ],
            "metadata": {
                "method": "GET"
            }
        }
]
(...)
```

**Why is this needed**:
With the classifier, implementations would know how to handle these parameters on a REST call scenario for instance.

**Comment by tsurdilo** [comment]
I think that we are ok in this regard. Function definitions can be used to enforce openapi / swagger, it really depends on the impl of course but I will add examples for rest invokes that look like for example:

"functions": [
    {
       "name": "getUserByName",
       "resource": "https://petstore.swagger.io/v2/swagger.json"
    }
  ]

**Comment by tsurdilo** [comment]
We will require use openapi spec for all function definitions.  More to come on this soon :)

**Comment by ricardozanini** [comment]
Closing this one since #145 will solve this requirement
