### ISSUE TITLE
Proposal to move the "Workflow Diagram" before the "Workflow Definition"

### ISSUE THREAD

**Issue by singhkays** [serverlessworkflow/specification#134]
**What would you like to be added**:
- Move the "Workflow Diagram" before the "Workflow Definition"
https://github.com/serverlessworkflow/specification/blob/master/examples/examples.md 

**Why is this needed**:
It would help better understand the examples by getting an overview from the diagram before looking at the code.

**Comment by tsurdilo** [comment]
https://github.com/serverlessworkflow/specification/pull/138
