### ISSUE TITLE
Proposal to move the 'Retry definition' section (under Events state) to the general section on retries

### ISSUE THREAD

**Issue by jorgenj** [serverlessworkflow/specification#135]
**What would you like to be added**:

Can we move ['retry definition'](https://github.com/serverlessworkflow/specification/blob/master/specification.md#-event-state-onevents-definition) section under ['Events state'](https://github.com/serverlessworkflow/specification/blob/master/specification.md#event-state) section to the [general section on retries](https://github.com/serverlessworkflow/specification/blob/master/specification.md#-workflow-error-handling---retrying)

**Why is this needed**:

The 'Retry definition' section under the 'Events state' has some great detail on the schema and behavior of retries.  All other states only link to the generic retries section which does not include all of this detail.  As a first-read through the doc, Event state is the first state mentioned with retries so it's natural to be introduced to the concept at this point but when using the spec as reference material it's hard to locate all the details on retry behavior where it's located currently (partly under Events state, and partly in the general 'retries' section).

**Comment by tsurdilo** [comment]
@jorgenj Yes good idea. I am rewriting / restructuring the error/retries/timeouts sections completely atm and will definitely consider this.

**Comment by jorgenj** [comment]
I noticed this because I was specifically looking for details on retries, but looking back at it I see now that the Event state actually has the most detail on other common elements as well (sub-sections for Action, FunctionRef, EventRef, Error, Retry, Transition).  I'm wondering if those should also be moved to a common section, rather than being listed directly under Events state.

**Comment by tsurdilo** [comment]
@jorgenj yes to the second comment as well :) Thank you very much for reporting these types of things. It really helps!

**Comment by tsurdilo** [comment]
@jorgenj i have combined onErrors and retry definitions in PR https://github.com/serverlessworkflow/specification/pull/175

**Comment by tsurdilo** [comment]
closed by commit https://github.com/serverlessworkflow/specification/commit/07e0b86da75564d36749ff4df876f7d4e898e5db

please file further requests on this via new issues
