### ISSUE TITLE
Retries; maxAttempts and interval attributes

### ISSUE THREAD

**Issue by jorgenj** [serverlessworkflow/specification#136]
**What is the question**:

If I'm understanding correctly, maxAttempts and the interval attribute both indicate the max number of attempts.  Are these fields really both allowing the user to specify the number of attempts, or am I misunderstanding something about these fields?

[From the spec](https://github.com/serverlessworkflow/specification/blob/master/specification.md#retry-definition)

Parameter | Description
---------- | -----------
interval | Interval value for retry (ISO 8601 repeatable format). For example: "R5/PT15M" (Starting from now repeat 5 times with 15 minute intervals)
maxAttempts | Maximum number of retry attempts. Value of 0 means no retries are performed

**Comment by tsurdilo** [comment]
@jorgenj Thanks for the question! maxAttempts can limit the number of attempts when interval defines an unbounded number of repetitions , for example R/PT15M. In the param description the example is indeed somewhat confusing so I will update that asap. 
Using maxAttempts even if interval is bounded could be useful in testing for example. 

I am currently revising the error handling  / timeouts / retries sections and will definitely include this as well as many more clarifications in the docs.

**Comment by jorgenj** [comment]
I can't tell if there's a reason why I might use interval field to limit retries over using the separate maxAttempts attribute, perhaps some guidance on when/why a user might use one vs. the other would be helpful to add to the docs?  One advantage I see over the separate fields is it's a nice succinct way to define a basic retry policy (retry 5 times with 2 minutes in between -> "R5/2M").

On the other hand, the concern is that this might get confusing when combined with functionality like progressive backoff.  For example:
> { "interval": "R5/PT15M",
      "multiplier": "1M"
    }
At first glance, it's not clear whether this will have 15M between every retry, or follow an increasing series of backoffs (I personally would assume the progressive series (15m, 16m, 17m, ...)).

**Comment by tsurdilo** [comment]
@jorgenj all good points I am using your ideas atm as part of the workflow error docs updates. Will ping you to review PRs that have updates asap.

**Comment by tsurdilo** [comment]
@jorgenj i have taken the first step on this with just a small change interval/delay in PR https://github.com/serverlessworkflow/specification/pull/175. 

Once that pr is merged we can move forward on the overall retry definition improvements.

**Comment by jorgenj** [comment]
@tsurdilo I'm new to github issues, is it reasonable to assign this task to me?  I'm not sure how to do that, is that something you can do?

**Comment by tsurdilo** [comment]
@jorgenj done
