### ISSUE TITLE
Retries; exponential backoff & max backoff duration

### ISSUE THREAD

**Issue by jorgenj** [serverlessworkflow/specification#137]
**What would you like to be added**:

Support for exponential backoff and to be able to cap the maximum amount of time between retry attempts.

**Why is this needed**:

**Exponential backoff**

A common strategy for retrying on failure conditions is to backoff exponentially, to support progressively larger backoff durations if the failure is potentially due to something like a network partition or service outage.

The current spec describes 'multiplier' as a duration, where subsequent backoff between retries is incremented by the duration value of 'multiplier'.  Would it be possible to add support for float values as well, in which case the backoff between retries would be calculated by multiplying the float value by the previous backoff duration (interval attribute providing the initial value if no previous retry attempts yet)?  Or perhaps the current field should be renamed to something like 'increment' and a new 'multiplier' field which expects a float value could be added?

**Max backoff duration**

I think there are many use-cases for this, but one such use-case:

For cloud orchestration workflows, a common use-case is to request a resource in one step of a workflow and then to 'poll' for completion of the resource in a sub-sequent step (eg. launch a compute instance and then wait for status=AVAILABLE).  Workflow implementers want to be 'kind' to the service being called and thus back-off, but they also want to keep the workflow timely/responsive by not waiting too long between checks.

Would it be possible to add a maxDuration attribute, which sets an upper-bound on the backoff duration between attempts of a state?

**Comment by tsurdilo** [comment]
@jorgenj 
Re "exponential backoff" - I think that is a valid use case. Could you provide an example json/yaml def the way you would like to see it and we can discuss details? Would just make it easier to see it as an example that can be used also for examples and docs.

Re: "max backoff duration" - again would be possible to see an example of how you would like this to be? Current impl can handle similar cases with the event-based switch state and the callback states for example, where the amount of time waiting for event can be expressed via a timeout value.

**Comment by jorgenj** [comment]
For exponential backoff, I'm partial to the idea of renaming the current 'multiplier' field which accepts a duration to 'increment' instead, and adding a new 'multiplication' field that accepts a numeric value.  For example:

> {    "expression": ...,
    "interval": "PT2S",
    "increment": "PT2S",
    "multiplier": 1.5
 }

This example would result in the following series of backoff durations between retries:
* 2s
* 6s ((2s + 2s) * 1.5)
* 12s ((6s + 2s) * 1.5)
* ...

For max backoff, something like the following (using multiplier redefinition from above):

> {    "expression": ...,
    "interval": "PT2S",
    "maxDuration": "PT15S",
    "multiplier": 2
 }

This example would result in the following series of backoff durations between retries:
* 2s ( min(2s, 15s) )
* 4s ( min(2s * 2, 15s) )
* 8s ( min(4s * 2, 15s) )
* 15s ( min(8s * 2, 15s) )
* 15s ( min(15s * 2, 15s) )
* ...

**Comment by tsurdilo** [comment]
depends on pr https://github.com/serverlessworkflow/specification/pull/175
