### ISSUE TITLE
Uniqueness constraint for workflows

### ISSUE THREAD

**Issue by jorgenj** [serverlessworkflow/specification#146]
**What would you like to be added**:

The ability to define some 'uniqueness' attributes of a workflow, there-by allowing the runtime to enforce a 'single logical instance' of a workflow at any given time.

**Why is this needed**:

Note; I think the Events state + correlation rules actually already support this in a way, but as far as I can tell it only works for workflows that are invoked via a consumed event.

Some common cases that I don't think are currently supported (please correct me if I'm missing something):
* For scheduled (cron-style) workflows, the ability to skip launching a new workflow instance if a previous workflow instance is still running.
  * For example, an hourly 'garbage collection' workflow that deletes stale resources.  If the previous one is still running, users may not want to have a second workflow instance running at the same time.
* For directly invoked workflows, the ability to skip launching a new workflow instance if a similar workflow instance is already running
  * For example, a 'recovery workflow' which terminates and relaunches a cloud resource, 'similar' in this case would mean the same type of workflow targeting the same cloud resource.
* Similar for sub-workflows, the ability to skip launching a new workflow instance if a similar workflow instance is already running

My understanding (which could be very incorrect) of the event correlation rules is that I could accomplish all of these use-cases but only if my workflows are invoked via events:
* If I want a single garbage-collection workflow, never more than one, then I can set a correlation rule with a hard-coded `contextAttributeValue=SomeValue` in the event definition.
* If I want to ensure there's only one workflow for a given resource at one time, then I can instead have a correlation rule with `contextAttributeName=SomeAttributeContainingTheResourceId`

Unfortunately, this doesn't work very well for scheduled (cron-style) workflows because it would require the arrival of an 'event' at roughly the same timing as the cron schedule (per the spec docs).  It also seems to preclude the use of the SubFlow state as that doesn't seem to invoke the child workflow via event, if I understand things correctly.

I don't have a solution to propose here, but I wanted to initiate a conversation about how we might extend the existing model so that users can accomplish this for:
* directly invoked workflows
* sub-workflows
* scheduled (cron-style) workflows

**Comment by tsurdilo** [comment]
@jorgenj Let's try to define what is meant by "similar". I think that will be the key aspect to start looking at in order to move forward with possible markup updates for these usecases you mention.
For example, are two workflow instances "similar" based on their data(subset), some identifiers (business keys), their cron schedules, something else?

**Comment by jorgenj** [comment]
Good question, I was thinking 'similar' could be defined based on the inputs to the workflow.  For example, something like allowing the workflow definition to declare that fields X,Y, and Z from input data form the 'uniqueness key' for a workflow instance.  (I'm not sure if this fits in what you were thinking as data(subset) or business keys).  I think this ties in well, conceptually, with the way correlation rules work for events.

For cron-triggered, the primary use-case that I've seen is to allow a single instance at a time, though I've seen a few implementations that want to sub-divide their problem-space and always have N 'shards' running at any given time (ie; shard0 knows to work on 1/3rd of data, shard1 another 1/3rd, and shard3 the last 1/3rd).   As far as I can see, the only potential 'input' to a cron-triggered workflow right now could be the timestamp it was triggered at.  If we can allow the cron-triggered workflow definition to also provide a hardcoded input (so every launch gets the same hardcoded input), then users could maybe declare an expression that takes that part of the input to form the 'uniqueness key' for that workflow?

**Comment by ricardozanini** [comment]
@jorgenj and what if we add an attribute similar to, I don't know, `singleton` to the cron-style workflows? So the runtime implementation would know if there's an instance running that supposed to be singleton and wouldn't start a new one.

For the others, I agree that a correlation key would define uniqueness for the process (for event-based workflows we already have it, like you mentioned).

**Comment by jorgenj** [comment]
@ricardozanini I think the 'singleton' idea could work for cron-style, though I'm kinda hoping we can figure out a way to make the 'correlation key' idea work for all 3 of:
* event invoked workflows
* directly invoked workflows
* cron-scheduled workflows

Consider this a half-baked idea, but is there a way we can figure out to allow users to apply correlation rules to either the input data (for direct-invoked workflows) or the invoking event(s) (in the case of an event-invoked workflow)?  Perhaps as an attribute of the [Start definition](https://github.com/serverlessworkflow/specification/blob/master/specification.md#start-definition).  

Allowing, perhaps, for something like the following to accomplish the singleton case for cron-triggered workflows:
```json
{
  "kind": "scheduled",
  "schedule": {
    "cron": "* * * * *"
  }
  "correlationRules": [
      { "correlationAttributeName": "Singleton",
         "correlationAttributeValue": "Singleton"
      }
  ]
}
```

For workflows that are intended to be direct-invoked, something similar could be used to ensure no more than one workflow instance at a time per patient:

```json
{
  "kind": "default",
  "correlationRules": [
      { "correlationAttributeName": "patientId" }
  ]
}
```

I think that's one potential idea for how we could add 'correlation rules' for direct-invoked and cron-scheduled workflows, but the thing I don't like is that it doesn't fit very well with the event-invoked workflows, since the correlation-rules in that case are defined on the events which the starting Events state says it's listening for.   This would mean we would have 2 different ways to do very similar things (not ideal).

Not a great idea, but I figured I'd throw it out there and maybe it gives other some ideas.

**Comment by tsurdilo** [comment]
Wondering if its good idea to make this an extension - https://github.com/serverlessworkflow/specification/tree/master/extensions

**Comment by jorgenj** [comment]
Is there guidance somewhere on determining what belongs as an extension vs. part of the core spec?  To be honest, I wasn't aware of the extensions mechanism until you just pointed it out, so I'm not sure how think about extensions.

To me, this feature request seems pretty closely related to the correlation-rules for events, so I'm inclined to think that it makes sense to be included in the main spec.

**Comment by tsurdilo** [comment]
**Is there guidance somewhere on determining what belongs as an extension vs. part of the core spec?**
https://github.com/serverlessworkflow/specification/blob/master/specification.md#extensions
I tried to outline in that section. Does it make sense?

**Comment by jorgenj** [comment]
Thanks for the link.

> Model extensions do no influence control flow logic (workflow execution semantics)

It seems to me that a 'uniqueness constraint' influences control flow logic, in that it affects whether 1 or many 'similar' instances of a workflow would be invoked.  I see this as a condition on how/when a workflow is invoked, similar in the way that the interval or cron schedule declare conditions on how/when a workflow can/should be invoked.

**Comment by jorgenj** [comment]
Does a comment re-open this issue?
