### ISSUE TITLE
How to just select some filed from input json use state Data Filter ？

### ISSUE THREAD

**Issue by skyshaokai** [serverlessworkflow/specification#158]
**What is the question**:
inputJson ：
{
  "inputkey1": "value1",
  "inputkey2": "value2",
  "inputkey3": "value3",
  "inputkey4": "value4"
}
if I want 
outputJson ：
{
  "outputkey1": "value1",
  "outputkey2": "value2"
}

When two fields inputkey1 and inputkey2 need to be taken from datainputpath JSON data to construct an output JSON, how should dataoutputpath be set ？

**Comment by tsurdilo** [comment]
@sky132333 filters as they are defined now can just filter the input data based on an jsonpath expression. they do not define atm data manipulation as you are describing atm. However we are looking at supporting this in the future, see Issue https://github.com/serverlessworkflow/specification/issues/149. (@ricardozanini there you go , a good use-case for it :) ).

The issue linked deals with adding JsonPatch support. With this you could do manipulations as what you are describing.

Hope this helps!

**Comment by ricardozanini** [comment]
@sky132333 I'll draft a document to support RFC 6902 and will ping you to review.

**Comment by ricardozanini** [comment]
For this use case, assuming this input once #149 is incorporated:

```json
{
    "inputkey1": "value1",
    "inputkey2": "value2",
    "inputkey3": "value",
    "inputkey4": "value4"
}
```

We could have a function like:

```json
{
   "name":"MyState",
   "type":"inject",
   "stateDataTransform":{
      "dataInputPatch":[
         {
            "op":"move",
            "from":"/inputkey1",
            "path":"/outputkey1"
         },
         {
            "op":"move",
            "from":"/inputkey2",
            "path":"/outputkey2"
         }
      ],
      "dataOutputFilter":"{{ $.outputkey1 $.outputkey2 }}"
   },
   "transition":{
      "nextState":"someNextState"
   }
}
```

@tsurdilo @sky132333 what do you guys think?

**Comment by sky132333** [comment]
> For this use case, assuming this input once #149 is incorporated:
> 
> ```json
> {
>     "inputkey1": "value1",
>     "inputkey2": "value2",
>     "inputkey3": "value",
>     "inputkey4": "value4"
> }
> ```
> 
> We could have a function like:
> 
> ```json
> {
>    "name":"MyState",
>    "type":"inject",
>    "stateDataTransform":{
>       "dataInputPatch":[
>          {
>             "op":"move",
>             "from":"/inputkey1",
>             "path":"/outputkey1"
>          },
>          {
>             "op":"move",
>             "from":"/inputkey2",
>             "path":"/outputkey2"
>          }
>       ],
>       "dataOutputFilter":"{{ $.outputkey1 $.outputkey2 }}"
>    },
>    "transition":{
>       "nextState":"someNextState"
>    }
> }
> ```
> 
> @tsurdilo @sky132333 what do you guys think?

Does only inject state support this?

**Comment by ricardozanini** [comment]
@sky132333 please follow the comments in the original issue #149 . We are brainstorming around this use case and we should bring up this topic in today's meeting 1pm EST.

**Comment by ricardozanini** [comment]
This also could be handled by the `jq` implementation if we decide to go ahead #216
