### ISSUE TITLE
Why is "resultEventRef" required for EventRef?

### ISSUE THREAD

**Issue by LCaparelli** [serverlessworkflow/specification#161]
**What is the question**:

What if there is no outcome data from tasks performed after the `triggerEventRef` event gets consumed? Must `FunctionRef` be used instead for those scenarios?

[EventRef Definition](https://github.com/serverlessworkflow/specification/blob/master/specification.md#eventref-definition)
[FunctionRef Definition](https://github.com/serverlessworkflow/specification/blob/master/specification.md#functionref-definition)

**Comment by tsurdilo** [comment]
triggerEventRef is an event that the workflow instance has to produce. then waits for the "timeout" duration for resultEventRef. The payload of resultEventRef should be merged then to the state data before next action is executed. HTH

One thing I noticed is that in the "data" property description of EventRef definitions says:
"data (payload) of the produced event". Would be probably more clear if we add that this parameter is associated specifically to the triggerEventRef as its represents the payload of the trigger event this action produces. 
Just something that we could add as a pr if anyone wants to help ...hint hint ;)

**Comment by LCaparelli** [comment]
> triggerEventRef is an event that the workflow instance has to produce. then waits for the "timeout" duration for resultEventRef. The payload of resultEventRef should be merged then to the state data before next action is executed. HTH

Right, but couldn't `resultEventRef` be optional?

> "data (payload) of the produced event". Would be probably more clear if we add that this parameter is associated specifically to the triggerEventRef as its represents the payload of the trigger event this action produces.
Just something that we could add as a pr if anyone wants to help ...hint hint ;)

Hehe, I'd love to send that in. :-)

Should I create a new issue or just the PR is enough?

**Comment by tsurdilo** [comment]
1) no its not optional. have to wait for completion of service(s) that are executed.
2) pr enough :)

**Comment by LCaparelli** [comment]
> no its not optional. have to wait for completion of service(s) that are executed.

Ohhhh, right. Right, it makes sense to me now. Without it, we couldn't tell if the services which got triggered actually finished. Is that it?

**Comment by tsurdilo** [comment]
@LCaparelli yeah, that allows us to invoke service(s) which are not exposed via rest for example, but are triggered via events. This allows us to cover cases such as https://quarkus.io/guides/funqy-knative-events for example.

**Comment by LCaparelli** [comment]
Ah, awesome. The use case is much clearer to me now, thanks @tsurdilo! Closing the issue :-)
