### ISSUE TITLE
spec End Definition kind 

### ISSUE THREAD

**Issue by sky132333** [serverlessworkflow/specification#164]
**What is the question**:
default - Default workflow execution completion; no other special behavior.
terminate - Completes all execution flows in the given workflow instance. All activities/actions being executed are completed. If a terminate end is reached inside a ForEach, Parallel, or SubFlow state, the entire workflow instance is terminated.

If kind is to be set “default” ，workflow execution completion .Is the workflow completed, but if there are other states running, will it continue to run and move to the next state? Can you give an example of the difference between fault and terminate?

**Comment by tsurdilo** [comment]
@sky132333 sure, one example is parallel state with multiple branches using sub-flows. When a particular sub-flow ends in a "default" end all others still continue. However when it ends in a terminate end all other currently running branches, as well as process instances should be terminated. 

A real-world example could be if you let's have 100 contestants in a raffle and you are checking all of them in parallel to see which one is the winner. If you use the terminate end  def, as soon as one of the parallel state branches determines a "winner" you want to just stop every other branch from keep processing and just end workflow execution. If you in this case use a "default" end def, process would have to wait until all other branches have completed after the winner has already been found  before it itself can complete. HTH

**Comment by sky132333** [comment]
> @sky132333 sure, one example is parallel state with multiple branches using sub-flows. When a particular sub-flow ends in a "default" end all others still continue. However when it ends in a terminate end all other currently running branches, as well as process instances should be terminated.
> 
> A real-world example could be if you let's say have 100 contestants in a raffle and you are checking all of them in parallel to see which one is the winner. If you use the terminate end def, as soon as one of the parallel state branches or foreach state iterations determines a "winner" you want to just stop every other branch/iteration from keep processing and just end workflow execution. If you in this case use a "default" end def, process would have to wait until all other branches/iterations have completed after the winner has already been found before it itself can complete. HTH

Good example ，thank you very much .

**Comment by tsurdilo** [comment]
@sky132333 your are welcome. is it ok if we close this issue or are there any more related questions?

**Comment by sky132333** [comment]
> @sky132333 your are welcome. is it ok if we close this issue or are there any more related questions?

ok ，thank you very much .
