### ISSUE TITLE
Parallel State: Branch .Hope to support the use of states as branch.

### ISSUE THREAD

**Issue by sky132333** [serverlessworkflow/specification#166]
**What would you like to be added**:
Hope to support the use of states as branch. 

**Why is this needed**:
In some cases, we need to use states as a branch.
Although there can be subworkflow to indirectly use states as a branch, it is not convenient to use subworkflow.

**Comment by tsurdilo** [comment]
@sky132333 we removed the direct use of states definitions inside branches for several reasons. It is much cleaner from the markup and from understanding point of view to place your branch logic (if it needs to be expressed via states) inside a sub-workflow and it also makes it reusable. Hope this helps.

**Comment by sky132333** [comment]
> @sky132333 we removed the direct use of states definitions inside branches for several reasons. It is much cleaner from the markup, reduces markup complexity by a lot, and from understanding point of view to place your branch logic (if it needs to be expressed via states) inside a sub-workflow as well as it makes it reusable. Hope this helps.

Okay, I get it
