### ISSUE TITLE
spec stateDataFilter  dataInputPath and dataOutputPath question

### ISSUE THREAD

**Issue by sky132333** [serverlessworkflow/specification#168]
**What is the question**:
example  select  veggieLike

state config：
{
  "name": "VegetablesOnlyState",
  "type": "inject",
  "stateDataFilter": {
    "dataInputPath": "{{ $.vegetables }}",
    "dataOutputPath": "{{ $.[?(@.veggieLike)] }}"
  },
  "transition": {
     "nextState": "someNextState"
  }
}

if data input  1 is

{
  "fruits": [ "apple", "orange", "pear" ],
  "vegetables": [
    {
      "veggieName": "potato",
      "veggieLike": true
    },
    {
      "veggieName": "broccoli",
      "veggieLike": false
    }
  ]
}

then state output is an object 
{
      "veggieName": "potato",
      "veggieLike": true
}

but if data input 2 is ：
{
  "fruits": [
    "apple",
    "orange",
    "pear"
  ],
  "vegetables": [
    {
      "veggieName": "potato",
      "veggieLike": true
    },
    {
      "veggieName": "tomato",
      "veggieLike": true
    },
    {
      "veggieName": "broccoli",
      "veggieLike": false
    }
  ]
}

is the output to be ：
[
  {
    "veggieName": "potato",
    "veggieLike": true
  },
  {
    "veggieName": "tomato",
    "veggieLike": true
  }
]

if it is the output ，but this have  a problem  input data 1 the output is an  object , input data 1 the output is an array . the output is different schema.

**Comment by tsurdilo** [comment]
@sky132333 sorry i dont understand. for both of the data inputs provided the output of the state has the same structure, namely:

for input 1:
```json
[
  {
    "veggieName": "potato",
    "veggieLike": true
  }
]
```


for input 2: 

```json
[
  {
    "veggieName": "potato",
    "veggieLike": true
  },
  {
    "veggieName": "tomato",
    "veggieLike": true
  }
]
```

So whats the question? I don't understand.

**Comment by sky132333** [comment]
> @sky132333 for both of the data inputs provided the output of the state has the same structure, namely:
> 
> for input 1:
> 
> ```json
> [
>   {
>     "veggieName": "potato",
>     "veggieLike": true
>   }
> ]
> ```
> 
> for input 2:
> 
> ```json
> [
>   {
>     "veggieName": "potato",
>     "veggieLike": true
>   },
>   {
>     "veggieName": "tomato",
>     "veggieLike": true
>   }
> ]
> ```
> 
> So whats the question? I don't understand. The result of the JsonPath eval is always an array.




> @sky132333 for both of the data inputs provided the output of the state has the same structure, namely:
> 
> for input 1:
> 
> ```json
> [
>   {
>     "veggieName": "potato",
>     "veggieLike": true
>   }
> ]
> ```
> 
> for input 2:
> 
> ```json
> [
>   {
>     "veggieName": "potato",
>     "veggieLike": true
>   },
>   {
>     "veggieName": "tomato",
>     "veggieLike": true
>   }
> ]
> ```
> 
> So whats the question? I don't understand. The result of the JsonPath eval is always an array.

<img width="1133" alt="pic" src="https://user-images.githubusercontent.com/11512967/97767904-4d21cf00-1b5a-11eb-976c-82a266be6e97.png">
in the spec is an object .

**Comment by tsurdilo** [comment]
@sky132333 nice catch! will update . thanks!

**Comment by tsurdilo** [comment]
Pull request for fix: https://github.com/serverlessworkflow/specification/pull/169

**Comment by tsurdilo** [comment]
closed via https://github.com/serverlessworkflow/specification/pull/169
