### ISSUE TITLE
What is states data and How to merge with it .

### ISSUE THREAD

**Issue by sky132333** [serverlessworkflow/specification#172]
**What is the question**:
Merged with the States data appears many times in the specification (action Data filter dataResultPath ,Error Data Filter ), but it does not explain what states data is and how to merge with it? Can you add some explanations and examples ？

**Comment by tsurdilo** [comment]
@sky132333 
Regarding *it does not explain what states data is * - there is a whole section on this topic in the spec document  https://github.com/serverlessworkflow/specification/blob/master/specification.md#Workflow-Data :)

Regarding *does not explain what states data is and how to merge with it? Can you add some explanations and examples ?* - 
I think there are examples in images and text on this. 

If you need a simple example ok sure -
Let's say you have an operation state data input of:

```json
{
   "order": {
      "id": "123",
      "customer": "John"
   }
}	
```
and this state invokes a service which has the result:
```json
{
   "order": {
      "id": "123",
      "accepted": true
   }
}	
```
which would be merged with state data to become:
```json
{
   "order": {
      "id": "123",
      "customer": "John",
      "accepted": true
   }
}	
```


Hope this helps.

**Comment by sky132333** [comment]
> @sky132333
> Regarding *it does not explain what states data is * - there is a whole section on this topic in the spec document https://github.com/serverlessworkflow/specification/blob/master/specification.md#Workflow-Data :)
> 
> Regarding _does not explain what states data is and how to merge with it? Can you add some explanations and examples ?_ -
> I think there are examples in images and text on this.
> 
> If you need a simple example ok sure -
> Let's say you have an operation state data input of:
> 
> ```json
> {
>    "order": {
>       "id": "123",
>       "customer": "John"
>    }
> }	
> ```
> 
> and this state invokes a service which has the result:
> 
> ```json
> {
>    "order": {
>       "id": "123",
>       "accepted": true
>    }
> }	
> ```
> 
> which would be merged with state data to become:
> 
> ```json
> {
>    "order": {
>       "id": "123",
>       "customer": "John",
>       "accepted": true
>    }
> }	
> ```
> 
> Hope this helps.

Thank you for answer.

**Comment by tsurdilo** [comment]
@sky132333 any time. will close this issue now if that's ok. thanks!
