### ISSUE TITLE
StateDateFilter  dataInputPath question

### ISSUE THREAD

**Issue by skyshaokai** [serverlessworkflow/specification#183]
**What is the question**:
In the spec 0.5 version , there are tow examples.
### In the first example:
![image](https://user-images.githubusercontent.com/11512967/98910183-cf68a680-24fd-11eb-970e-6771205b55b2.png)
dataInputPath is {{ $.hello }}  . 
data input is:
![image](https://user-images.githubusercontent.com/11512967/98910332-fcb55480-24fd-11eb-86ce-cca8e07273da.png)
The event state stateDataFilter is invoked to filter this data input. Its "dataInputPath" is evaluated and filters only the "hello" greetings in different languages. At this point our event state data contains:
{
  "hello": {
      "english": "Hello",
      "spanish": "Hola",
      "german": "Hallo",
      "russian": "Здравствуйте"
    }
}
Please note that the JSON field is "hello".

### In the second example:
![image](https://user-images.githubusercontent.com/11512967/98910773-93821100-24fe-11eb-8345-ae9d2c5af3d2.png)
dataInputPath is  {{ $.fruits }} ,Please note that the JSON field not contains "fruits".

These two examples make me wonder why statedatefilter datainputpath sometimes uses its own fields when putting data into state data? Statedatefilter dataoutputpath has the same question.

**Comment by tsurdilo** [comment]
@sky132333 if i understand the question correctly: input paths on both examples allow you to specifically declare which parts of your state data input are relevant or not.  in these two small examples yes I agree it looks as non functional, but think of workflow cases where the maybe event payloads or service results are very big and include alot of data that is not relevant for the orchestration that particular workflow performs. This allows us to maintain much less data in memory during workflow execution. 
Similarly for output paths they allow to further filter the state data (data that may have been merged from results of service executions etc etc) and only pass to the next workflow state data that is relevant to further process our orchestration.

So this is definitely more useful in large data scenarios and these two examples dont do it justice. This would be a nice thing to add in the spec docs to make it more clear, I agree and will work on it.

**Comment by sky132333** [comment]
> @sky132333 if i understand the question correctly: input paths on both examples allow you to specifically declare which parts of your state data input are relevant or not. in these two small examples yes I agree it looks as non functional, but think of workflow cases where the maybe event payloads or service results are very big and include alot of data that is not relevant for the orchestration that particular workflow performs. This allows us to maintain much less data in memory during workflow execution.
> Similarly for output paths they allow to further filter the state data (data that may have been merged from results of service executions etc etc) and only pass to the next workflow state data that is relevant to further process our orchestration.
> 
> So this is definitely more useful in large data scenarios and these two examples dont do it justice. This would be a nice thing to add in the spec docs to make it more clear, I agree and will work on it.

I agree with you. But what makes me feel confused is that in the first example of these two examples, hello is put into state data through datainputpath, and the field is hello. But in the second example, we get the fires state data, but there is no firuits field. It confused me.

**Comment by tsurdilo** [comment]
@sky132333 
regarding **hello is put into state data through datainputpath** - this is not the case, this property filters the original data input to the state (which can be either the output of the previous state, or the workflow data if its a starting state). Filters cannot create data, they can only filter existing ones.

so in this example, there has to be existing state data input which has to include a "hello" field already. Hope this helps

**Comment by ricardozanini** [comment]
@tsurdilo about this statement:

>  Filters cannot create data, they can only filter existing data.

I think with #149 we can also address this problem?

**Comment by tsurdilo** [comment]
@ricardozanini we have  inject state which is a "pass" state that include data manipulation already. Not sure yet how all this can fit together but we will discuss.
