### ISSUE TITLE
Question about ”State data filtering - Using multiple filters “

### ISSUE THREAD

**Issue by skyshaokai** [serverlessworkflow/specification#202]
**What is the question**:
in  spc：https://github.com/serverlessworkflow/specification/blob/master/specification.md#-state-data-filtering---using-multiple-filters

Question 1 ：
 "dataInputPath": "{{ $.hello }} "  ，after "dataInputPath" is evaluated and filters . The current state data should be：
{
      "english": "Hello",
      "spanish": "Hola",
      "german": "Hallo",
      "russian": "Здравствуйте"
  }
instead of
{
  "hello": {
      "english": "Hello",
      "spanish": "Hola",
      "german": "Hallo",
      "russian": "Здравствуйте"
    }
}

because JsonPath ： $.hello  result  as follows :
![image](https://user-images.githubusercontent.com/11512967/101899300-8ed97700-3be8-11eb-995a-f68520d5d787.png)

Question 2：
In the example  ：
"greetingFunction" returns:
{
   "finalCustomerGreeting": "Hola John Michaels!"
}

action ："dataResultsPath": "{{ $.finalCustomerGreeting }}"
after "dataResultsPath" is evaluated and filters. Why is the "finalCustomerGreeting" field action result is merged into state data. for JsonPath  $.finalCustomerGreeting the result not contain "finalCustomerGreeting"：

![image](https://user-images.githubusercontent.com/11512967/101900304-386d3800-3bea-11eb-9dbd-1f17cff3ccc8.png)
So should be  just  "Hola John Michaels!" merged into state data ?  If not ，What exactly does action "dataResultsPath" mean?  
In the specification, the description of "dataResultsPath" is "JsonPath expression that filters the actions data result, to be added to or merged with the states data" (https://github.com/serverlessworkflow/specification/blob/master/specification.md#-state-data-filtering---action-data-filter).
Is the meaning of this description should be to select and filter action result only as JSON path. It does not say what field name has been put into state data for the filtered result ?

**Comment by tsurdilo** [comment]
@sky132333 the idea is:
1) the actionDataFilter dataResultsPath is going to be evaluated after results of the action is available. The expression takes in the data and says to merge it with the "finalCustomerGreeting" element of the state data. If this element does not exist, the merging shall create one.
2) The stateDataFilter dataOutputPath is evaluated before state transitions (or workflow ends if end def is defined) and filters the state data to only include the finalCustomerGreeting field. 

I will update this section to make it more clear and make sure there are no issues with the evaluated jsonpath expressions.
Will do this asap.

**Comment by sky132333** [comment]
> @sky132333 the idea is:
> 
> 1. the actionDataFilter dataResultsPath is going to be evaluated after results of the action is available. The expression takes in the data and says to merge it with the "finalCustomerGreeting" element of the state data. If this element does not exist, the merging shall create one.
> 2. The stateDataFilter dataOutputPath is evaluated before state transitions (or workflow ends if end def is defined) and filters the state data to only include the finalCustomerGreeting field.
> 
> I will update this section to make it more clear and make sure there are no issues with the evaluated jsonpath expressions.
> Will do this asap.

Thank you very much. 

If we assume that"greetingFunction" returns:
{
  "greeting": {
    "finalCustomerGreeting": "Hola John Michaels!"
  }
}
and  
action ："dataResultsPath": "{{ **$.greeting.finalCustomerGreeting** }}" . So after "dataResultsPath" is evaluated and filters is the result to be :

{
  "greeting": {
        "finalCustomerGreeting": "Hola John Michaels!"
   }
}
and merged to state data  as:
{
  "hello": {
      "english": "Hello",
      "spanish": "Hola",
      "german": "Hallo",
      "russian": "Здравствуйте"
    },
    "customer": {
       "name": "John Michaels",
       "address": "111 Some Street, SomeCity, SomeCountry",
       "age": 40
     },
     "**greeting**": {
        "finalCustomerGreeting": "Hola John Michaels!"
     }
}

Is that right?

In addition，in some cases action dataResultsPath maybe complicated . For example , If we assume that"greetingFunction" returns:
{
    "store": {
        "book": [
            {
                "category": "reference",
                "author": "Nigel Rees",
                "title": "Sayings of the Century",
                "price": 8.95
            },
            {
                "category": "fiction",
                "author": "Evelyn Waugh",
                "title": "Sword of Honour",
                "price": 12.99
            },
            {
                "category": "fiction",
                "author": "Herman Melville",
                "title": "Moby Dick",
                "isbn": "0-553-21311-3",
                "price": 8.99
            },
            {
                "category": "fiction",
                "author": "J. R. R. Tolkien",
                "title": "The Lord of the Rings",
                "isbn": "0-395-19395-8",
                "price": 22.99
            }
        ],
        "bicycle": {
            "color": "red",
            "price": 19.95
        }
    },
    "expensive": 10
}

and  action ："dataResultsPath": "{{ **$.store.book[0,1].category** }}" . In this case, what is the result after merge into state data ？When JsonPath expression  is Indefinite (contains ?(<expression>) or [<number>, <number> (, <number>)] ) ，it is difficult to determine which key to use when merge action function result into state data.

I suggest that we can learn from aws （https://docs.aws.amazon.com/step-functions/latest/dg/input-output-inputpath-params.html ）, use "ResultSelector"  provides a way to manipulate the state's result before ResultPath is applied，and  use ResultPath to control which combination of these is passed to the state output. In this way we can control where to take the data from the function return and merge it into the state data.
