### ISSUE TITLE
Workflow invocation bindings

### ISSUE THREAD

**Issue by manuelstein** [serverlessworkflow/specification#206]
**What would you like to be added**:
A workflow can currently be designed to be triggered by events (using event-type state as starting state) and it can be scheduled (using scheduled start state). The "default" starting kind leaves it to the runtime with no API spec of the workflow invocation (e.g. the data expected). The discussion around the scope (public/private) has led to the idea of allowing different bindings of the workflow.

**Why is this needed**:
Workflow invocation bindings, in general (event, scheduled, OpenAPI, gRPC), are crucial to the way the workflow interacts with its environment. The entry point to the workflow (starting state) should be reusable (regardless whether the input data comes from a CloudEvent, an API or some other structured message). But at the same time, the semantics of a state may depend on the input method, e.g. trigger by a certain CloudEvent type may use a different starting state than the entry point of an API call.

**More info**:
The binding of a workflow to an API is currently left to the runtime. It should be possible to bind a workflow to one method or another, define access control (which requires AuthZ and AuthN), etc. There's a trade-off between making these part of the workflow or separating them out. AuthN and AuthZ, for example, is something I'd expect not to be part of the workflow definition.
Serverless Workflows may separate the spec of bindings, which would separate the data communication method (event, API call) from the workflow definition. We could also define invocations as part of the workflow (where starting states are defined).

**Comment by tsurdilo** [comment]
We should discuss high-level access control in terms of "participants" but should IMO only provide this on a very high level (domain specific) as the actual access control should be governed by the runtimes. 

Currently we specify that if workflow has a starting event state it is triggered by an event or a series of events. This is also high-level as that can for runtimes mean messages pushed to a topic, or an email, or smoke signals, and there is no restriction for runtimes to not expose that workflow still as an http endpoint and trigger it that way as well. 

Should always look at this from the standpoint of control-flow logic and business requirements solution. 

Hope this helps some. I would like to see your ideas on the access control stuff, would be really nice to work on that for the near/far future.

**Comment by jensg-st** [comment]
I think it should be part of the implementation. In my opinion an implementation will wrap an API around it which should normalize the input and forward it to the workflow. If you need different starting states then there are sub-flows to do that for example.

In general I think if you need different start states you are looking at different workflows anyway and you workflow should be technology agnostic.
