### ISSUE TITLE
Function invocations (gRPC)

### ISSUE THREAD

**Issue by manuelstein** [serverlessworkflow/specification#207]
**What would you like to be added**:
Functions can currently be called using OpenAPI specs. The idea is to also allow the use of gRPC APIs (and maybe others, such as AsyncAPI, plain HTTP calls, etc). 

**Why is this needed**:
These may be optional to be supported in the spec (making OpenAPI mandatory), but when specified, at least it would clarify how function invocations performed by the workflow would bind to service protocols other than the OpenAPI kind.

**Comment by tsurdilo** [comment]
I would like for us to look at this part of our language extensions if possible. 
Similar concept as to what CE has for their protocol bindings.
