### ISSUE TITLE
Clarification on the relationship between Serverless Workflow and Argo Workflow

### ISSUE THREAD

**Issue by YiannisGkoufas** [serverlessworkflow/specification#209]
Hi, I was looking at the examples for Argo ( https://github.com/serverlessworkflow/specification/blob/master/examples/examples-argo.md ) and I wanted to ask some more details regarding the roadmap.

- Will Argo support (is it supporting already?) the Serverless Workflow specification in the future?
- Will there be a converter Serverless --> Argo Workflow ?

Thanks!

**Comment by tsurdilo** [comment]
Hi @YiannisGkoufas thanks for the question.

1) I believe this is a better question for the Argo project. Our projects are collaborating but I am personally not aware of current efforts to integrate Serverless Workflow language. @alexec would you be able to help with this question please?

2) Existing/new workflow runtime impls can use parse Serverless Workflow language to an execution model of the runtime. 
I am not sure why a language-to-language converter would be necessary. 

Hope this helps!
