### ISSUE TITLE
Group dataInputSchema/dataOutputSchema

### ISSUE THREAD

**Issue by jensg-st** [serverlessworkflow/specification#213]
**What would you like to be added**:

Replace the `dataInputSchema` and `dataOutputSchema` parameters attached to each state with a single object `dataSchema`, which has two analogous fields `input` and `output`. 

Alternatively, merge both fields with the `stateDataFilter` to group all four. Something like `stateData.inputFilter`, `stateData.outputFilter`, `stateData.inputSchema`, `stateData.outputSchema`.

**Why is this needed**:

I notice that `stateDataFilter` already groups two similar fields together. For consistency, the data schema fields should get the same treatment. This will consolidate the documentation about data schemas into a single place in the specification, and it will have a side benefit of making each state definition appear simpler and cleaner.

**Comment by tsurdilo** [comment]
@jensg-st makes sense. will work on it asap.

**Comment by tsurdilo** [comment]
@jensg-st https://github.com/serverlessworkflow/specification/pull/218. Please review when you get the chance.

**Comment by jensg-st** [comment]
Looks good to me
