### ISSUE TITLE
Multiple names for event definitions not needed

### ISSUE THREAD

**Issue by jensg-st** [serverlessworkflow/specification#215]
**What would you like to be added**:

The [Event Definition](https://github.com/serverlessworkflow/specification/blob/master/specification.md#Event-Definition)'s `names` parameter should be removed.

**Why is this needed**:

The specification states that an Event Definition can have either one `name` or an array of `names`, But there's no value added by defining multiple identical events by different names. The name serves no practical purpose, so having multiple identical events with different names doesn't add any value. At least we could not think of any example where this would be useful.

**Comment by tsurdilo** [comment]
@jensg-st Event definitions, like function and retry definitions can be reusable between multiple workflows. The name property is a domain-specific property which is used as a reference. Domain-specific to the workflow. As such this use case makes sense where you want to give the event a domain-specific name depending on the workflow context its being used in.

For example let's say you have two workflows that deal with bank transactions one having a scheduled interval from 9am to 5pm and another workflow with scheduled interval from 5:01pm to 8:59am. Both might be consuming events with same type and same source but might want to reference these events domain specific for example, "WorkingHoursTransactionEvent" and "AfterHoursTransactionEvent" respectively. Hope this helps.

**Comment by alankm** [comment]
If an event definition is reusable between workflows, doesn't it follow that it should *avoid* having any domain-specific properties?

If you think about it as analogous to creating a Java class to be imported by other programs -- or like a header file for C users -- a definition should have just one name. Then if necessary it should be up to the individual workflows using that shared resource to create local aliases for the global name.

**Comment by tsurdilo** [comment]
@alankm you can think of it as name aliases, or if you want to look at it from like a programming / java point of view a map with multiple unique keys and same values for each. hope this helps.

**Comment by jensg-st** [comment]
And again having information which changes based on attributes is not one of my all time favorites. If X is set the Y is important etc. Why not having names as an array with one element? Now I have two ways of defining a name; an array with one item or setting name. The array solution would make it easier and maybe cleaner. We can just ignore "name" I guess and then it works for us.

**Comment by tsurdilo** [comment]
@jensg-st i reopened the issue - agree with your last statement completely. Will work on it. thanks!

**Comment by tsurdilo** [comment]
@jensg-st after thinking about this i did pr (https://github.com/serverlessworkflow/specification/pull/220) that removes the "names" property per your original request on this issue. We do need @ricardozanini approval as afaik he was using / thinking of using this property.

**Comment by ricardozanini** [comment]
@tsurdilo I'll take a look at it next week once I have access to my computer!👩‍💻
