### ISSUE TITLE
'directInvoke' should be a bool

### ISSUE THREAD

**Issue by alankm** [serverlessworkflow/specification#219]
The `directInvoke` field on the `ScheduleDefinition` [data structure](https://github.com/serverlessworkflow/specification/blob/master/specification.md#Schedule-Definition) should be a bool type, rather than an enum. Or otherwise the specification should provide a list of valid enumeration types other than `"allow"`, which is the only example found.

**Comment by tsurdilo** [comment]
@alankm in the [spec workflow json schema](https://github.com/serverlessworkflow/specification/blob/master/schema/workflow.json) you can find the definition as:

```json
"directInvoke": {
          "description": "Define if workflow instances can be created outside of the defined interval/cron",
          "type": "string",
          "enum": [
            "allow",
            "deny"
          ]
        }
```

**Comment by alankm** [comment]
Ah, cool. I've been working solely from the markdown file. 

Are there any plans to add more enum values? Otherwise this still seems like it should be a bool.

**Comment by tsurdilo** [comment]
@jorgenj wdyt? to me @alankm makes a good point here.

**Comment by tsurdilo** [comment]
@alankm the [workflow schemas](https://github.com/serverlessworkflow/specification/tree/master/schema) should be the "source of truth" for the language definitions. 
Sometimes details like this might be missing in the specification markdown, feel free to open prs with fixes where you find things missing :)

**Comment by jorgenj** [comment]
Seems reasonable to me, I can't think of a reason why 'directInvoke' would be something other true or false.

**Comment by tsurdilo** [comment]
@alankm pls review https://github.com/serverlessworkflow/specification/pull/222

**Comment by alankm** [comment]
Looks good to me.
