### ISSUE TITLE
Start defining specification compliance (levels)

### ISSUE THREAD

**Issue by tsurdilo** [serverlessworkflow/specification#233]
**What would you like to be added**:
We need to start defining specification compliance levels. At this time it is assumed that compliance means 
runtime impl of every define language construct in a specific spec release.

We should start a discussion on this at least to see what makes sense to do at this time.

**Why is this needed**:

**Comment by manuelstein** [comment]
I think at this point, we're assuming 100% coverage for compliance, correct? What diversification do you have in mind?

**Comment by ricardozanini** [comment]
I think this is worth adding since each implementation might have its timing to implement every feature we have in the spec.

**Comment by tsurdilo** [comment]
@manuelstein @ricardozanini i was thinking along the lines of functionality, for example using some common terms such as 
"pipeline" possibly no need for being compliant with events and functions
"stateless" compliance that might not need have to deal w/ the new stuff we proposing to add like "keepAlive" etc
"full" - everything 

better ways prob exist ..but something along those lines maybe

**Comment by ricardozanini** [comment]
I liked this idea. We could group features and give "levels" to them. This way, implementations could track their "level" of implementation on their roadmap. Is that what you are saying?

**Comment by tsurdilo** [comment]
@ricardozanini yeah and ontop we can map changes to certain buckes..so like if a runtime specifically uses sw for stateless orchestration then thinks like that keepAlive thing that we discussed for so long would not apply as that would be part of the "stateful" compliance bucket...

**Comment by ricardozanini** [comment]
Makes sense to me. The Operator SDK has something similar. Take a look: https://sdk.operatorframework.io/docs/advanced-topics/operator-capabilities/operator-capabilities/.

We can use this doc as a reference or grab some ideas.
