### ISSUE TITLE
Need repeat execution of state

### ISSUE THREAD

**Issue by keepupon** [serverlessworkflow/specification#239]
What would you like to be added:
Hope to support repeat execution of state.

Why is this needed:
In some cases, we need to run some states repeatedly for x times (without parameter, can't use ForEach). Although we can put the same action in x states to resolve this scenario, it is not convenient.

**Comment by tsurdilo** [comment]
@keepupon very nice suggestion. I think we can solve this by adding looping to SubFlow state. 
this could include parameters:
"expression" - loop as long as this evals to true
"max" - loop max value

wdyt?

**Comment by keepupon** [comment]
@tsurdilo thanks for reply
"max" will meet our case,
and it would be even nice if we can get control of more error handling, another parameter to define if the loop should exit when subflow run into error, just for example.

as for "expression"，should we make another effort to change the evaluation each time (**count--**) ?  then that may not be our choice.

**Comment by tsurdilo** [comment]
@keepupon 
i like the idea on the loop continuation decision on unhandled errors. thanks.
here is the idea i would propose and we could discuss from there:

SubFlow State -> Loop Definition:
* expression (type string): expression which must evaluate to true/false. SubFlow will loop as long as this expression is true. If not defined, the max property must be defined to limit the loop count
*  checkBefore (type boolean, default true): control if expression is evaluated before or after each loop iteration
* max: (type int, default 1): max loop iteration
* continueOnError (type boolean, default false): should looping continue if an unhandled error is propagated from subflow to parent workflow. Note this must be an error which is not explicitly handled by the SubFlow state "onErrors" definition.

I think with this it will provide you with the needed functionality but also adds more to looping for some more advanced situations. For your use as I understand then you could have, for example:


```json
{
    "name": "LoopingSubFlow",
    "type": "subflow",
    "workflowId": "mysubflowstateid",
    "loop": {
       "max": 10,
       "continueOnError": true
    }
}
```

So you would not use the expression param, which might be useful in some cases for other users. 
Note that the loop counter is hard to express imo with the workflow language and should be
handled by the runtime impls.

wdyt?

**Comment by tsurdilo** [comment]
I think with errors, if the subflow state defines explicit onErrors definition then looping should discontinue anyways as the onerrors will handle the transition to the next workflow state / end. Hope this helps.

**Comment by tsurdilo** [comment]
and just for me to remember, as far as compensation for subflow that has loop def, it would be compensated once when compensation is triggered, no matter how many "loops" it executed  when it was active.

**Comment by keepupon** [comment]
@tsurdilo Yea, that's exactly what we are looking for, tks
{
    "name": "LoopingSubFlow",
    "type": "subflow",
    "workflowId": "mysubflowid",
    "loop": {
       "**max**": 10,
       "**continueOnError**": true
    }
}

**Comment by tsurdilo** [comment]
@keepupon i reopened the issue until the work discussed here is done. will link it to a pull request so you can track progress.

**Comment by tsurdilo** [comment]
PR: https://github.com/serverlessworkflow/specification/pull/243

**Comment by jorgenj** [comment]
Hi @keepupon,  could you elaborate on use-case this is solving?  Perhaps a stripped-down example workflow would be helpful?   I'm struggling to understand why this can't be resolved with looping & control-flow logic in the sub-workflow instead of putting this repeat functionality on the SubFlow state.
