### ISSUE TITLE
Add back ability to set expression lang name in  top-level workflow param (default to jq)

### ISSUE THREAD

**Issue by tsurdilo** [serverlessworkflow/specification#250]
**What would you like to be added**:
Add "expressionLanguage" top-level param (string type, default "jq"). This would allow users to define up-front what expression language is going to be uses throughout the workflow definition.
**Why is this needed**:
https://github.com/tremor-rs has a requirement to use their https://docs.tremor.rs/tremor-script. 
CloudEvents is working on their specific expression language.
Same will be the case with other projects that are using / looking at / collaborating with SW. 
We do need a default expression language (jq) however should provide the ability for projects to define their own expression language when they have a hard requirement to use it.

**Comment by ricardozanini** [comment]
This is tricky for compatibility between runtimes, no?

**Comment by tsurdilo** [comment]
yeah but seems unavoidable in the end. some runtimes have hard requirements for specific expression syntax they have to use. i put in the related pr a note that portability can be affected if the default expression lang/syntax is not used.

**Comment by morigs** [comment]
I believe almost all runtimes will want to extend their workflows with custom functions. Perhaps it's better to implement custom function `tremor-script` in the runtime rather to add one more expression language?
This way workflows without custom functions will be portable and expression functions will always be clean and simple
