### ISSUE TITLE
Question: how to aggregate output across multiple branches or actions

### ISSUE THREAD

**Issue by jplane** [serverlessworkflow/specification#256]
There are several cases where multiple outputs need to be merged back into state data:

- Parallel State
-- each branch might produce its own output (correct assumption?)... what does the union of all branch outputs look like? how do you (for example) author a single output filter for the parent parallel state that acts upon individual branch outputs?
-- completion type will likely factor in here, too (XOR only produces a single element, the others produce multiple, etc.)
-- Branch does not have a name, which makes it hard to construct a synthetic output for all branches that let's you later identify the output from any given branch

- ForEach State
-- the spec defines OutputCollection which is fine, but suffers from the 'can't create a new node with JSONPath' problem (perhaps #216 is meant to address this?)

- Operation State with multiple actions (or any other use of 'Actions' array)
-- action has results path, so we can merge individual action results back into state data (which is good!)

These seem to be slightly different takes on the same general pattern of "merging multiple results back into the main workflow state". I think it would be useful to either define a common expected solution for this pattern in the spec, or at least to clarify the differences and why they exist.

Glad to help with that, if we agree its a worthy cause.  :-)

**Comment by tsurdilo** [comment]
@jplane thanks for submitting the issue!

* parallel state:
a) yes merging here is highly dependent on completionType param
b) definitely let's add "name" property to branch definition

* foreach state
a) jq will help alot with this. with jsonpath its assumed that the runtime has to create this. we also have pr for this: https://github.com/serverlessworkflow/specification/pull/249

* actions
a) definitely can look into this further to make sure to iron out any kink

+100 on working on defining data filtering and merging better, and you helping on this :)

**Comment by jplane** [comment]
Fantastic... appreciate the quick reply. I'll pull something together in a draft PR over the next day or so.

**Comment by jplane** [comment]
I'm wondering if we can solve this by extending the data filter concept:

- add parallel branch result data filter (one for each branch, defined on the branch entity)
- remove ForEachState.OutputCollection and add ForEachState.IterationDataFilter (applied to each result of the iteration, to merge back to state data)
- action input/results filter is fine as it is, I think

Thoughts? I'll submit a PR if we agree on the general direction.

**Comment by tsurdilo** [comment]
* +1 on per-branch data filter
* the problem with doing the proposed filter, especially with jq is that it could alter/change/modify the inputCollection array which the state iterates over and thats a big problem (like modifying the array/list while iterating it in programming). you would imo have to specify that the IterationDataFilter can access the outputcollection object, but with jq i do not atm see a benefit of that as jq can do it alone

thoughts?

**Comment by jplane** [comment]
RE: problem of proposed IterationDataFilter modifying the InputCollection... agreed, but that problem still exists today anyway (Input/OutputCollection could resolve to the same collection, even with different jq expressions, etc.)

For me, the simplest solution has the fewest moving parts, and borrows from concepts that already exist elsewhere. DataFilter is one of the best parts of the existing spec, and appears in many places... which makes it familiar for workflow authors and promotes modular design/implementation for devs building runtimes (hopefully, anyway ;-) ).

I'm almost of the opinion a minimalist implementation like this would be ideal:

- remove ForEachState.InputCollection
- remove ForEachState.OutputCollection
- remove ForEachState.IterationParam
- make ForEachState.StateDataFilter required
- implementation note... ForEachState.StateDataFilter.DataInputPath should produce a JSON array (runtime error if not) where each element is implicitly the input an iteration, no need for an extra "iterationParam" property in that input
- implementation note... ForEachState.StateDataFilter.DataOutputPath should define where to insert/append output collection (jq is good for this, as already noted)

Again, I think this minimizes the moving parts and leverages concepts like data filters that already exist.

**Comment by tsurdilo** [comment]
@jplane i have some questions about this, will try to explain and let me know what you think:

1) it moves the complexity from "inputCollection" to the filter and makes the foreach states data filter "special/different' than for other states -> having to produce the iteration array in the data filter may remove some other state input data that is needed for the actions that are executed in the foreachstate iterations. also the foreach states state data filter now  also has a special use now that does not apply to any other state data filters (in addition to it now being required which is not the case in other states).

2) unlike with a "loop" (repeat in subflow states for example) the foreach state is executed only once. therefore its state data filter (datainputpath and dataoutputpath) is be executed only once as well, when the state is started and before it ends.
for filtering of the results of each action execution in foreach state you should probably use the event data filter, and if user defines a workflowid instead, the filter then applied in that sub-workflow (basically that sub-workflows data output should be added to the outputcollection.

wdyt?

**Comment by tsurdilo** [comment]
@jplane 
Regarding ** but that problem still exists today anyway (Input/OutputCollection could resolve to the same collection, even with different jq expressions, etc.)** : good point, we really need to add in spec that input and output collections should not be the same (if its not already in the spec doc). runtime impls should assure that is not the case...or dont worry about it which will most likely result in runtime exceptions during execution (user error :) )

**Comment by jplane** [comment]
Okay, you raise some valid points about ForEach. So perhaps this:

- add ParallelState.Branch.DataOutputFilter (as discussed above)
- keep ForEachState.InputCollection and .OutputCollection
-- I suggest an implementation note that runtimes either a) detect and prevent overlap between InputCollection/OutputCollection (which might be hard/slow from a practical standpoint) or b) operate against a copy of InputCollection so that modifications via OutputCollection don't affect ForEach processing
- eliminate ForEachState.IterationParam (its not clear to me why we need this at all vs. just pass the input collection element directly as input for each iteration)
