### ISSUE TITLE
Misuse of the term parameters

### ISSUE THREAD

**Issue by morigs** [serverlessworkflow/specification#261]
Term `parameters` is used all across the specifications. One of examples is `parameters` field in `parameters`.

But actually it's about the [arguments](https://stackoverflow.com/questions/1788923/parameter-vs-argument).
it is very confusing on first reading and leads to confusion.

Consider changing `parameters` to `arguments` or similar

**Comment by tsurdilo** [comment]
+1
will work on it

**Comment by tsurdilo** [comment]
https://github.com/serverlessworkflow/specification/pull/263
