### ISSUE TITLE
"Active paths" concept/semantics need elaboration and precise definition

### ISSUE THREAD

**Issue by jplane** [serverlessworkflow/specification#262]
There are several places in the spec that mention workflow "active paths", usually around the concept of workflow instance lifetime, the "keepAlive" property, etc.

https://github.com/serverlessworkflow/specification/blob/master/specification.md#workflow-instance

At minimum, the spec should precisely define how such active paths can arise (what combination of definition constructs, etc.) It seems to have something to do with Parallel branches that may not have finished yet, ForEach iterations that haven't finished yet, SubFlows that haven't finished yet, etc. Anything else? The spec isn't very precise here, which is a big problem for implementors.

Taking a step back... unless I'm misunderstanding (always a possibility :-) ) the concept of "multiple active paths" suggests that states can take transitions prior to all the "child" work underneath that state being complete. If that's the case, a few thoughts:

- Such a concept seems pretty foreign to most state machine implementations... perhaps with good reason?

- I'm concerned about the implications for (non)determinism of an engine that attempts to implement these semantics, and the difficulty (or impossibility) to reliably validate correctness. There's an infinite set of possibilities to test against, which again isn't something one would reasonably expect to encounter with a state machine.

- I think its fine (and frankly necessary in a cloud-native runtime) to support "fire-and-forget" actions where you don't wait for results to come back (and therefore don't attempt to rejoin them to state data). But this is not the same thing as "multiple active paths"... its still an action whose lifetime is bounded by its parent state, it just has the semantic that you start the action and then forget about it. That means the workflow itself shouldn't care about that action anymore, including attempting to cancel or otherwise clean it up (like seems to be implied with the End.Terminate construct).

Going a bit further... to promote any reasonable chance for multiple robust runtimes, I would strongly encourage that we eliminate the possibility of "multiple active paths" **except those bounded strictly by the lifetime of their parent state**. For example, ParallelState and ForEachState are fine, as long as their actions complete (from the perspective of the workflow itself) before their parent state transitions elsewhere. Again, fire-and-forget actions are fine... they simply complete as soon as they are invoked, with no waiting for a result.

This might mean (for example) changing the semantics of ParallelState to ensure branches that don't complete according to the CompletionType are canceled prior to transitioning away from the ParallelState. For example, if CompletionType = Xor, then the first branch that completes is the "winner", and the remaining branches are canceled immediately prior to transitioning from the Parallel to the next state. Etc.

I really feel its important to a) adhere to classic state machine semantics here and b) constrain possible behavior to be deterministic to make it possible to test and verify for correctness.

A and B from the last sentence are actually the same thing. :-)

Thoughts? (none of this would be short-term changes, of course... but, glad to help refine it, regardless :-) )

**Comment by tsurdilo** [comment]
For active paths, yes that would include parallel state branches with the completiontype set as well as waitForCompletion on subflow states. Don't think foreach state applies here as it should wait for all iterations to complete. 

I think that automatically cancelling all async running activities on a state transition or always having to wait for all async activities to complete before transition can happen is not the best idea. A workflow instance controls a single execution defined in the workflow definition. Async execution can be in many cases part of the business requirements, and there are cases where you want to to wait for the instance context to stay alive (even tho the control flow logic has completed) until they are done and update it. 
With what you are saying if I understand correctly is that when the control flow logic is complete that the instance should also automatically complete. If that's the case I think that this then fits more stateless scenarios and does not take in account many stateful orchestration needs. 
Maybe its best if we pick an example and discuss it with the two different ways of thinking described here and see the differences? WDYT?

**Comment by tsurdilo** [comment]
definitely agree on defining active path better. would be really great to have your help there!

**Comment by jplane** [comment]
_"automatically cancelling all async running activities on a state transition... is not the best idea"_

I actually agree with this... I was using that example above as a thought experiment, but realize now that wasn't clear. Sorry for the confusion. :-)

_"Async execution can be in many cases part of the business requirements"_

Agree 1000%. The spec already has CallbackState and some other constructs to represent this. Those are very necessary.

_"...and there are cases where you want to to wait for the instance context to stay alive (even tho the control flow logic has completed) until they are done and update it."_

I understand what you're describing, and I agree there are problems that fit this description that need a solution. The issue I have is two-fold:

1. The language and (mostly) semantics chosen for SWF is that of state machines (state, transitions, actions).... which is terrific, I'm strongly in favor of this and agree 1000% that the industry needs "state machines for the cloud" (it's frankly why I'm here :-) )

2. However... allowing states with child actions where the actions do not complete before the state transitions to another state, *and* where cleanup of those "multiple active paths" is done with End.Terminate, Workflow.KeepActive, and other artificial constructs is hiding the fact that *the workflow is really just in another state (the "waiting for async actions to finish up" state) and its hiding that important fact from the workflow author. These "lifetime rules" also make a reliable engine implementation much more challenging to build and test, which is a shame.*

Like I mentioned above, fire-and-forget actions are important. State A should be able to (for example) call an async REST API and then transition away before waiting for a response. Full stop, that's necessary. But the spec allows turning fire-and-forget into "fire-and-forget, and then later come around and remember again, using workflow lifetime rules outside the state where the action originated." IMO that makes robust implementations of this spec much much harder to achieve (I worry impossible, frankly).

IMO we shouldn't invent artificial things like End.Terminate or KeepActive to clean up active paths or harvest those results. Instead workflow authors should explicitly model the "waiting for results" behavior as yet another state. That's simple, nothing is hidden from the user behind boolean switches or flags, and we can actually build/test this behavior reliably. There's no need for workflow lifetime to ever exceed the lifetime of its child states (and to have all the extra "lifetime rules") if *everything that happens in the workflow is modeled as a state/transition/action.* Doing this would help ensure that all workflows are in fact state machines, which gives us a chance to build robust and reliable runtimes.

Take this example:  https://github.com/serverlessworkflow/specification/blob/master/examples/README.md#accumulate-room-readings

The reason we need End.Terminate, KeepActive, ExecLifetime, etc. here (and all their complexity) is because the workflow lifetime is tied to a single "event arrival + generate report" sequence. But there's no reason it has to be.

If instead you got rid of End.Terminate, KeepActive, ExecLifetime and simply transition from ConsumeReading to GenerateReport (after you receive all needed event instances for a given room/hour), and then from GenerateReport back to ConsumeReading (after you generate the report for a given hour), the same workflow instance can run forever and correlate events by room and by hour (maybe you could run separate instances per room if that's useful... whatever). Add in another explicit event and handler for terminating the workflow if you want (or provide some other means to shut it down) and you've solved the problem using states/transitions/actions (state machines!) without needing the other stuff.

This is very much stateful, very much serverless, very much workflow, and very much state machine.

_(As an aside... I realize many folks have come before me to define the spec up to this point, and I want to be very respectful of that. I think there are many really strong elements in what's there so far, but I really appreciate your willingness to consider other perspectives to help make it better. I know its hard to shepherd something like this with a group, and out in public. Thanks for considering what I've written.)_

**Comment by tsurdilo** [comment]
@jplane i will reply to your post (which is really great by the way!) but first wanted to address the last point you made: this project is 100% community driven (and completely relies on community contributions) so of course anything you say and contribute is fully considered (and much appreciated). Conversations just like this are exactly whats needed to grow SW and make it better so keep it going please :) 

I think it would be really great to have you join our weekly meetings and present your ideas around this to the group. Would it be possible to put you on the agenda for Monday March 1st maybe?

**Comment by tsurdilo** [comment]
@jplane 
I will try to explain the reasoning behind some of the properties mentioned just so we are all on the same page and then let's see how we can improve. 

"keepActive" - comparing to some other workflow dsls/runtimes this is called "ad-hoc" in BPMN / is the default setting in Cadence/Temporal where a workflow instance is active until explicitly terminated. There are I think two main reasons for having this: 1) Allows users to explicitly set when the workflow instance is terminated based on their requirements 2) Allows for long-running workflow scenarios, and scenarios where you never want to terminate a created workflow instance for example.
This could be modeled as a "forever waiting delay state" or maybe a state that does nothing and just loops to itself forever. From the users point of view, especially in large processes the idea was to add this property to alleviates them from possibly having to define 100+ of these "never ending" states / loops and instead puts this burden on the runtime to replace this construct , given the workflow definition, with whatever control flow logic it seems fit that keeps the workflow instance alive.
The intent was not to break the state machine concept or making it impossible to implement, but from the language level to make it easier to model very large workflows.

**Comment by tsurdilo** [comment]
"execTimeout" - comparing to some other workflow dsls/runtimes this is handled with an event subprocess (see https://github.com/serverlessworkflow/specification/blob/master/comparisons/comparison-bpmn.md#process-execution-timeout)  / by "setWorkflowExecutionTimeout" in Cadence/Temporal. 
This again can be modeled by individual timeout properties in some cases, but not always. For states that at the time of execTimeout triggers are "active", for example are waiting for a sync function call to return, or are running branches in parallel, it may not be possible to achieve the business requirement of stopping the workflow instance and all of its current activities at the exact time specified by execTimeout. 
Also this again very large workflows where having to model this would require adding specific impl in all your workflow states and also subflow states used (thus making them not reusable as the business requirements of this parents exectimeout would trickle into its workflow control flow logic).
Again, this can be modeled with control flow logic, but is just a convenience for the workflow implementors to easier model their business requirements and puts a burden on the runtime engine to replace it with the needed structure to maintain the state machine concept.

"runBefore": convenience parameters that allows users not to have to specify in large workflows possibly 100+ transitions to this state.

**Comment by tsurdilo** [comment]
@jplane I think the example https://github.com/serverlessworkflow/specification/blob/master/examples/README.md#accumulate-room-readings is a good thing to bring up. It is a small example and I think the value of it can be much better seen in large workflows. It's hard to do add very large workflow in the "examples" document.

Overall I do agree with almost all of the things you mentioned especially about not breaking the state machine rules. 
It would be great to have some examples that show how we can improve on this. 
Adding some "waiting" constructs represented as states and can fit the need would be great imo. 
The idea behind all this is not to add any "artificial constructs" but really to assist users from having to add many extra states and lines of code to model their requirements with the SW dsl.

Hope this explains some of the reasoning behind all of this :) 

What do you think could be the first thing we should look at to improve?

**Comment by jplane** [comment]
Hi @tsurdilo 

Thanks for your replies. I'm planning to attend the Monday meetings regularly (starting on 2/22) so I'll be glad to have a discussion about these things whenever the group is interested. Let's plan for that on 3/1.

I'm less familiar with BPMN but know the concepts in Temporal (at Microsoft we have a service called Durable Functions which is extremely similar to Temporal... I know DF very well)

https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-overview?tabs=csharp

I think my questions here mostly surround the "keepActive" concept and related need for End.Terminate. I think in classic state machines those concepts don't exist (and shouldn't exist). So SWF's use of state machine concepts like states/transitions seems (to me) at odds with the design choice to include KeepActive and End.Terminate.

You'll note that Temporal is not itself a "state machine engine"... you can build state machines using Temporal, but you can also build things that aren't state machines. And Temporal doesn't use terminology like "state" or "transition"... that seems like an intentional choice. In Temporal work happens in "activities" and control flow is implicit in the code you write (there are no formal state or transition concepts). So I see SWF and Temporal as occupying some of the same space but with different "atomic elements" for building blocks, and inevitably some different semantics as a result.

FWIW I'm actually fine with ExecTimeout and agree its a valuable way to reduce workflow author burden. I don't think ExecTimeout is fundamentally incompatible with state machines.

Maybe a fundamental question for SWF is... is it a spec for authoring "cloud-enabled state machines"? Or something else? I know what I'd like it to be :-) but I'm just one opinion.

Inspiration for my thinking comes from the "saga" enterprise/cloud pattern... some folks describe sagas as "event-driven, long-running, distributed state machines". That maps well to my thinking and the use cases I encounter in various customer work. And I can see where SWF could formalize this pattern into an industry standard, which would be great. But that may or may not map to the ultimate goals.

I hope to better understand those goals once I start attending the meetings. See you on Monday! :-)

**Comment by jplane** [comment]
FYI the discussion in #231 is related to this.

My interpretation of alankm's comments in that thread are that he has the same confusion as me... the spec allows:

1. use of actions where action execution outlives its parent state transition as an "active path" (and interaction with that "active path" does not happen through additional formal states + transitions)
2. creation of a state machine whose lifetime is not governed by its states alone, but by its states + synthetic properties like KeepActive and End.Terminate

The second item is a natural consequence of the first (if you allow "multiple active paths" then you need additional constructs to "clean them up" etc.)
