### ISSUE TITLE
Move start definition to top-level workflow properties

### ISSUE THREAD

**Issue by tsurdilo** [serverlessworkflow/specification#264]
**What would you like to be added**:
Move the "start" definition to top-level workflow properties
**Why is this needed**:
This might be easier for validators to assure there is a single workflow starting state. 
Currently with our schema there is no way to enforce a single starting state (or no starting state)
Only thing we do assure is that either a "start" or an "end" is required for most of the states where its applicable.

**Comment by singhkays** [comment]
+1 on this. There's just enough logic in the start definition that it makes sense for it to become its own state - https://github.com/serverlessworkflow/specification/blob/master/specification.md#Start-Definition 

Thinking about the user mental model, a user probably wants to define how the workflow gets triggered first and then think about defining what work will be done in the workflow.
