### ISSUE TITLE
Update action and event data filters

### ISSUE THREAD

**Issue by tsurdilo** [serverlessworkflow/specification#277]
**What would you like to be added**:
Action data filter: add additional property which defines which state data element to add the result of the action to (default ".")
Event data filter: add additional property which defines which state data element to add the event payload to (default ".')
**Why is this needed**:
currently we assume the action results / event payload is merged into top-level state data.

**Comment by tsurdilo** [comment]
open for suggestions on the naming of the new param in both filters

**Comment by jorgenj** [comment]
outputPath? outputMergePath?  mergePath?

Also, wondering if we should rename the existing dataOuputPath to more clearly indicate that it transforms the output?  Perhap outputTransform?  outputExpression?

**Comment by jorgenj** [comment]
I think another thing that's missing is a detailed description of the expectations for how a merge should be done.  Is it a shallow or a deep merge?  ie;

Given a state input of: 
```
{ data: { foo: bar }}
```

And an action just completed which returned the following:
```
{ data: { bar: foo} }
```

What would the merged result be?

If it's a shallow merge, I'd expect the output to be:
```
{ data: { bar: foo }}
```

For a deep merge, I think I'd expect:
```
{ 
  data: {
    foo: bar,
    bar: foo
  }
}
```

If we're thinking deep merges, then I think there's some complex scenarios to consider that I don't think there's a sane way to handle other than to throw a runtime exception, like...
* merging arrays `{data: [foo]}` + `{data: [bar]}`
* merging dis-similar data-types `{data: "foo"}` + `{data: ["foo"]}` + `{data: {foo: bar}}` + `{data: null}` + etc.

**Comment by tsurdilo** [comment]
The adding/merging should be done same as with the jq "+=" operator, meaning merge if possible and right overwrites left.

**Comment by singhkays** [comment]
I debated whether to create a new issue but since we're on this topic, I'd like to propose a simplification to data filters based on @jorgenj's comment above 

> outputPath? outputMergePath? mergePath?
> 
> Also, wondering if we should rename the existing dataOuputPath to more clearly indicate that it transforms the output? Perhap outputTransform? outputExpression?

### Problems
1. The description for these "paths" says it should be an expression but the name doesn't convey that semantic. 
2. Why do we have three types of filters (State + Action + Event data filter) with similar properties. For a new user it increases the breadth of things to understand especially when they are very similar

### Proposal
1. Combine State + Action + Event data filter into a generic "data filter" object. This can then be used wherever data filtering is required - State data, action data, event data
2. Simplify property names

### Examples
#### Merge path supplied
```
{
  "dataFilters": {
    "inputFilter": "${ {vegetables: .vegetables} }",
    "outputFilter": {
        "expression": "${ {vegetables: .vegetables[] | select(.veggieLike == true)} }",
        "mergePath": "path where the data will be merged"
  }
}
``` 

#### When merge path not needed
```
{
  "dataFilters": {
    "inputFilter": "${ {vegetables: .vegetables} }",
    "outputFilter": "expression": "${ {vegetables: .vegetables[] | select(.veggieLike == true)} }",
}
```

**Comment by tsurdilo** [comment]
@singhkays I like your idea. will try to work it in. 
there are two things I'd like your input on:
1) not all data filters have the same properties:
  - state data filter has input and output filtering. there is no adding/merging needed
  - event data filter has only output filtering (payload), and can include adding/merging
  - action data filter has input and output filtering and includes adding/merging
It's really hard to describe which properties would be required based on where this definition is placed (using json schema). so we would have to make all properties always available for users and hope they read the documentation to know which ones to used for a specific data filtering scenario..
  

2) Does using the same property name for all filters look ok or is it confusing. Here is a single state with 3 filters. wdyt?
```json

        {
            "name": "WaitForCustomerToArrive",
            "type": "event",
            "dataFilter": {
                "inputFilter": "${ .languageGreetings } ",
                "outputFilter": {
                              "mergePath": "${ .finalCustomerGreeting }"
                  }
            },
            "onEvents": [{
                "eventRefs": ["CustomerArrivesEvent"],
                "dataFilter": {
                    "outputFilter": {
                              "expression": "${ .payload.customer }",
                              "mergePath": "${ .customer }"
                  }
                },
                "actions":[
                    {
                        "functionRef": {
                            "refName": "greetingFunction",
                            "arguments": {
                                "greeting": "${ .languageGreetings.spanish } ",
                                "customerName": "${ .customer.name } "
                            }
                        },
                        "dataFilter": {
                             "outputFilter": {
                              "mergePath": "${ .finalCustomerGreeting }"
                          }
                    }
                ]
            }],
            "end": true
        }
   
```

**Comment by tsurdilo** [comment]
@singhkays the way I started working on this today, the example above would look like;
```json

        {
            "name": "WaitForCustomerToArrive",
            "type": "event",
            "onEvents": [{
                "eventRefs": ["CustomerArrivesEvent"],
                "eventFilter": {
                    "eventData": "${ .customer }",
                    "toStateData": "${ .customerInfo }"
                },
                "actions":[
                    {
                        "functionRef": {
                            "refName": "greetingFunction",
                            "arguments": {
                                "greeting": "${ .spanish } ",
                                "customerName": "${ .customerInfo.name } "
                            }
                        },
                        "actionFilter": {
                            "input": "${ greetings.hello }",
                            "results": "${ .greetingMessageResult }",
                            "toStateData": "${ .finalCustomerGreeting }"
                        }
                    }
                ]
            }],
            "stateFilter": {
                "input": "${ .greetings } ",
                "output": "${ .finalCustomerGreeting }"
            },
            "end": true
        }
  
```
what do you think? We could combine both of our ideas and just call it "dataFilter" property across the board as well. I just worry about readability but it's maybe not a big problem

**Comment by tsurdilo** [comment]
@jorgenj @singhkays - https://github.com/serverlessworkflow/specification/pull/278
