### ISSUE TITLE
Replace "jq syntax" with something better-defined

### ISSUE THREAD

**Issue by gibson042** [serverlessworkflow/specification#287]
#216 proposed interpreting Workflow Expressions as "jq syntax", and #249 implemented it. But jq syntax<a href="#user-content-note1">¹</a> and semantics<a href="#user-content-note2">²</a> have no formal specification, and vary across versions<a href="#user-content-note3">³</a>, across non-official implementations<a href="#user-content-note4">⁴</a> and even across the _same_ implementation on different hosts<a href="#user-content-note5">⁵</a>. `jq` is a great utility, but it should not be relied upon in an interop specification.

**What would you like to be added**:
The "standard" expressions should have fully-specified syntax and semantics, and therefore should not be "jq". [JMESPath](https://jmespath.org/) and [CEL](https://github.com/google/cel-spec) come to mind as solid replacement candidates.

**Why is this needed**:
A specification should not depend upon the happenstance of particular implementation choices, because that risks fracturing the ecosystem built upon it. Undefined/implementation-defined behavior should be minimized, and—where not possible to eliminate completely—should be _explicitly_ documented in order to warn practitioners about areas of potential incompatibility.

--------
<a id="note1">¹</a> Even something as simple as `. []` is ambiguous because https://stedolan.github.io/jq/manual/ does not define tokenization.

<a id="note2">²</a> https://stedolan.github.io/jq/manual/ does not define the behavior of [`length`](https://stedolan.github.io/jq/manual/#length) with numeric input (_although the version 1.6 `jq` binary returns the number itself, even if it is non-integer_), the syntax accepted by [`tonumber`](https://stedolan.github.io/jq/manual/#tonumber) (_although the version 1.6 `jq` binary accepts at least leading ASCII whitespace, leading +/- signs, leading zeroes, leading/trailing decimal points, and exponential notation, and rejects hexadecimal notation_), the complete behavior of arithmetic operators (_e.g., `1e999 + 1e999`, `0 / 0`, `infinite * 0`, `nan == nan`, etc._), or the behavior of `… as $__loc__` (_which the version 1.6 `jq` binary rejects_).

<a id="note3">³</a> For example, `test("\\p{Alphabetic}")` is not valid in the version 1.5 `jq` binary but is valid in version 1.6 because of an update to the embedded [Oniguruma](https://github.com/kkos/oniguruma) library.

<a id="note4">⁴</a> For example, [jackson-jq](https://github.com/eiiches/jackson-jq) does not support `$__loc__` or `?//` alternative destructuring, and [gojq](https://github.com/itchyny/gojq) does not use IEEE 754 for integers (so e.g. `9007199254740992 < 9007199254740993` is true in gojq but false in the version 1.6 `jq` binary).

<a id="note5">⁵</a> For example, [`strptime` and `strftime`](https://stedolan.github.io/jq/manual/#Dates) format strings vary by host operating system, as does the behavior of [math functions](https://stedolan.github.io/jq/manual/#Math).

**Comment by tsurdilo** [comment]
@gibson042 thanks you for all the info, very much appreciated. 

When using SW dsl you have the ability to specify your expression language of choice (see "expressionLang" param in workflow definition - https://github.com/serverlessworkflow/specification/blob/master/specification.md#workflow-definition-1). The default for v0.6  (to be released this month) was decided to be jq by the team.

We evaluated jq against JMESPath and found it to have a lot strong feature set. Not sure about CEL yet but will definitely look.

Will definitely address all the info you provided after our v0.6 release this month. Do you think that some issues could be alleviated by enforcing a jq version (e.g. 1.6) to make things better short term until we address this issue?

**Comment by gibson042** [comment]
> Do you think that some issues could be alleviated by enforcing a jq version (e.g. 1.6) to make things better short term until we address this issue?

It should definitely reference a specific version rather than the generic "jq", but doing so will only resolve a small fraction of these issues. The fundamental problem is that there is no actual definition of "jq" other than behavior of executable code compiled from a point-in-time snapshot of the https://github.com/stedolan/jq/ source, which doesn't lend itself to the purposes of defining or implementing a specification.

**Comment by jorgenj** [comment]
+1 for preferring JMESPath over JQ.  I was not very familiar with it when JQ was first discussed, but the more I look at JMESPath the more I like it better.  

* The formal specification and support for many programming languages is great.
* JQ also has some features that might be security problems for some runtimes, for example some of the features look like they could be used to leak details about the local filesystem of a runtime implementation.

**Comment by tsurdilo** [comment]
@alankm what are your thoughts on the mentioned issues with jq in this thread?

**Comment by alankm** [comment]
I can definitely understand the frustrations with the lack of a proper jq 'spec'. It's very surprising that -- in my opinion -- there are NO json query language specifications that actually meet users' expectations for a minimum feature set.

I wonder if this is a decision point where the project has to choose between either being a *real* spec, or a spec that can be used to make something *good*.

**Comment by tsurdilo** [comment]
@alankm thanks! definitely don't think a hybrid solution is a good thing either. i am working on a TCK for the spec for v0.7 and we should definitely use it to define expected results for many different expressions used

**Comment by gibson042** [comment]
> I can see why a spec would want to move away from jq. But my goal has always been to have something that is first-and-foremost good for end users. Leaving aside the massive advantage jq has over all competitors in that regard due to its long history and ample resources online, I just don't think any other json query language has the features needed to be truly useful.

I don't think it is good for users if there can be no guarantee their expressions in the "default language" will work on every conforming implementation.

> For example, consider the problem of removing a field from an object. With jq that's easy, no matter how complex the object: `del(.fieldName)`. [JMESPath cannot do this](https://github.com/jmespath/jmespath.py/issues/121).

Both [JMESPath](https://jmespath.org/) and [CEL](https://github.com/google/cel-spec) support custom functions, and it would be perfectly fine for this specification to define both a syntax by reference and a modified set of built-in functions that implementations are required to provide.

**Comment by tsurdilo** [comment]
I think we cannot 100% guarantee that the default expression language will work on all impls regardless of the language chosen. There will always be issues imo and thats where the TCK kicks in to save us :) 

There is also the question of popularity in community that is imo important and it seems that jq has the edge there by far (could be wrong).

Not a big fan of built-in functions for expressions being part of the specification. This is imo a maintenance nightmare waiting to happen. We do provide the ability to abstract reusable expressions in function defs I think thats a big plus.

Will schedule this to start discussing after v0.6 release and let's see where it goes :)

**Comment by ricardozanini** [comment]
I completely agree with @alankm and @tsurdilo here. Adding custom functions for runtimes to implement will be hard to maintain.

`jq` by far has more usage and popularity. Users can define their own functions there based on jq expressions, which we facilitate by having the `type: expression` in the function's definition.

I understand @gibson042 when he says that jq is lacking a spec. That was my first question when @alankm raised this issue in the past. We agreed that the TCK could make things easier for our users in terms of compatibility. Also, JMESPath relies on the implementation, whereas jq implementations are just wrappers around the main C library.

**Comment by gibson042** [comment]
> I think we cannot 100% guarantee that the default expression language will work on all impls regardless of the language chosen. There will always be issues imo and thats where the TCK kicks in to save us :)

Right now you can't even guarantee _validity_. Are you comfortable with the following being acceptable in design and testing but breaking in production (or being acceptable with one provider but not with another) because the backing implementation of "jq" is different and hits a syntax/semantics gap?
* `${ {people: [ .people [] | select(.age >= 40) ] } }` (syntax, whitespace)
* `${ .unsafeName | gsub("\\P{Alphabetic}"; "-") }` (runtime PCRE syntax)
* `${ 1 / .size }` (runtime arithmetic semantics)
* `${ .timeout + 10 }` (runtime arithmetic semantics)
* `${ .id == $savedId }` (runtime arithmetic semantics)
* `${ .count | tonumber }` (runtime numeric syntax)
* `${ { isoWeekDay: .posixEpochSeconds | strftime("%G-W%V-%u") } }` (runtime pattern syntax)

> Not a big fan of built-in functions for expressions being part of the specification. This is imo a maintenance nightmare waiting to happen. We do provide the ability to abstract reusable expressions in function defs I think thats a big plus.

By adopting a "language" with no formal definition, you are opting into that maintenance nightmare _now_.

> We agreed that the TCK could make things easier for our users in terms of compatibility

If TCK is functionally a conformance suite for implementations, then it is de facto the definition of this language—provided you are willing to build **and document** those aspects. But if it is instead a tool for users to test their input for validity, then it does not address these concerns because implementers cannot know what inputs users will be attempting.

> Also, JMESPath relies on the implementation, whereas jq implementations are just wrappers around the main C library.

It's always possible to mess up an implementation, but with a specification such mistakes can be unambiguously characterized—without it, there's no firm way to distinguish them from a different interpretation and resulting _permanent_ divergence.

> EDIT: @gibson042 please join our next meeting!

Sure, where are the details and instructions for attendance?

**Comment by jorgenj** [comment]
From the weekly community meeting, capturing this here for future discussions and for those wanting to evaluate alternative expression languages.

These are the gaps that were identified between JQ and JMESPath:

1. Many of the built-in functions in JQ, for example:
1.1 strftime, strptime, delete, regular-expressions
1.2 Others?
2. Support for deep merging of json objects
3. Ability to define custom functions

@manuelstein @tsurdilo @ricardozanini Please let me know if I missed anything. 

If we could define and write down somewhere the minimal set of features/functions from something like JQ that we would want to support, I think that could be very helpful.

**Comment by gibson042** [comment]
This issue is actually not stale, there just hasn't been any movement to address it.

**Comment by gibson042** [comment]
This issue is actually not stale, there just hasn't been any movement to address it.

**Comment by cdavernas** [comment]
IMO, that issue is indeed stale. Bottom line is there's nothing out there that is as practical as `jq` when it comes to querying/filtering json. Sure, it has its limitations, and a decent versioning capability is one of them. But let's face it, it's well documented, well adopted, stand-alone, cross-platform and has a crazy amount of irreplacable features. IMO, the quest to replace it somehow by something far worst and clunky is nothing but a dream. The question now is: should we keep on keeping that dream alive?

**Comment by cdavernas** [comment]
> it would be perfectly fine for this specification to define both a syntax by reference and a modified set of built-in functions that implementations are required to provide.

IMO, no it wouldn't be fine to push on implementers further requirements simply for working decently with a third-party, exchangeable expression engine.

**Comment by cdavernas** [comment]
> I don't think it is good for users if there can be no guarantee their expressions in the "default language" will work on every conforming implementation.

Again, I disagree. We are not speaking of rocket science here. You give in the right json input to `jq`, it's gonna perform the exact same way on any number of implementations. If, of course, implementers decide not to pre-process workflow expressions for interpolation, and if you delegate all that SW-related work to a third party product, we do land on the minefield that made you guys open that huge issue about interpolation and the like, which does not make any sense to me.

I prefer having a pre-processor interpolating my expressions just before sending them into `jq` rather than having to define a zillion best practices (that are still gonna go down the drain at a point) JUST for the sake of using `jq` input variables...

**Comment by tsurdilo** [comment]
@cdavernas +100 
I think that this issue has been opened and re-opened without anyone being able to suggest a better alternative
will close it for now and possibly reopen in the future if really needed.

**Comment by ricardozanini** [comment]
+1000 @tsurdilo. Many thanks for your words, @cdavernas. You said everything that I'd like to say in this thread.
