### ISSUE TITLE
sdk in javascript/typescript

### ISSUE THREAD

**Issue by antmendoza** [serverlessworkflow/specification#288]
Hello, 

I am looking for a open source project to contribute, 

I have experience with BPM frameworks and I find everything around this specification very interested. 

Do you think that would be a good idea to have an sdk in javascript/typescript?

if not, is there any other (or better) way to collaborate?. I am used to code in Java and javascript/typescript and I am open to learn anything else. 

Thank you, 
Antonio

**Comment by tsurdilo** [comment]
Hi @antmendoza, having a spec SDK in javascript/typescript would be great (would prefer typescript if possible, but thats just a preference at this point). 

Please join our CNCF slack channel and ping me when you are ready to get started on this.

**Comment by tsurdilo** [comment]
Community Slack Channel: https://slack.cncf.io/ - #serverless-workflow

**Comment by tsurdilo** [comment]
@antmendoza and since you said you program in Java as well, there are tons of things to improve on on the Java SDK too ;)

**Comment by tsurdilo** [comment]
@antmendoza hi :) just wanted to see if there is anything we can do to help with the js/ts  sdk?
Let me know at what point we can start setting up the  project repository for it. 
Thank you!

**Comment by antmendoza** [comment]
Hi @tsurdilo, 
sorry I have been very busy with work, hopefully I will be working on the sdk again from thursday.

I have been testing libraries to generate the object model from the json schema, without modifying the json schema files, but no luck.  

So I am going to modify by hand the json schema to have the object model generated from it. Apparently with some modifications we will be able to have a decent set or classes with this library https://github.com/bcherny/json-schema-to-typescript

**Comment by antmendoza** [comment]
Hi @tsurdilo 
I have done some progress with the sdk-ts, it would be great to get feedback

We already have implemented fromSource (json/yaml), toJSON and toYAML https://github.com/antmendoza/serverlessworkflow-sdk-ts/blob/main/src/base-workflow.ts
- Test: https://github.com/antmendoza/serverlessworkflow-sdk-ts/blob/main/spec/base-workflow.spec.ts

Also the creation of some object models throught builders https://github.com/antmendoza/serverlessworkflow-sdk-ts/tree/main/src/model
- using it here https://github.com/antmendoza/serverlessworkflow-sdk-ts/blob/main/spec/applicantrequest.spec.ts

I have not implemented yet all the builders, I am doing modifications to the autogenerated models https://github.com/antmendoza/serverlessworkflow-sdk-ts/blob/main/src/model/workflow.ts, it is not properly generated as you can se here https://github.com/antmendoza/serverlessworkflow-sdk-ts/blob/main/src/model/workflow.ts#L1036
So what I am doing is addressing it while I am creating the builders

Please let me know what do you think so I can continue.

**Comment by tsurdilo** [comment]
@antmendoza wow, great job! thank you very much. 

if you are ok with the name "sdk-ts" I will create the stub repository here (https://github.com/serverlessworkflow) so you can star doing prs to move what you have so far, and we can improve/complete with subsequent prs later. wdyt?

**Comment by tsurdilo** [comment]
@antmendoza maybe "sdk-typescript" would be better?

**Comment by antmendoza** [comment]
@tsurdilo yes agree,  I think sdk-typescript is better. 

Ok, once the repo is created I am going to create a pull request, 

thank you.

**Comment by tsurdilo** [comment]
@antmendoza https://github.com/serverlessworkflow/sdk-typescript :)

**Comment by manuelstein** [comment]
closed as discussed in community meeting 12 Apr 21
