### ISSUE TITLE
Why use the 'State' nomenclature?

### ISSUE THREAD

**Issue by Neuroglia** [serverlessworkflow/specification#320]
**What is the question**:
Why make use of the 'State' nomenclature?

This is probably a stupid question, which certainly has been answered many times already, but why did you choose to name 'States' that way?

_DISACLAIMER: I'm not a native english speaker, as you probably have realized by now, so the following might be biased by my partial knowledge of the language._

The way is see it, a state is the same as google's define, which IMHO does not really apply to it.
> the particular condition that someone or something is in at a specific time.

I personally use the 'State' word in my code when describing the condition of an object, for example: SalesOrder.State.
In this case, I would be prefer, for ubiquitousness purpose, to be able to have something like:

```csharp
class WorkflowInstance
{

   WorkflowDefinition Definition { get; }

    WorkflowState State { get; }
    
    Step Step { get; }
    
    Step[] Steps { get; }

}

class Step
{

    StepDefinition Definition { get; }

    WorkflowState State { get; }

   ...
}

enum WorkflowState
{
   Pending,
   Executing,
   Suspended,
   Executed,
   Faulted,
   TimedOut
}
```

... which would be MUCH more ubiquitous and less confusing IMHO: 

```csharp
var workflow = GetMyRunningWorkflow(myInstanceId);
Console.WriteLine($"The workflow '{workflow.Definition.Name}' is in state '{workflow.State}' and its current step is '{workflow.Step.Definition.Name}'");
```

... than:

```csharp
var workflow = GetMyRunningWorkflow(myInstanceId);
Console.WriteLine($"The workflow '{workflow.Definition.Name}' is in status '{workflow.Status}' and its current state is '{workflow.State.Definition.Name}'");
```

What do you guys think?

**Comment by tsurdilo** [comment]
@Neuroglia it is not a "stupid" question at all, and yes we had and have ongoing discussions about this. 
We had requests for "step", "task", and also for keeping the current "state" nomenclature. 
Let's bring this up in one of our next meetings again and discuss.
@manuelstein I know you have been very active in this area - would you mind giving us your opinion on this please? Also, can we add this onto our agenda for one of our next meets?

**Comment by manuelstein** [comment]
Hi, that's indeed a design decision taken a while ago. The Serverless Workflow Language (SWL) describes a state chart, hence states.
Each execution of a Serverless Workflow has workflow data associated with it that is passed on during execution. The idea of the state chart is to have only one state control the workflow data at a time.
Tasks can be often various graphs and linked for order, but in principle allow the bag-of-task scheduler to run tasks concurrently.
Steps is similar to states in that they're typically taken one at a time, but AFAIU they typically lack a shared context. I'm actually missing related work that uses steps for a proper comparison.
State charts are well-known from the OMG UML equivalent.

**Comment by tsurdilo** [comment]
@Neuroglia @manuelstein thanks for all the info here. Let me know if this issue can be closed.

**Comment by Neuroglia** [comment]
@tsurdilo From where I stand, I believe you can close it, my question was perfectly answered!
