### ISSUE TITLE
Schedule `interval` field "R/<Duration>" pattern is not sufficiently defined

### ISSUE THREAD

**Issue by gibson042** [serverlessworkflow/specification#322]
The [Schedule](https://github.com/serverlessworkflow/specification/blob/main/specification.md#schedule-definition) `interval` field is defined as "ISO 8601 format", but ISO 8601 does not include any pattern like **R/\<Duration>**:
> **5.6.1 Means of specifying recurring time intervals**
> A recurring time interval shall be expressed in one of the following ways.
> 
> a) by a number of recurrences (optional), followed by a start and an end which identify the first time interval [_**R[\<Number>]/\<Start>/\<End>**, which is effectively useless unless the duration is short and within the same calendar day because not every day is the same length_];
> 
> b) by a number of recurrences (optional), followed by a start and a duration which identify the first time interval [_**R[\<Number>]/\<Start>/\<Duration>**_];
> 
> c) by a number of recurrences (optional), followed by a duration and an end which identify the last time interval > [_**R[\<Number>]/\<Duration>/\<End>**_]. 
> 
> In all cases, if the number of recurrences is absent, the number of occurrences is unbounded.
> 
> NOTE 1  In some applications, a recurring time interval is expressed by a number of recurrences (optional) and duration alone, because either the start or end is supplied out-of-band.

The field should be defined more precisely, and if it is important to include such syntax then it should do so clearly (unlike ISO 8601 itself, in which the note _implies_ that such a representation should be possible but doesn't explicitly define how), and specifically define how the start or end time is established.

**Comment by gibson042** [comment]
http://www.loc.gov/standards/datetime/iso-tc154-wg5_n0038_iso_wd_8601-1_2016-02-16.pdf is an obsolete draft, not the actual published ISO 8601:2019 (the actual text of which I quoted above).

**Comment by tsurdilo** [comment]
@gibson042 thanks! could you help us define that field more precisely please? That would really help

**Comment by gibson042** [comment]
Yes. How do you intend for implementations to establish the start time for "R/\<Duration>" intervals?
