### ISSUE TITLE
 How can the specification implementer support the new version？

### ISSUE THREAD

**Issue by skyshaokai** [serverlessworkflow/specification#325]
**What is the question**:
There is a big difference between the new version and the old version of the specification. How can the specification implementer support the new version?

**Comment by tsurdilo** [comment]
Hi @skyshaokai good question. As our specification matures we will have these kinds of growing pains but we need 
to make sure to keep them to a minimum. 

Currently we are at release v0.6 and are planning v0.7 for this summer. We plan to start v1.0 release candidates shortly after that. I think it is realistic that until the spec reaches v1.0 that can be lots of updates to the language given community feature and improvement requests. 

We do have plans to shorten our release schedule before v1.0 however so each release would include a smaller set of updates/changes which should make updates for implementors easier (and us as well). In addition we need to do a better job limiting breaking changes (especially around removing existing features). 

One thing that would really allow us to become more efficient with all this is community help. We are a 100% community-driven project and its success depends on community contributions.

Having more hands on deck to help us with defining and updating the roadmap, updating sdks, website, vscode plugin, etc etc would be really nice to have. We are looking for community contributors to not only raise issues or add improvements but also help with leading and helping maintain and improving all parts of our ecosystem.

So to answer your question, we have several plans in place to set up a much better release structure going forward and are working hard on it. At the same time we are looking for help to realize these plans faster. Any help is much appreciated!

**Comment by skyshaokai** [comment]
Thank you for answer.
