### ISSUE TITLE
Define/validate workflow input data

### ISSUE THREAD

**Issue by Neuroglia** [serverlessworkflow/specification#328]
**What would you like to be added**:

A spec to define workflow input data

**Why is this needed**:

This would grant the workflow the ability to verify and validate its input data, thus allowing it to fail fast in case of inadequate input.
It would potentially allow workflow clients/consumers to know ahead of time, in a declarative, ideally schema-based fashion, the kind of data that is expected to start running an instance of a specific definition.

What do you guys think?

P.S: Sorry for issues flooding, but my brain waves are being severely stimulated by this awesome project x)

**Comment by tsurdilo** [comment]
@Neuroglia we used to support this via a top-level "dataInputSchema" parameter which can point to a JSON schema. Runtimes can then validate the workflow data input against it. We decided to remove that feature until we got a request for it, and this is it :) 

I think we should add that definitely. We used to support it also on the state level but maybe that can wait until there is a request for that as well. 
WDYT?

**Comment by tsurdilo** [comment]
@Neuroglia I would suggest something like this:

1) string type (only schema has to be defined, failOnValidationError is default true here):
```json
"dataInputSchema": "URL_to_json_schema"
```

1) object type (if failOnValidationError needs to be set to false):
```json
"dataInputSchema": {
   "schema": "URL_to_json_schema",
   "failOnValidationError": false
}
```

we can shorten the parameter names if needed, just need an idea to what.
WDYT?

**Comment by Neuroglia** [comment]
@tsurdilo IMHO, your suggestion's perfect! I could definitly work with that!
