### ISSUE TITLE
Version attribute to be defined on the sub flow state

### ISSUE THREAD

**Issue by mswiderski** [serverlessworkflow/specification#329]
**What would you like to be added**:

Add version attribute to the sub flow state to allow to reference sub flow by id and version. The will enable simple way of utilising versions of workflows.

**Why is this needed**:

Currently it is not possible to use versions with sub flows as there is no way to add the version when defining the sub flow.
https://github.com/serverlessworkflow/specification/blob/main/specification.md#SubFlow-State

Moreover what I find a bit weird is that the `workflowId` attribute is not required and type is set to `boolean`. Could you please explain why is that?
![image](https://user-images.githubusercontent.com/904474/113484296-cd50b580-94a7-11eb-8867-0a1478116787.png)

**Comment by tsurdilo** [comment]
@mswiderski the id not being required is a typo, it is required in the schema. Will fix asap. 

+1 on adding version. 

Note that with https://github.com/serverlessworkflow/specification/pull/301 the subflow state will be replaced with a "subflow" type action, but this request still applies there as well.

**Comment by mswiderski** [comment]
alright, good to hear it's considered as valid enhancement. I will look into the other PR about moving to action.

**Comment by tsurdilo** [comment]
Property description fix: https://github.com/serverlessworkflow/specification/pull/330

**Comment by jorgenj** [comment]
I 100% agree with this idea of needing version to be settable.  I actually almost included it originally in #301 but I didn't want to complicate that PR because I wasn't sure how controversial that change was going to be.

**Comment by tsurdilo** [comment]
@jorgenj feel free to add it to #301 if you want. If not we can add it after
