### ISSUE TITLE
SwitchState: 'default' is a reserved word in many programming languages

### ISSUE THREAD

**Issue by jorgenj** [serverlessworkflow/specification#345]
**What would you like to be added**:

The 'default' parameter in Switch state conflict with the 'default' reserved word in many popular programming languages. 
 Should we consider renaming it?  Perhaps the name 'otherwise' or 'defaultCondition' would be acceptable?

**Why is this needed**:

The SDK's in several languages will have to do something special for this field (for example in the java sdk I believe it names the field '_default').   This adds extra complexity for maintainers of the SDK's and is a potential cause for some confusion for users of the SDK's.

**Comment by jorgenj** [comment]
This concern also applies to event-based switch, which also has a 'default' parameter.

**Comment by jorgenj** [comment]
I'm happy to push a PR for this if I can get some feedback on what the preferred property name would be.

**Comment by tsurdilo** [comment]
@jorgenj please name it "defaultCondition" as it would flow better with "dataConditions" and "eventCondition":

```json
{
      "name":"CheckApplication",
      "type":"switch",
      "dataConditions": [
        {
          "condition": "${ .applicants[?(@.age >= 18)] }",
          "transition": "StartApplication"
        },
        {
          "condition": "${ .applicants[?(@.age < 18)] }",
          "transition": "RejectApplication"
        }
      ],
      "defaultCondition": {
        "transition": "RejectApplication"
      }
    }
```

@manuelstein @mswiderski @ricardozanini you cool with that?

**Comment by tsurdilo** [comment]
> I'm happy to push a PR for this if I can get some feedback on what the preferred property name would be.

@jorgenj you ask and you shall receive ;) (assigned to you)

**Comment by mswiderski** [comment]
I opt for `defaultCondition`
