### ISSUE TITLE
ParallelState completionTypes values

### ISSUE THREAD

**Issue by jorgenj** [serverlessworkflow/specification#346]
**What would you like to be added**:

This is definitely a 'style' thing so feel free to close if you violently disagree, but I'd like to propose some names that I think are a bit more clear in their intent for the completionTypes.

Proposal:

Change the accepted values of completionType to: `all`, `any`, and `some`.
Change the name of the 'n' field to: `numCompleted`

**Why is this needed**:

Reasoning:

`and` & `xor` are most often encountered as boolean operators between 2 distinct values, so it's a bit confusing in this context where there are N parallel threads (not just 2).   `n_of_m` is a straight-forward choice, but the corresponding `n` field name is very ambiguous, it gives no clear context to it's meaning on it's own.

**Comment by jorgenj** [comment]
I'm happy to push a PR for this if it's agreed that the suggested names are acceptable.

**Comment by tsurdilo** [comment]
@jorgenj please use:

"and" -> "allOf"
"xor" -> "oneOf"
"n_of_m" -> "anyOf"
"n" -> "branchNum"

**Comment by tsurdilo** [comment]
> I'm happy to push a PR for this if it's agreed that the suggested names are acceptable.

assigned

**Comment by jorgenj** [comment]
> @jorgenj please use:
> 
> "and" -> "allOf"

Sounds good

> "xor" -> "oneOf"
> "n_of_m" -> "anyOf"

These 2 names are very similar, it seems like this might be confusing to users.  Looking to some examples from Java, the Stream interface has allMatch() and anyMatch().  'Any' in that context implies one or more, which I think is how the 'xor'/'oneOf' and so might cause confusion on what our 'oneOf'/'anyOf' do.  I'll just throw out some ideas here for consideration:
* `atLeast`
* `someOf`
* `numBranches` (yah, this might be weird if there's also a field with that name to specify the number, or perhaps it's good because it creates a connection to that field name?)

> "n" -> "of" (should not be 0)

This name also doesn't seem like it carries enough context.  How about `numBranches`?

**Comment by tsurdilo** [comment]
I think parameter names that you can actually use to describe the functionality are powerful:

Defines that state can transition when **all of** the branches complete...
Defines that state can transition when **one of** the branches completes...
Defines that state can transition when **any of** the branches complete...
Defines the number **of** branches that have to complete to transition ...

we can ask in meet what ppl think

**Comment by jorgenj** [comment]
> Defines that state can transition when **one of** the branches completes...
> Defines that state can transition when **any of** the branches complete...

These 2 statements are functionally equivalent, as far as I can tell.    Or does 'one of' specifically mean that it will only proceed if exactly one and only one branch has completed?  What if more than one branches complete concurrently?

**Comment by jorgenj** [comment]
PR: #351
