### ISSUE TITLE
Improve timeouts

### ISSUE THREAD

**Issue by tsurdilo** [serverlessworkflow/specification#352]
**What would you like to be added**:
* add timeouts section to docs

Actions:
* add action execution timeout
* add timeout before action invocation (TBD)

Workflow:
* add state execution timeout (global)

States:
* add state execution timeout (local)

Parallel state:
* add branch exec timeout (on state level / on branch level?)

**Why is this needed**:
need to improve dsl timeouts

**Comment by jorgenj** [comment]
For the "wait" timeout on an action, it sounds like the intent is to delay before executing the action.  What's the use-case you have in mind?  An alternative idea to consider is to have a "delay" action, rather than having a delay property on each action.  This would have some consistency with the existing pattern with Delay state, rather than having a delay attribute for every type of state. 

For parallel state, if there's already timeout for the action being added, then does it still make sense to have a timeout on the branch as well?

In general, the rest of the timeouts seem like good use-cases to support.

**Comment by tsurdilo** [comment]
I will update descriptions of things as working on this. 
These are timeouts not physical delays so think of it as 
"max time for an action to complete execution" (use case if it takes over 10 days ...move on)"
"max time for an action to ack its invoked" (use case how long to wait for possible ack before start issuing retries),,this is still TBD :)

**Comment by Neuroglia** [comment]
@tsurdilo this would be great IMHO. In Synapse, I did implement timeouts but was a bit restricted so far. This would help me to timeout rest actions and all different states. Total need!

**Comment by jorgenj** [comment]
> These are timeouts not physical delays (again sorry my description of this issue really sucks) , so think of it as
> "max time for an action to complete execution" (use case if it takes over 10 days ...move on)"
> "max time for an action to ack its invoked" (use case how long to wait for possible ack before start issuing retries),,this is still TBD as that would most likely involve action "heartbeat" as well :)

Got it, that makes a lot more sense, the original bit of text made it sound like that one was about adding some type of delay before executing the action.

So the "max time for an action to ack its invoked" timeout would allow for the an action to fail if that work doesn't get started in a reasonable time?  Like if there's a massive backlog in actions to be executed and not enough "worker capacity", then some of those actions might time-out?

**Comment by tsurdilo** [comment]
yes. yeah its "time to start" exec.
another thing you maybe think of for runtimes  is action heartbeat. lets
say you have an action that sometimes executes within  minutes but
sometimes can take an hour (long running actions).
 in that case you have to set the total exec timeout to more than an hour.
if that action fauls lets say within 50 seconds you will delay your entire
workflow execution until your exec timer fires.
for this some runtimes implement a heartbeat meaning the action reports
back to the runtime that it is "working".
the heartbeat timeout can be set to something much shorter so you can
cancel or retry an action as soon as you detect a failure and not delay
exec.
we cant enforce hearbeating i think but just trying to explain.
