### ISSUE TITLE
[Idea] Add "continue as new" period for for cron/interval 

### ISSUE THREAD

**Issue by tsurdilo** [serverlessworkflow/specification#353]
**What would you like to be added**:
for periodic ran workflows we need to define "continueAsNew" 
which means that if you have a periodically ran workflow
you can specify a time duration after which runtime needs 
re-parse the workflow def and run the next schedule instance of workflow "as new"
**Why is this needed**:

imagine workflow on a cron where cron defines once-per week execution for 10 years
during this years things change, your function definitions (endpoints / openapi/grpc defs)
your event sources change etc etc

continueasnew gives opportunity to update your workflow definition during this long running process after some set period of time

this could be possibly also triggered by an event rather than being hard-coded period/time in the definition

**Comment by Neuroglia** [comment]
@tsurdilo Wouldn't have the same effect than setting the version to `latest`, which would implicitly get latest version on each iteration?

**Comment by tsurdilo** [comment]
@Neuroglia this is just idea for now :) 
yeah i think idea is same with the diff that i think with "latest" you would imply that each time a new workflow def is deployed it would trigger update/migration of all active instances. this cannot be enforced on the spec level so expectation can vary across runtimes imo.

**Comment by tsurdilo** [comment]
@Neuroglia another use for something like that are execution logs ..probably again still maybe this does not necessarily belong in the dsl but if you have long running workflows you will eventually run into storage issues. this would allow you to move to new shard/table for example cause each "as new" would have new instance id

**Comment by jorgenj** [comment]
It seems like there should be a concept of a single 'live' version of a workflow, and only the 'live' version should have its schedule be executed.  All other versions that aren't the live version would be 'dormant', ie; they could be launched manually but if they have a 'schedule' defined it would not be active for that version.

**Comment by tsurdilo** [comment]
i have a different idea of how to use this -- will close this issue and open new one
