### ISSUE TITLE
Add "continueAs"

### ISSUE THREAD

**Issue by tsurdilo** [serverlessworkflow/specification#362]
**What would you like to be added**:

currently we support "transition" and "end definitions", neither allow us to chain workflow executions as we currently depend to call a workflow from a workflow as a function invocation or producing an event. 
In the cases where workflows are not exposed as services/functions and dont react to events it is impossible to do this.

add "continueAs" option where the current workflow execution ends (like with "end", but a new execution of a workflow starts right after, for example:

```json
{
            "name": "Simple State",
            "type": "inject",
            "data": {
                "count": 0
            },
            "continueAs":  {
                   "workflowid": "...",
                   "version": "....",
                   "data": "${ ..... }"
             }
        }
```

short cut form (no data is sent as the new workflow execution input):

```json
{
            "name": "Simple State",
            "type": "inject",
            "data": {
                "count": 0
            },
            "continueAs": "workflowid"
        }
```

**Why is this needed**:
this will allow us to cover some really interesting chaining use cases with our DSL.
this is not the same as subflow actions as their execution do not stop the execution of the parent workflow
and can now only be defined inside actions. 
ContinueAs can be used anywhere transition/end definitions are used which means you can use it 
on decisions for a switch state for example.

**Comment by jorgenj** [comment]
Am I correct in thinking that this could be accomplished via an end operation state with a single awaitCompletion=false subFlow action?

**Comment by tsurdilo** [comment]
You could but thats not from the DSL level describe what it really is ..its not a subFlow invocation but a workflow execution. Also it would also have to be a terminate end and not just end which then puts even more complex weird logic onto users , and also it does not fit our "action" definitions really as its not an action but a hard stop of current workflow and execution of new workflow.
ContinueAs also works well with switch state:

```json
"dataConditions": [
            {
              "condition": "${ .applicants | .age >= 18 }",
              "continueAs": "workflowid1"
            },
            {
              "condition": "${ .applicants | .age < 18 }",
              "continueAs": "workflowid2"
            }
         ],
         "defaultCondition": {
            "transition": "RejectApplication"
         }
```

**Comment by tsurdilo** [comment]
AWS also added a similar construct..just fyi - https://docs.aws.amazon.com/step-functions/latest/dg/tutorial-continue-new.html

**Comment by manuelstein** [comment]
Thx, I noticed that AWS didn't add any construct to the [ASL](https://states-language.net/), but instead, they're using a Lambda function that calls their workflow API to start a new execution.
Btw, there's an Azure solution in durable functions orchestration to [drop the context](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-eternal-orchestrations?tabs=csharp) as well.

IIUC we don't even need the service function, bc we can call a workflow from an operation state and not wait on the subflow's completion. Wouldn't that have the same effect?
