### ISSUE TITLE
Clarification on "interrupt"

### ISSUE THREAD

**Issue by kevinteg** [serverlessworkflow/specification#369]
**What is the question**:

Likely a very quick one:
`The interrupt property defines if the currently running instance should be allowed to finish its current execution flow before it needs to be terminated. If set to true, the current instance execution should stop immediately.`

Does current execution flow mean the active state (finish all actions, etc)?

**Comment by Neuroglia** [comment]
@kevinteg To my understanding, yes, but I wasn't there when this was defined. WDYT @tsurdilo ?

**Comment by tsurdilo** [comment]
meaning that its current execution flow / path should be able to finish (reach an end definition). maybe we should use "path" instead to be clear.

**Comment by kevinteg** [comment]
OK glad I asked.  Yes I think it would be helpful to add some wording there about what it means (and maybe an example use case).

Thanks!
