### ISSUE TITLE
Schema: add 'functionref' type

### ISSUE THREAD

**Issue by JBBianchi** [serverlessworkflow/specification#383]
**What would you like to be added**:
I think a functionref definition should be added to the [workflow schema](https://github.com/serverlessworkflow/specification/blob/main/schema/workflow.json)'s definitions. At the moment, the action [functionRef ](https://github.com/serverlessworkflow/specification/blob/main/schema/workflow.json#L345) property is described inside the property definition instead of pointing to an external definition like action [eventRef ](https://github.com/serverlessworkflow/specification/blob/main/schema/workflow.json#L376) or [subflowRef](https://github.com/serverlessworkflow/specification/blob/main/schema/workflow.json#L380). 

**Why is this needed**:
To keep a consistant way of referencing objects related to a workflow.

**Comment by tsurdilo** [comment]
good catch. yeah we should move it to definitions.
anyone up for doing this?

**Comment by tsurdilo** [comment]
https://github.com/serverlessworkflow/specification/pull/384
