### ISSUE TITLE
404 when trying to parse 'workflow.json' schema: 'secrets.json' not found

### ISSUE THREAD

**Issue by cdavernas** [serverlessworkflow/specification#394]
**What happened**:

A 404 is returned when trying to access the following url, when parsing the SW schema:

`https://serverlessworkflow.io/schemas/0.7/secrets.json`

**What you expected to happen**:

Everything to work as expected

**How to reproduce it**:

Try validating a workflow with any of the SDKs that support schema-based validation (TypeScript, .NET, ...)

**How to fix it**:

Add the `secrets.json` file into the [website's repo](https://github.com/serverlessworkflow/serverlessworkflow.github.io/tree/main/schemas/0.7) 

**Anything else we need to know?**:

Furthermore, the `id`specified in the [secrets.json file](https://github.com/serverlessworkflow/specification/blob/main/schema/secrets.json#L2) is incorrect.

**Environment**:
- Specification version used: 0.7.x

**Comment by tsurdilo** [comment]
good catch on the id! will fix asap. we merged the pr yesterday and just
havent had the chance to update website. will link the website commit when
it done

**Comment by cdavernas** [comment]
Thanks @JBBianchi for the `id`, he's the one that spotted it.

**Comment by tsurdilo** [comment]
https://github.com/serverlessworkflow/serverlessworkflow.github.io/commit/ce16f8bfe36b83b108078041c3d341c66f5db272

**Comment by tsurdilo** [comment]
@cdavernas this can be closed now i think

**Comment by cdavernas** [comment]
@tsurdilo it can! Many thanks!
