### ISSUE TITLE
Add Workflow Queries

### ISSUE THREAD

**Issue by tsurdilo** [serverlessworkflow/specification#397]
**What would you like to be added**:
Workflow queries allow users to query state data during / after workflow execution.
Workflow writers can define queries inside their workflow definition or in a separate json/yaml file.
Workflow queries are defined via expressions.
Workflow queries are read only, they should not in any way alter or influence workflow execution
Workflow queries should have a domain-specific name. Runtimes can determine how to expose queries depending on the technology used.
Exceptions/Errors raised during query evaluation should not influence workflow execution in any way. 

For runtimes:
* workflow queries should be running in their own set of threads which are not part of the main workflow execution.

TBD: Add a "workflow query" action type. This will allow powerful communication between workflows. 

**Why is this needed**:
Question is should this be part of the workflow definition or not :) Discussion welcome.
Maybe this is just a runtime thing, however it does bring another level of possible communication between workflow instances which can be of great value.

**Comment by janaganh** [comment]
hi @tsurdilo, 
These questions I have regarding workflow queries. I am still learning the spec, it might not relevant.

> Workflow queries allow users to query state data during / after workflow execution.

regarding state data available for querying, will it be state data from the last executed workflow state or will it be possible target the specific workflow state for querying even though it has completed execution and currently another different workflow state is executing. If its  the case is the output state data in each workflow state persisted?

> Workflow writers can define queries inside their workflow definition or in a separate json/yaml file.

Will queries need to be predefined, can it be there ad-hoc queries using CLI or API’s which can be used for debugging or other use-cases  

thanks
janagan

**Comment by tsurdilo** [comment]
> Will queries need to be predefined, can it be there ad-hoc queries using CLI or API’s which can be used for debugging or other use-cases

I think the queries should be pre-defined that way the workflow developers can ensure their validity (and there are probably some security issues around passing expressions to be executed to the workflow execution).


> regarding state data available for querying, will it be state data from the last executed workflow state or will it be possible target the specific workflow state for querying even though it has completed execution and currently another different workflow state is executing. If its the case is the output state data in each workflow state persisted?

Good question, I think since queries should be executed in a thread that is not the main workflow running thread, it should be the current executing workflow state data.

WDYT?
