### ISSUE TITLE
Add batching and sync option to ForEach state

### ISSUE THREAD

**Issue by tsurdilo** [serverlessworkflow/specification#401]
**What would you like to be added**:
Add batching ability to foreach state
Add ability to specify sequential exec of foreach state iterations
**Why is this needed**:
Currently we dont have batching ability. If data element for foreach has a million elements, we assume runtime would create a million threads to run in parallel. We should have ability to define (dynamic) batch sizes for each parallel processing of data
For sequential exec we need to be able to specify that . default is still going to be parallel so not a breaking update

**Comment by manuelstein** [comment]
Just to understand, the current option to batch is by pre-slicing the array into an array of arrays. E.g. [0,1,2,3,4,5,6,7,8,9] can be batched transforming it to [[0,1,2,3,4],[5,6,7,8,9]] with some expression.
So, this would achieve this without requiring the developer to do the (somewhat complex) expression for slicing?
Sounds okay.

**Comment by tsurdilo** [comment]
Yeah the idea is if you have 100 elements to say process "10 at a time" or something. Not sure yet what the best way is to express that but expression would be nice yes.
