### ISSUE TITLE
subFlow timeout

### ISSUE THREAD

**Issue by yzhao244** [serverlessworkflow/specification#418]
**What is the question**:
I have a question regarding Workflow Timeouts. :)

Since currently, the parallel state branch supports actions definition which can use subFlowRef, is the workflow timeout of the subFlow going to be overwritten by Action execution timeout or vise versa?

When I looked at the example of [Workflow Timeouts](https://github.com/serverlessworkflow/specification/blob/main/specification.md#workflow-timeouts), it looks to me that action execution timeout overwrites top-level workflow timeout.

**Comment by tsurdilo** [comment]
@yzhao244 Yes it will have to be like you describe. 
The parent workflow action timeout must take precedence of the workflow execution timeout defined inside the sub-workflow.

**Comment by tsurdilo** [comment]
@yzhao244 can this issue be closed?

**Comment by yzhao244** [comment]
@tsurdilo yes :)
