### ISSUE TITLE
Refactor `rest` Operation

### ISSUE THREAD

**Issue by cdavernas** [serverlessworkflow/specification#420]
**What would you like to be added**:

1. Rename the `rest` operation type into `openapi`: the actual REST operation is an `openapi` operation, and could therefore be confusing to some.
2. Create a `rest` operation type, which allows configuring a request from top to bottom, thus enabling out-of-the-box support for legacy systems.

The `rest` operation definition could look like this:

```yaml
- name: MyOperation
  operation: 'http://mysite.com/api/{pathParam}#POST'
  type: rest
```
And it's reference like this:

```yaml
- name: MyAction
  functionRef:
    refName: MyOperation
    arguments:
      headers:
        - name: headerParam
          value: 'headerValue'
      path:
        - name: pathParam   #references the {pathParam} value in the operation url
          value: 'myendpoint' #replaces the {pathParam} value in the operation url
      query:
        - name: queryParam
          value: 'queryvalue'
      cookie:
        - name: cookieParam
          value: 'cookievalue'
      body:
        firstName: Tihomir
        lastName: Surdilovic
```

**Why is this needed**:

1. Calling a cat a cat 😸 
2. Allows out-of-the-box support for legacy systems and broadens SW use cases even further 🔫 

**Notes for implementers**:

The idea is basically to allow users to somehow mimic an OpenAPI doc in place of a function reference's `arguments` property, thus allowing the invocation of "dumb" http services.

**Comment by JBBianchi** [comment]
Good idea!

Not 100% sure about the spec, for instance
```yaml
operation: 'http://mysite.com/api/{pathParam}#POST'
```
The # could be part of the url. I think a separated property for the verb/method would be cleaner.

Also, not sure having `cookie` is required, it's a set of headers after all?

**Comment by cdavernas** [comment]
@JBBianchi Great point for the `#`. But this wall just an example, a first glimpse. 
As for `cookies`, I added them because so does `OpenApi`, didn't even bothered to think 😄

**Comment by JBBianchi** [comment]
It might be easier to have cookies separated, not sure.

**Comment by tsurdilo** [comment]
@cdavernas @JBBianchi nice +1 on doing this.

The only two things I would change:
1. First the path param - make it an array of strings, for example:

       "path": ["a", "b", "${ .c}"]

and in your operation param you could do for example:

      "operation": "http://mysite.com/{1}/{2}/{3}"

2. Instead of hard-coding the method (post/put/get/delete) make it a property (enum) and make user pick it not in the function definition but where you reference it. That way you can reuse the same function definition in different states depending on what method user wants to call it with.

**Comment by cdavernas** [comment]
@tsurdilo Great idea! I'm gonna get working then!

**Comment by JBBianchi** [comment]
Not sure about the array thing, the named parametters are less enclined to introduce errors. With arrays, the use needs to count, removing, adding or moving an item is trickier then with named ones.

**Comment by tsurdilo** [comment]
@JBBianchi thats fair too, you could then make the "path" param an array of objects types that have name and value pairs if you wanted as well and have for example

      "operation": "http://mysite.com/{one}/{two}/{three}"

whatever you decide to do, this way you can with validation up-front tell user that "hey your function def needs 3 paths but you only defined 2" :)

**Comment by cdavernas** [comment]
@tsurdilo for the way I described path parameters, I used the OpenAPI way, which is verbose but, like @JBBianchi said, is IMHO somewhat cleaner and less error prone. Plus, it can be formatted as such by modern logging technologies and can be queried by Kibana, for instance.
As for the verb, you idea does make a lot of sense. However, that way, the `FunctionDef` has little if no purpose. That's why I wanted to delegate to it as much responsibility as possible. Actually, I even believe it should have a copy of the `arguments` property, to set up configuration work common to all invocations (typically, headers or query param values). WDYT?

**Comment by tsurdilo** [comment]
@cdavernas I think that if you delegate specific invocation info to functiondef you are losing reusability. What you could do is define something like "invocationTemplates" meaning in the function definition you could add 

```json
 {
  "name": "...",
  "operation": "...",
  "templates": [
    {
      "type": "rest",
      "arguments": {} 
    },
    {
      "type": "grpc",
      "arguments": {} 
    },
    {
      "type": "graphql",
      "arguments": {} 
    }
  ]
}
```

and then reference the template in the function ref and we can use {1}, {2} ... also to pass in params to the template.
wdyt?
If we just move the invocation info to function definition alone, then we remove reusability.
For functions that have a single type of invocation there is gonna be a single template and its really like what I think you are suggestion to do in those cases, but it helps with functions that might have multiple 
invocation types, for example CRUD type of functions.
wdyt?

**Comment by cdavernas** [comment]
@tsurdilo I'm not sure we are speaking of the same thing. Basically, I wanted to add a `configuration` or whatever property to the `functionDef` where you could set headers, path, cookies and query parameters that would be included (merged) into the `functionRef` arguments (which takes precedence and can therefore override values). That way, you could reuse a, say, POST function definition, with common headers values, for example, but with different payloads.

**Comment by cdavernas** [comment]
@manuelstein @ricardozanini you are both awfully silent 😭 
Any comments/ideas/suggestions? WYT about those ideas?

**Comment by tsurdilo** [comment]
@cdavernas ok.from the example it looks as those are all "arguments" in the function def and that threw me off. I think separating that name as in arguments/parameters vs like headers or metadata that would help

**Comment by ricardozanini** [comment]
I liked the idea and this will help us on Kogito to reuse some work :)

About the REST function definition _per se_, I like the [JAX-RS approach of using annotations](https://en.wikipedia.org/wiki/Jakarta_RESTful_Web_Services), we could leverage their docs to avoid reinventing the wheel. I remember proposing something like this in the past before having openapi functions. :thinking: 

```json
{
    "name": "GetPetById",
    "operation": "/pets/{id}",
    "type": "rest",
    "metadata": {
         "verb": "GET"
    }
}
```

Usage:

```json
{
  "name": "MyAction",
  "functionRef": {
       "refName": "GetPetById",
       "arguments": {
           "name": "id",
           "value": "$ .pet.id"
       }
   }
```

I'd let all the parameters defined in the `function` definition. Either in the `metadata` (worse) or create a new optional argument for parameter template/definition. Same for verb definition (GET by default, obviously). For POST/PUT operations, we can use the argument name `body` as default. In this case:

```json
{
    "name": "NewPet",
    "operation": "/pets",
    "type": "rest",
    "metadata": {
         "verb": "POST"
    }
}
```

Usage:

```json
{
  "name": "MyAction",
  "functionRef": {
       "refName": "NewPet",
       "arguments": {
           "name": "body",
           "value": "$ .pet"
       }
   }
```

Querystrings:

```json
{
    "name": "SearchPets",
    "operation": "/pets?name={name}",
    "type": "rest",
    "metadata": {
         "verb": "GET"
    }
}
```

Header/Cookies we rely on parameter definition:

```json
{
    "name": "Authenticate",
    "operation": "/auth,
    "type": "rest",
    "parameterDef": [{
         "type": "header",
         "name": "BasicAuth",
         "value": "$.creds"
     }],
    "metadata": {
         "verb": "POST"
    }
}
```

**Comment by tsurdilo** [comment]
@cdavernas should we move on this?

**Comment by cdavernas** [comment]
@tsurdilo with pleasure!

**Comment by cdavernas** [comment]
@ricardozanini Even though I like what you proposed, it seems a bit too loose to my taste, especially in the case of query strings. I'm not opposed to doing it that way, but woul definitly prefer something like what OpenAPI does, meaning allowing to specifiy the localtion of an argument (i.e. in:query).
For example you could very well call twice the same REST function, once with a query string param, the second time without. Your proposal wouldn't allow that, AFAIK.

WDYT?

**Comment by ricardozanini** [comment]
@cdavernas that proposal was just a dump from my brain that I come up with in five minutes. We can definitely improve it.

About calling the GET REST function twice without the parameter, you can just do this:

```json
{
  "name": "SearchPets1",
  "functionRef": {
       "refName": "SearchPets",
       "arguments": {
           "name": "name",
           "value": "$ .pet.name"
       }
}
```

```json
{
  "name": "SearchPets2",
  "functionRef": {
       "refName": "SearchPets"
   }
}
```
Without the argument, we can make the call without the querystring.

But I agree that we should enforce/make it more reliable instead of using `metadata`  fields for everything.

**Comment by JBBianchi** [comment]
Sorry for the late reply, I tend to agree with the principle with @ricardozanini but I also agree with @cdavernas remark.

Using a well established standard synthax, like the one of OpenAPI, is:
1. easy for users because it's a well known/documented standard
2. easy for the implementer because they already implemented OpenAPI

To summarize, the `Function Definition` should described the endpoint and its possible arguments:
```json
{
   "functions":[
      {
         "name":"get-my-pet",
         "type":"rest",
         "operation":"https://petstore.swagger.io/pet/{petId}",
         "metadata":{
            "get":{
               "parameters":[
                  {
                     "name":"petId",
                     "in":"path",
                     "description":"ID of pet to return",
                     "required":true,
                     "type":"integer",
                     "format":"int64"
                  }
               ]
            }
         }
      },
      {
         "name":"update-my-pet",
         "type":"rest",
         "operation":"https://petstore.swagger.io/pet/{petId}",
         "metadata":{
            "post":{
               "parameters":[
                  {
                     "name":"petId",
                     "in":"path",
                     "description":"ID of pet that needs to be updated",
                     "required":true,
                     "type":"integer",
                     "format":"int64"
                  },
                  {
                     "name":"name",
                     "in":"formData",
                     "description":"Updated name of the pet",
                     "required":false,
                     "type":"string"
                  },
                  {
                     "name":"status",
                     "in":"formData",
                     "description":"Updated status of the pet",
                     "required":false,
                     "type":"string"
                  }
               ]
            }
         }
      }
   ]
}
```
And then used by a `Function Reference` like any other:
```json
{
   "actions":[
      {
         "name":"Get My Pet",
         "functionRef":{
            "refName":"get-my-pet",
            "arguments":{
               "petId":"${ .petId }"
            }
         },
         "actionDataFilter":{
            "toStateData":"${ .pet }"
         }
      },
      {
         "name":"Update My Pet",
         "functionRef":{
            "refName":"update-my-pet",
            "arguments":{
               "petId":"${ .petId }",
               "name":"${ .pet.name }",
               "status":"sleeping"
            }
         },
         "actionDataFilter":{
            "useResults":false
         }
      }
   ]
}
```

WDYT?

**Comment by ricardozanini** [comment]
> Using a well established standard synthax, like the one of OpenAPI, is:

@JBBianchi, do you propose to copy the OpenAPI scheme? I think we all agree that we should rely on standards, so I'm happy if we embrace either JAX-RS or OpenAPI. We just have to establish the boundaries and what we support. 

This should be a "lightweight" version of the standard. We recommend interacting with legacy REST endpoints that do not offer an OpenAPI spec.

To be honest, what I did in the past was to create the OpenAPI spec myself and feed it to the engine. See this: https://apitransform.com/how-to-convert-postman-collection-to-openapi/.

I'm trying to say that instead of importing the OpenAPI standard to our metadata field, we point people to generate the OpenAPI spec even if the legacy endpoint does not offer one. Today is pretty straightforward to do it. So that could be a suitable option IMO.

**Comment by cdavernas** [comment]
> I'm trying to say that instead of importing the OpenAPI standard to our metadata field, we point people to generate the OpenAPI spec even if the legacy endpoint does not offer one. Today is pretty straightforward to do it. So that could be a suitable option IMO.

That's a valid point. Generating a spec doc is quick and easy. 

I'd however favour using @JBBianchi's suggestion, as yours might IMHO rebuke newcomers, force feeding them standards upon standards before they can even get to the point of a simple `wget`.

WDYT?

**Comment by ricardozanini** [comment]
I'm fine with it. We can use the metadata field to feed the operations. I can even reuse some bits of the OpenAPI generator based on that. 

I'd just like to see:

1. A clear boundary of what we support based on the OpenAPI
2. Add the possibility and the ways to generate the OpenAPI spec instead of using this rest function for a more "robust" approach.

**Comment by JBBianchi** [comment]
I think it's mostly verb: { parameters }, do you see anything else useful ?

**Comment by ricardozanini** [comment]
I think we need to carefully take a look at the spec and handle that thoroughly. Just skimming the doc, I could see fit for:

- [Parameters](https://spec.openapis.org/oas/v3.1.0#parameter-object)
- [Request Body](https://spec.openapis.org/oas/v3.1.0#request-body-object)
- [Path Templating](https://spec.openapis.org/oas/v3.1.0#path-templating)

But yeah, I agree to use an amalgam of the OpenAPI spec 👍

**Comment by JBBianchi** [comment]
@tsurdilo does it make sense for you?

**Comment by JBBianchi** [comment]
Any suggestion to move foward on this ? I think will all agree.

@ricardozanini any additional remarks? @tsurdilo what's your take ?

**Comment by ricardozanini** [comment]
My only remark is to try to use the OpenAPI spec whenever possible, maybe even importing their spec. So we won't reinvent the wheel. Mainly the paths/operation (https://spec.openapis.org/oas/v3.1.0#paths-object) part.

**Comment by cdavernas** [comment]
@ricardozanini I propose not to support `RequestBody`, because it is recommended not to void using it:

> (...) requestBody is permitted but does not have well-defined semantics and SHOULD be avoided if possible.

I would therefore propose that the `operation` value should be, as you proposed, a [Path Templating](https://spec.openapis.org/oas/v3.1.0#path-templating) value.

We then only need two fields: one for the method to use, and another for the [parameters](https://spec.openapis.org/oas/v3.1.0#parameter-object), such as follow:

```yaml
functions:
- name: rest-call
  type: rest
  operation: http://test.com/api/users/{userId}/greet #https://spec.openapis.org/oas/v3.1.0#path-templating
  method: POST
  parameters: #array of https://spec.openapis.org/oas/v3.1.0#parameter-object #could be an external ref or the inline object
    - name: userId
      in: path
      required: true
    - name: body
      in: body
      required: true
      schema: 
        type: object
        properties:
          from:
            type: string
          greeting:
            type: string
        required:
          - from
          - greeting
```

Note that inthis proposal, I moved the `method` and `parameters` properties up to the `functionDef`'s top level. Reason is, IMHO, `metadata` should be used for additional behaviors (external to the spec), not to the spec itself. WDYT?

**Comment by ricardozanini** [comment]
Agreed with `RequestBody`. I also agree that `metadata` is too over. But adding parameters in the def's top-level will carry it over to other function types. Won't bring unalignment with different types?

**Comment by cdavernas** [comment]
We could change the `functionDef` object to be a discriminated type (oneOf). Only with `type=rest` should those properties be included.

Anyways, where would you put those properties?

**Comment by ricardozanini** [comment]
Yes, I agree that's difficult. But it's a necessary evil I think.

Honestly, we should get turn the `type` an optional attribute. The `operation` already can give us the necessary pointers about the operation itself.

And I think `paramDef` and `method` could be reused for others. I can see a custom script function using it, for instance. Let's go!

**Comment by tsurdilo** [comment]
Im personally not a big fan of functiondef-> metadata->post->parameters, think this can be done in a better way, lets discuss. 
Do like the functionRef->arguments as that fits well with what we currently have

**Comment by tsurdilo** [comment]
@cdavernas 
question about:

                     "operation":"https://petstore.swagger.io/pet/{petId}",
                      ...
                     "name":"petId",
                     "in":"path",
                     "description":"ID of pet that needs to be updated",
                     "required":true,
                     "type":"integer",
                     "format":"int64"

is it assumed that this is a POST always? Also don't get the "required" part and the type, if its defined as part of the operation uri then it should be required and imo always string type. What am i missing?

**Comment by cdavernas** [comment]
> Im personally not a big fan of functiondef-> metadata->post->parameters, think this can be done in a better way, lets discuss. Do like the functionRef->arguments as that fits well with what we currently have

No, that is part of the definition of the call, not the args it is called with. In other words, what you see in the def is an OpenApi function definition.

**Comment by cdavernas** [comment]
> @cdavernas question about:
> 
> ```
>                  "operation":"https://petstore.swagger.io/pet/{petId}",
>                   ...
>                  "name":"petId",
>                  "in":"path",
>                  "description":"ID of pet that needs to be updated",
>                  "required":true,
>                  "type":"integer",
>                  "format":"int64"
> ```
> 
> is it assumed that this is a POST always? Also don't get the "required" part and the type, if its defined as part of the operation uri then it should be required and imo always string type. What am i missing?
> 
> my first reaction is that all this can be just something like:
> 
> ```
>  "operation":"METHOD#URI#PARAMS",
>  "type": "rest"
> ```

It cannot be as you suggest, as parameters can be put in headers, path, body, cookies, etc. So you need a most exhaustive description of all parameters. 

As for the `required` property, it's part of the OpenApi function definition. It indicates that the arg MUST be supplied in the function ref

**Comment by tsurdilo** [comment]
ok. this then seems like a ton of effort to please legacy systems. why not start with basic rest capability then improve if there is request? i would be ok with basic spec support that csn be extended via extensions

**Comment by tsurdilo** [comment]
for legacy its not possible to wrap/describe their apis via openapi?

**Comment by cdavernas** [comment]
> ok. this then seems like a ton of effort to please legacy systems. why not start with basic rest capability then improve if there is request? i would be ok with basic spec support that csn be extended via extensions

It's not a lot of efforts imho, it's just a matter of referencing OpenApi

**Comment by tsurdilo** [comment]
ok. im just trying to figure this out cause it seems we are going to start to look like google cloud workflow by constantly having to update this rest spec unless we copy all of openapi over. this prob not best idea??

**Comment by cdavernas** [comment]
> for legacy its not possible to wrap/describe their apis via openapi? just feels like we are copying openapi partially anyways here

It's just not doable in a lot of use cases, where you cannot include local files and do not want to host that doc just yo do a couple of rest calls

**Comment by tsurdilo** [comment]
> > for legacy its not possible to wrap/describe their apis via openapi? just feels like we are copying openapi partially anyways here
> 
> It's just not doable in a lot of use cases, where you cannot include local files and do not want to host that doc just yo do a couple of rest calls

got it. ok then for me this looks like perfect candidate for an extensions. not part of core spec

**Comment by cdavernas** [comment]
Copying just the OpenApi dpec's parameter fragment is imo not a deal breaker, plus we could just decide to not update it, as long as it covers most legacy use cases (which current version actually does)

**Comment by cdavernas** [comment]
> > > for legacy its not possible to wrap/describe their apis via openapi? just feels like we are copying openapi partially anyways here
> > 
> > 
> > It's just not doable in a lot of use cases, where you cannot include local files and do not want to host that doc just yo do a couple of rest calls
> 
> got it. ok then for me this looks like perfect candidate for an extensions. not part of core spec

Mayne. Wdyt @ricardozanini ?

**Comment by tsurdilo** [comment]
each runtime can provide even own extension point for this that would be tailored to rhe rest functionality they can provide. i think for sanity of spec we ahouls so this as this looks very custom and so far we have dodged doing cutom stuff thankfully

**Comment by cdavernas** [comment]
> each runtime can provide even own extension point for this that would be tailored to the rest functionality they can provide. i think for sanity of spec we should do this as this looks very custom and so far we have dodged doing cutom stuff thankfully

Whatever we choose to proceed with, imho we anyways need to rename rest function kind into openapi, which is what it is

**Comment by JBBianchi** [comment]
I agree with the last comment, and same goes for `rpc` that should be renamed as `grpc` imo.

**Comment by ricardozanini** [comment]
> > > > for legacy its not possible to wrap/describe their apis via openapi? just feels like we are copying openapi partially anyways here
> > > 
> > > 
> > > It's just not doable in a lot of use cases, where you cannot include local files and do not want to host that doc just yo do a couple of rest calls
> > 
> > 
> > got it. ok then for me this looks like perfect candidate for an extensions. not part of core spec
> 
> Maybe. Wdyt @ricardozanini ?

I think we can work on an extension, yes. We can do this in four hands and have the project host the extension. So implementations can optionally support and implement it.

I was a little worried about adding more attributes to the functions def, I should say. I think that extensions could be an in-between option to go.

**Comment by ricardozanini** [comment]
About renaming, I agree.

I think it was @tsurdilo that mentioned the other way to transform the `type` into a string. And that could be an optional parameter. Or even incorporate it into the operation itself (e.g. "openapi:myfile.yaml" or "openapi:http://specs.com?id=1", etc.).

Also, limiting the functions in the spec would be a better way to go, IMO. I'd limit the rest to extensions (odata, async, and so on).

**Comment by ricardozanini** [comment]
Guys, as we discussed today, I will open a PR to describe the REST invocation within the operation attribute like `post:/path/to/endpoint/{arg1}?id={arg2}`. If the argument is not there in the state, everything is sent within the request body.

**Comment by tsurdilo** [comment]
with dal think always "the sinpler the better". :)

**Comment by tsurdilo** [comment]
also method should be optional. in not specified should default to post to make it easier on users

**Comment by cdavernas** [comment]
@tsurdilo shouldn't it be GET by default instead, as it usually is?

**Comment by ricardozanini** [comment]
> should be "#" separated like others not ":" please

I think we can later discuss turning the `operation` field into a valid URI (this way we could use the scheme to define the operation type, for instance: `rest:get:/path/{arg1}?param1={arg2}`). But that's a discussion for yet another forum.

**Comment by ricardozanini** [comment]
> also please operation should be "method#expression" only imo. no hard coded urls there. that would allow user to pass whole url if needed as well as call reusable expression function if wanted. it also allows reuse

There are no hard-coded URLs, but a description of the **path**, not the URL.

Let's discuss this in the PR. I've changed to OPERATION#METHOD approach. For example: 

```json
{
  "functions": [{
    "name": "updateUser",
    "operation": "UPDATE:#/users/{id}",
    "type": "http"
  }]
}
```
