### ISSUE TITLE
Errors per actions

### ISSUE THREAD

**Issue by manuelstein** [serverlessworkflow/specification#427]
**What happened**:
Using an array of actions, e.g. [functionA, functionB] can have overlapping errors, e.g. [CustomerNotFoundError].
Currently, I can only define a single error handling, but can't distinguish with which function it has occured.

**Anything else we need to know?**:
It can be resolved with more comprehensive actions (with retry, error handling, etc. per action).
Or if [state nesting](#413) were to be reintroduced, each action could get its own operation state, so a list of actions (e.g. branches in foreach, switch, etc.) would become their own state chart.

**Environment**:
- Specification version used: main branch for 0.7

**Comment by yzhao244** [comment]
@manuelstein Yes, I agree with your issue here :). I raised similar one at here. #398

**Comment by tsurdilo** [comment]
this was added as part of https://github.com/serverlessworkflow/specification/pull/435
it includes "errorRef" as well as optional "errorRefs" array of strings
