### ISSUE TITLE
Inconsistency in types in Workflow function reference

### ISSUE THREAD

**Issue by praveentiru** [serverlessworkflow/specification#436]
**What is the question**:
While reading through the specification, I see inconsistency in Function definition here -> https://github.com/serverlessworkflow/specification/blob/main/specification.md#Function-Definition

The type enum has different values in table, type description and operation description. Operation description lists `rest`, `asyncapi`, `rpc`, `graphql`, `odata` and `expression` as valid types. The other two locations are subsets of this list.

Can someone please clarify what is the valid list here?

**Comment by tsurdilo** [comment]
@praveentiru nice catch - thank you. 
Btw. the "source of truth" should always be the spec schemas, in this case - https://github.com/serverlessworkflow/specification/blob/main/schema/functions.json#L45

Will update the spec doc to fix the error.

**Comment by tsurdilo** [comment]
https://github.com/serverlessworkflow/specification/pull/437
