### ISSUE TITLE
Intellij Plugin similar to VSCode Extension

### ISSUE THREAD

**Issue by suhasark** [serverlessworkflow/specification#455]
**Describe the extension you would like to be added**:
An Intellij Idea IDE plugin with similar functionality as that of VSCode extension 

**What is the main purpose of the extension**:
This plugin/extension would be useful for developers that use Intellij IDEA as the IDE for their development needs. The workflow spec integration within the IDE will make it easier to visualize the workflow in-place instead of switching between VSCode & IJ.

**Comment by tsurdilo** [comment]
Think this would be very useful to have.

**Comment by ricardozanini** [comment]
@suhasark are you able to contribute to such a plugin?

**Comment by suhasark** [comment]
Yes , I can take up this work - Thanks

**Comment by tsurdilo** [comment]
@suhasark nice!!! I would like to help with it if possible

Just as like comparisons, our VSCode plugin https://github.com/serverlessworkflow/vscode-extension really has two main features:
1) Json/Yaml intellisense from the spec json schemas. 
note that on our website (serverlessworkflow.io) we maintain the schemas, for example:
https://serverlessworkflow.io/schemas/0.7/workflow.json for our latest 0.7 release
you can also set https://serverlessworkflow.io/schemas/latest/workflow.json which should give you the "latest" schema from the main branch of the spec repo.
This i think is already possible to do in IntelliJ without a specific plugin, as to set the schema for Json files for intellisense.

2) The diagram generation:
* the diagram generation tool is available here: https://github.com/serverlessworkflow/workflow-diagram-service
* it uses the java sdk https://github.com/serverlessworkflow/sdk-java currently which includes the actual code that generates the the process svg given the workflow json/yaml
* currently the generation service works off the spec release 0.6 still, but as soon as we update the java sdk to 0.7 we will update the diagram-generation-service to use the latest java sdk version and then we can redeploy it.
* the diagram generation service is currently deployed onto OpenShift (and thank you @ricardozanini  for that!!!). We do provide a link to it from our website as well -> https://github.com/serverlessworkflow/serverlessworkflow.github.io/blob/main/_redirects#L6
so to get the workflow diagram you can make a post to serverlessworkflow.io/services/diagrams with data set to the json/yaml of the workflow that's being edited and get back the diagram svg which you can display as part of your plugin.

Hope this help you get started. If you have any questions feel free to ask, also it would be nice if this plugin could be part of the serverless workflow repos. If you are ok with that I can create a new repo here and give you maintainer rights for it so we can all work on that together. WDYT?

**Comment by suhasark** [comment]
Thank you @tsurdilo .

- You are right about the intellisense support with Intellij. The schema file configuration should work
- Separate repo would be useful for this plugin.
- I did have a cursory look at the diagram generation service code. It is written using quarkus , so ideally will be very quick to get the service started. So instead of invoking the hosted service on OpenShift, I was thinking of bringing up the service as part of the plugin within the Intellij environment & calling this from the plugin code. 

This has the following advantages :
1.  Plugin doesn't depend on service availability.
2. Most of the corporates have enterprise firewalls that would stop the plugin from communicating with the service. 

Disadvantage is that it obviously puts a runtime dependency on the service & hence deep coupling with the service.

Please let me know your thoughts.

**Comment by tsurdilo** [comment]
Sounds good. The reason we used Quarkus (could have used SpringBoot or Micronaut, etc as well really) is just so could expose a rest endpoint to the diagram generation.
 In the Intellij plugin you dont have to start that whole service you could just have code that calls the existing public endpoint via some https apis to get the raw svg and display it. 
The advantage of doing that inside the ide (which i did not know was possible) is that user can generate diagram svg even when offline as you also said. Maybe if possible being able to update the java sdk dependency version via configuration in ide plugin can help with users being able to update it without having to wait for a new plugin version?
I havent created intellij plugins before so dont have much insights of whats all possible or not. will read up on it.

**Comment by ricardozanini** [comment]
@suhasark I think you can leverage the diagram generation library directly instead of firing up the service locally, assuming the IntelliJ platform has Java support.

**Comment by suhasark** [comment]
Yes that is possible. 

Intellij plugins can be written in Java or Kotlin (haven't used this before). It puts a compile time dependency on the library which I presume is okay.

**Comment by tsurdilo** [comment]
in that case i think you would just need to have a dependency to the java sdk modules, not the diagram generation project

**Comment by suhasark** [comment]
Thank you @tsurdilo and @ricardozanini .

Please let me know when a new repo is created.

**Comment by tsurdilo** [comment]
@suhasark 
https://github.com/serverlessworkflow/intellij-plugin
let me know who all i should add as members of this repo

thanks

**Comment by tsurdilo** [comment]
@suhasark just fyi, we are moving towards diagram image generation using our typescript sdk and mermaidjs, you can see how @antmendoza switched our website online editor to it: https://github.com/serverlessworkflow/serverlessworkflow.github.io/pull/110
so pretty soon we will be retiring the diagram generation service just need to update the vscode plugin to use our typescript generator
