### ISSUE TITLE
Make iterationParam in ForEach state optional

### ISSUE THREAD

**Issue by tsurdilo** [serverlessworkflow/specification#462]
**What would you like to be added**:
should be optional. if not defined can be auto set by runtime
**Why is this needed**:
in some
cases not neededto be explicitly defined so less markup to write

**Comment by manick02** [comment]
I will start looking at this as well

**Comment by tsurdilo** [comment]
@manick02 thanks!

**Comment by tsurdilo** [comment]
closed by https://github.com/serverlessworkflow/specification/pull/477
