### ISSUE TITLE
Make workflow name param not required

### ISSUE THREAD

**Issue by tsurdilo** [serverlessworkflow/specification#464]
**What would you like to be added**:
Make "name" param on workflow no required
**Why is this needed**:
uniqueness by id. name is not referenced anywhere else. subflow ref is by id so name can be optional

**Comment by manick02** [comment]
@tsurdilo I will take a look at this but am totally new to the specification. Any suggestion on getting started would be helpful

**Comment by tsurdilo** [comment]
For the schema change, look at the required params here as Ricardo mentioned - https://github.com/serverlessworkflow/specification/blob/main/schema/workflow.json#L174 and remove "name" from both arrays there.

There is no need to update any examples.

**Comment by manick02** [comment]
thanks for the help @ricardozanini and @tsurdilo  let me do this and raise a PR.

**Comment by manick02** [comment]
Raised the PR https://github.com/serverlessworkflow/specification/pull/467
