### ISSUE TITLE
Ability to define global retries strategy for all actions

### ISSUE THREAD

**Issue by tsurdilo** [serverlessworkflow/specification#475]
**What would you like to be added**:
Global retries strategy that should be applied to all actions
**Why is this needed**:
Currently each action has to define own

**Comment by manick02** [comment]
I will take a look at this and come back with questions if any.

**Comment by manick02** [comment]
I am assuming the global retry strategy means global retries 
` "autoRetries": {
      "type": "boolean",
      "default": false,
      "description": "If set to true, actions should automatically be retried on unchecked errors. Default is false"
    },
    "retries": {
      "$ref": "retries.json#/retries"
    },`    In my analysis the best way to do this would be to adding **one of**(_globalRetryRef_ as not mandatory property of type String,_globalRetry_ of type #/definitions/retrydef)  at the same level in the specification as quoted above. Please correct me if I am wrong in understanding the feature.

**Comment by tsurdilo** [comment]
@manick02 currently we can define the 

      "retries": []

array as a top-level workflow property. in action definitions we can then specify a "retryRef" which maps to one of those retries definitions. 
The idea is to somehow define one retries definition which is default, meaning that if an action does not specify a retryRef, this default one should be used.

One idea would be as you mentioned to add a globalRetryRef, another idea could be to add 
like a "isDefault" option on retries definition (only one should be set to true), and then it should be used for all action retries for actions that dont explicitly define a retryRef. 
@cdavernas @ricardozanini wdyt?

**Comment by manick02** [comment]
In my opinion, Having IsDefault on retries and restricting to only one set to try will make it harder/impossible to describe in the specification using json schema.

**Comment by tsurdilo** [comment]
agree, some times we cannot just rely on json schema as it does have these types of restrictions. it is ok to define some rules in the spec that go beyond the capabilities of the underlying schema. we can discuss

**Comment by manick02** [comment]
I feel having rules going beyond schema will implementation of Runtime and TCK bit more complex, people can correct me
