### ISSUE TITLE
clarity on exclusive options in specs

### ISSUE THREAD

**Issue by globalflea** [serverlessworkflow/specification#489]
**What would you like to be added**:
In all affected definitions, add details to specify when required fields are exclusive of other fields - i.e. out of n required fields, only one must be defined 

**Why is this needed**:

There are many occurrences where a field in a definition has description that say "Required if *another field* is not defined".  However, it is not state if these fields are exclusive of each others.  As an example, in [Action Definition](https://github.com/serverlessworkflow/specification/blob/v0.7/specification.md#action-definition), there is functionRef, eventRef, subflowRef that says each is required if the others are not defined.  It does not say that **only one** should be defined

**Comment by DoisKoh** [comment]
To add to this, here are some of the occurrences where I've had similar issues:

- Action definition's ```functionRef```, ```eventRef```, and ```subflowRef``` (as already stated above)
- ```transition or end```: many definitions contain either ```transition or end``` listed together as one required parameter, whereas some others have both ```transition``` and ```end``` parameters, usually with ```transition``` being stated as required "if end is not defined". These seem like the same things but being stated in different ways across the document - it would be good to standardize or clarify what the differences are.
- Error(Ref?) definition's ```errorRef``` and ```errorRefs```: based on the specs, it seems quite clear that these would be mutually exclusive and required, but the way they are defined is directly in contrast to the ```transition or end``` parameter listed right below it (as one parameter).

As an aside, [Error Definition](https://github.com/serverlessworkflow/specification/blob/main/specification.md#error-definition) seems to be an 'ErrorRef' definition, and the actual 'Error' definition only exists inside schema/errors.json

**Comment by tsurdilo** [comment]
@globalflea @DoisKoh working on this now :)

**Comment by tsurdilo** [comment]
@globalflea @DoisKoh please review https://github.com/serverlessworkflow/specification/pull/566
