### ISSUE TITLE
Rename DataBasedSwitch to DataBasedSwitchState and EventBasedSwitch to EventBasedSwitchState

### ISSUE THREAD

**Issue by antmendoza** [serverlessworkflow/specification#516]
**What would you like to be added**:

Rename DataBasedSwitch to DataBasedSwitchState and EventBasedSwitch to EventBasedSwitchState

**Why is this needed**:

It is only about naming "convention" as I see it.
Whether I am reading the documentation or coding I can see that the rest of the states end with the word `State`, so I am expecting these states to follow the same convention.

**Comment by tsurdilo** [comment]
@antmendoza there is only a single switch state. In the json schema it can be one or the other type: 
https://github.com/serverlessworkflow/specification/blob/main/schema/workflow.json#L1118

do you think this can be improved?

**Comment by antmendoza** [comment]
yes, I understand that there are two implementations DataBasedSwitch and EventBasedSwitch, in the same way that Eventcondition has Transitioneventcondition and Enddeventcondition.

for example, in the typescript sdk the builder name is type+`Builder`, so when we are creating a workflow the code looks like this:  

```

 .states([
        databasedswitchBuilder()
          .name('CheckApplication')
...
        operationstateBuilder()

..
        xxxxstateBuilder()

```
it is weird to me don't see the word state in the databasedswitchBuilder, again there is nothing wrong, just my point of view.

**Comment by tsurdilo** [comment]
good point, understand now. yeah lets fix this

**Comment by antmendoza** [comment]
I can create a PR

**Comment by tsurdilo** [comment]
thanks!!
