### ISSUE TITLE
onEvent->eventRefs array should have unique values

### ISSUE THREAD

**Issue by tsurdilo** [serverlessworkflow/specification#520]
onEvents-eventRefs array should have only unique values

**Comment by cdavernas** [comment]
@tsurdilo What do you mean with that?

**Comment by tsurdilo** [comment]
"eventRefs": ["HighBodyTemperature", "HighBodyTemperature", "HighBodyTemperature", "HighBloodPressure],


what does that mean? :)

**Comment by cdavernas** [comment]
@tsurdilo Ah! Indeed! 👅
