### ISSUE TITLE
Allow Extensions to be more vendor specific and vendor friendly

### ISSUE THREAD

**Issue by globalflea** [serverlessworkflow/specification#543]
**What would you like to be added**:
Include a "namespace" field to indicate the organisation or category for the extension.  In addition, parameters "extensionId" and "path" to be optional and a json object be defined if these two parameters are missing
**Why is this needed**:
The namespace (or some better name) will allow the vendors to mark certain extensions applicable to their workflow implementation or as a form of classification for the extension - eg. { ... namespace: org.cncf.serverless-workflow ... } or {... namespace: com.mycompany.rules ...}.  Workflow implementation can then determine if the specific class of extension is supported and proceed to deserialize the associated json information.  As a example, 
{
"extensions": [
  {
  "name": "myratelimitextension",
  "namespace": "org.cncf.serverless-workflow"
  "extensionId": "workflow-ratelimiting-extension",
  "path": "file://myextensions/ratelimiting.yml"
  } ]
}

Also, by specifying the "extensionId" and "path",  users will be forced to put their extensions in a separate files.  May be more flexible if "extensionId" and "path" are optional, and where they are not specified, a Json object will be required to specify vendor specific parameters.

**Comment by tsurdilo** [comment]
@globalflea can you please review associated PR https://github.com/serverlessworkflow/specification/pull/562
