### ISSUE TITLE
Constants using illegal jq character

### ISSUE THREAD

**Issue by mswiderski** [serverlessworkflow/specification#550]
**What happened**:
In the spec (https://github.com/serverlessworkflow/specification/blob/main/specification.md#Workflow-Constants) constants mandate to use `$CONST` namespace to access values of the constants. The problem is that `$` is reserved character in jq and the only way to make use of it is to use quotes based access like `"$CONST".NAME.FIRST_NAME`

**What you expected to happen**:
Either it is documented in the spec or (in my opinion it would be better) to change the namespace to something that is not illegal in default expression language (jq)

**How to reproduce it**:
Create any expression that references `$CONST` with jq as expression language 

**Anything else we need to know?**:

**Environment**:
- Specification version used: 0.8

**Comment by cdavernas** [comment]
@mswiderski This has been the subject of many long conversations in the past. Point is,  IMO you should pre-process the jq expression and interpolate all $const or $env or whatever reserved keywords, then pass the interpolation result to jq.

**Comment by mswiderski** [comment]
thanks @cdavernas for very quick reply!

While I agree this is a valid implementation approach I am not sure spec should give examples of expressions that are really not valid. Or at least it should mention that it is known and implemented should resolve it before evaluation since spec mandates the use of `$CONST`

What do you think?

**Comment by cdavernas** [comment]
@mswiderski Hehe, you're welcome. I guess we share the same timezone x)

I completely agree with you, the doc as it is might be misleading to newcomers. 

@tsurdilo Any suggestions?

**Comment by cdavernas** [comment]
@manuelstein This might interest you ;)

**Comment by tsurdilo** [comment]
Don't think this is interpolation issue hehe. Seems to me more of jq expression eval problem?

**Comment by cdavernas** [comment]
@tsurdilo It has to do with reserved keywords that, if I remember correctly, @manuelstein wanted to substitute for more cross-compatible ones.

**Comment by tsurdilo** [comment]
Ok. From what I see, and could be wrong is that CONST is not a namespace but argument name passed to jq that binds $CONST to its value.

**Comment by tsurdilo** [comment]
If you have json:
           {
              "letters": ["a", "b", "c"]
           }

you can with jq:

            jq --arg CONST "d" '.letters |= .+ [$CONST]' test.json
            {
              "letters": [
                "a",
                "b",
                "c",
                "d"
              ]
            }

**Comment by mswiderski** [comment]
yeah, as I understand it it seems that `$` is marker for variables ins `jq`. So it cannot be easily used without bind that variable before using it. So maybe the question is - was this intended? Or do we want to have it like that (consider CONST) to be a variable.

Personally I considered CONST to be namespace and not variable that requires binding explicitly before evaluating expression. Though maybe that was to naive approach ...

**Comment by tsurdilo** [comment]
yes the idea was to use jq variables for that. 
they can be added as args as shown before, but you can always also assign vars in expressions, for example:

      echo '{"hello": "world"}' | jq '{"not": "bar"} as $CONST | . + {"not": $CONST.not}'   
      {
        "hello": "world",
        "not": "bar"
      }

**Comment by mswiderski** [comment]
alright, fair enough. If this is intended to be a variable then it is all good. Might be worth adding a note in the spec as right now it's referred as namespace which might be bit confusing (at least it was for me).

Thanks for all the comments that allowed me to better understand it and continue with implementation @tsurdilo @cdavernas

**Comment by tsurdilo** [comment]
Thanks @mswiderski! Yeah lets use this issue to fix the text in spec. Will work on it

**Comment by tsurdilo** [comment]
@mswiderski pls review https://github.com/serverlessworkflow/specification/pull/563 when can
