### ISSUE TITLE
Example on StateExecTimeout implies States can be retried which is wrong

### ISSUE THREAD

**Issue by globalflea** [serverlessworkflow/specification#551]
From the specs on StateExecTimeout :
"...single property. To show an example, let's say that we set the single property to "PT10S", meaning 10 seconds. A workflow state "X" which defines this timeout when first executed has the max execution timeout set to 10 seconds. If the state execution is then retried, each time it is retried, the individual retry max execution timeout is again 10 seconds." (My italics)

The example implies that State are allowed to be retried (hence, associated retry policy), however, the current spec does not allow retry for states

**Comment by tsurdilo** [comment]
@globalflea please review https://github.com/serverlessworkflow/specification/pull/564
