### ISSUE TITLE
Why not Succeed&Fail State?

### ISSUE THREAD

**Issue by keepupon** [serverlessworkflow/specification#560]
**What would you like to be added**:
New workflow states, succeed and fail

**Why is this needed**:
Just like succeed\fail state in Amazon States Language and stackstorm's engine commands fail&noop, there is a situation to explicitly end the workflow with succeed\fail status (end workflow execution with succeed if some minor error is encountered, for example).  Though we can use the end parameter in serverless workflow, but it will be better to have a standalone node for process visibility and explicitly specify the result.

**Comment by tsurdilo** [comment]
Hi @keepupon, can you show an example where such states would be good to have? I am aware of those states in ASL but outside of testing could never find a real use case to use them. 

I think we could achieve something similar with current end definition by possibly adding a "criteria" (fill in some better name here) property that can be used to denote some domain-specific status? We could also just add metadata prop to end definition for now until we figure this out, if that would unblock you.
