### ISSUE TITLE
Rename eventRef properties to something more meaningful

### ISSUE THREAD

**Issue by tsurdilo** [serverlessworkflow/specification#573]
currently we can do in actions:

       actions:
          - eventRef:
            triggerEventRef: OrderServiceSendEvent
            resultEventRef: OrderServiceResultEvent

this denotes that this action needs to "send" an event X and then wait for event Y that is the invocation result event
we might want to look into renaming "triggerEventRef" and "resultEventRef" to something more meaningful such as maybe
"produceEventRef" "consumeEventRef" or similar, wdyt?

**Comment by antmendoza** [comment]
agree, "produceEventRef" and "consumeEventRef" sounds better to me than trigger/result

**Comment by cdavernas** [comment]
@tsurdilo @antmendoza ...especially now that you can just produce without having to consume. I therefore totally agree.
