### ISSUE TITLE
Add ability to start parallel compensation

### ISSUE THREAD

**Issue by tsurdilo** [serverlessworkflow/specification#586]
**What would you like to be added**:
Typically compensation is done sequentially in reverse order once its explicitly triggered. 
There are use cases however where all compensation activities are not related to some ordering, but 
for sake of performance can be executed in parallel.

Add ability to overwrite the "reverse order" default with ability to define you want compensation to be performed in parallel .
This should be done in the "compensate" definition.

**Why is this needed**:
Ability to solve cases where compensation can be performed in parallel

**Comment by tsurdilo** [comment]
@cdavernas @ricardozanini @mswiderski 
any issues with this?

**Comment by cdavernas** [comment]
@tsurdilo nothing against the idea, which is good imo. I'm just wondering how this could be factored into the spec? As a matter of fact, I'd prefer not to have to choose between sequential or parallel compensation, but would rather prefer having the option to use both on the same pipeline. Being, do example, able to do 3 different compensation in parallel then continue compensation in a sequential fashion. Wdyt?

**Comment by tsurdilo** [comment]
i think that will get pretty complex. as compensation is modeled in wf def and is part of control flow logic i think we can utilize parallel state as a compensation state, and have the effect you are asking for.

this request is just an all-or-nothing setting that would not affect your compensation control flow logic. 
maybe we can start with that and then expand once we have some more complex use cases?

**Comment by mswiderski** [comment]
so will that be on the compensation triggering side or compensation handling side? I mean what part of compensation will actually define how it should work?

**Comment by tsurdilo** [comment]
on trigger, something like

"compensate": true (sequential reversed)

"compensate": { "parallel": true } (parallel)

**Comment by mswiderski** [comment]
hmm wouldn't it cause that same logic could be triggered in different ways? Like one compensation event will be parallel and the other sequential? Just thinking out load here but I a not sure we need anything extra to what you described with parallel state. Personally I would not complicate compensation with that but rather let users model their compensation logic with parallel support explicitly.

**Comment by tsurdilo** [comment]
yeah good point it would also add to possible user errors. do think that top level single time def could work. will do pr and then lets have a look if we want or not. prob not for 0.9 however
