### ISSUE TITLE
Event Based Transitions Example - eventTimeout

### ISSUE THREAD

**Issue by JBBianchi** [serverlessworkflow/specification#604]
**What happened**:
It's not possible to validate the [Event Based Transitions Example](https://github.com/serverlessworkflow/specification/tree/0.8.x/examples#workflow-definition-7) with the schema v0.8: Property `eventTimeout` is not allowed.

**What you expected to happen**:
The example to be valid

**How to reproduce it**:
Take the JSON and validate it, in the [online editor](https://serverlessworkflow.io/editor.html) for instance.

**Comment by tsurdilo** [comment]
Thanks for reporting, yes 

    "eventTimeout": "PT1H",

needs to be defined in timeouts def. Will do
