### ISSUE TITLE
Specify eventDataFilter for each event in eventRef in Event State

### ISSUE THREAD

**Issue by blackthunder0812** [serverlessworkflow/specification#606]
In event state, when we specify multiple events in `eventRef`, especially when `exclusive` set to `false`, how do we specify `eventDataFilter` for each event received?

Example:
```
    ...
    "exclusive": false,
    {
        "onEvents": [{
            "eventRefs": ["HighBodyTemperature", "HighBloodPressure"],
            "eventDataFilter": ... // specify for each event
    ...
```

**Comment by tsurdilo** [comment]
Yeah this is very valid point. We are atm simplifying the event state for 0.9. Just need a little more time to finish it.
