### ISSUE TITLE
Support for output data schema

### ISSUE THREAD

**Issue by EnriqueL8** [serverlessworkflow/specification#611]
**What would you like to be added**:
Currently when defining a new workflow one can specify `dataInputSchema` which we can use to validate the input. Yet a user starting a workflow instance does not know what the output of this workflow is. What is the expected to get when the workflow finishes? This is primarily useful for HTTP requests.

I propose in the same we have `dataInputSchema` to have a `dataOutputSchema` which accepts a JSON schema.

**Why is this needed**:
This will make it easier to document the outputs of workflow for example in an OpenAPI document as the response from the workflow runtime. This makes it especially useful in a microservice architecture where someone can look at the OpenAPI and know what to expect. 

I'm not sure how this fits in with output CloudEvents? Ideally, this output doesn't have to be a CloudEvent.

**Comment by cdavernas** [comment]
@EnriqueL8 This is a good suggestion IMO. However, we should decide if that's for informational purpose only or not.
As a matter of fact, such a schema could be used to verify that the output of a workflow instance matches what's expected just before a successfull completion.

**Comment by EnriqueL8** [comment]
Good point, I hadn't thought of it as a validation step but now that you say it it does feel natural for it to be.

**Comment by fjtirado** [comment]
I vote for same functionality than dataInputSchema, thats it, by default the output is validated againts the output shema if present

**Comment by tsurdilo** [comment]
> Yet a user starting a workflow instance does not know what the output of this workflow is. What is the expected to get when the workflow finishes?

A JSON result (state data output of last workflow state) or a failure (thats dependent on the runtime).

> This is primarily useful for HTTP requests.

If you are exposing workflows from rest endpoint, think you could describe your workflow using OpenAPI which does include response schema. Similarly for event-triggered workflow you can use AsyncApi. 

Trying to figure out what's the purpose of this request as if we add this it can go pretty deep into what all can be added that other frameworks have already.

**Comment by fjtirado** [comment]
@tsurdilo I agree with your concerns, but for these use cases, you just avoid specifying an output schema. I mean, the same than inputSchema, the new field will be optional.

**Comment by cdavernas** [comment]
I'm gonna have a spec binge next week. Should I work on that PR too guys? @tsurdilo @ricardozanini @fjtirado 

I'm a big fan of the idea, personally speaking!
