### ISSUE TITLE
Authentication for REST requests

### ISSUE THREAD

**Issue by EnriqueL8** [serverlessworkflow/specification#612]
**What would you like to be added**:
At the moment there is no notion of authentication within the spec when using a `rest` state. Let's assume we have a function such as 
```
functions:
- name: secureAPI
  operation: "openapi.yaml#createPets"
```

The OpenAPI file might contain a [security scheme](https://swagger.io/docs/specification/authentication/) such as Bearer Token. So how do I describe in my SW that I need to provide a bearer token for this request? One of the solutions might be to pass it in the argument for the `functionRef` but this isn't ideal since you would have to add it every time you want to use that function.

The best solution would be to have a new construct within the spec where you can define the different types of authentication for the functions being used. We can use the existing [auth]( https://github.com/serverlessworkflow/specification/blob/main/specification.md#Auth-Definition)  used to access the resource containing the function invocation information but in this case, it would be authentication information for the function invocation. Not saying we should use the same contract, but a have similar one for function invocation.

**Why is this needed**:
In order to describe the authentication needed a function invocation.

**Comment by cdavernas** [comment]
@EnriqueL8 you can use the top level `auth` property. It currently supports basic, oauth2 and bearer. I'd recommend using a secret-based OAuth2 auth definition so that you do not expose any sensitive info in your flow.

**Comment by EnriqueL8** [comment]
As far as I understood, the `authRef` is used to access the resource containing the function invocation information but not  for authentication information at function invocation

**Comment by cdavernas** [comment]
The `authRef` is used to reference an authentication mechanism declared at top level. The referenced scheme and its properties should be implemented and handled by the runtime when calling the function. 
For example, if you referenced a basic auth definition, the runtime should, when calling an OpenApi function, add the appropriate Authorization header with the specified username and password. 
Does that answer your question or am I missing smtg or failling to understand your use case?

**Comment by cdavernas** [comment]
Well, but if you don't have an intermediate human task or a mechanism of the like, what would be the difference between pre-defining the username/password in an `authDef` or directly within the function?
You don't necessarily have to use a secret btw, you very well could do something like the following:

```
...
auth:
  - name: basic
    scheme: basic
    properties:
    - username: serverlessworkflow
      password: rules
...
```

I would, however, advise against using such a scheme (basic or bearer), and would rather advise using oauth2. As a matter of fact, using the oauth2 scheme, the runtime would have to "produce" the token by contacting the configured `authority`, using the defined `client_id`, `client_secret`, etc, which is obviously way safer.

**Comment by EnriqueL8** [comment]
Yeah, OAuth is what @ricardozanini had suggested to me but instead of the client_id and api keys behind defined in the workflow they are passed through at invocation of the whole workflow.

So when the user wants to start the workflow they pass those credentials and then runtime looking at somewhere in the spec can correlate those to right function. Multiple users can use the same workflow but with their own credentials

**Comment by ricardozanini** [comment]
@cdavernas, the use case is an impersonation pattern for OAuth2, which means that the workflow will impersonate the user to make a call on their behalf. Of course, the SW must have a `client_id` and `secret` defined to generate the given token. 

But the use case here, I believe, is to pass someway the user calling the flow to the OAuth2 process during runtime. It could be a header in the data payload, for instance. Or the spec could somehow describe how to do it per function definition (just thinking aloud).

> In Synapse, if an authRef is defined, we use it, should the OpenApi doc declare an auth mecanism or not.

hmmm, I think there's a misconception here that we need to address in the spec then:

> Auth definitions can be used to define authentication information that should be applied to resources defined in the operation property of [function definitions](https://github.com/serverlessworkflow/specification/blob/main/specification.md#Function-Definition). It is not used as authentication information for the function invocation, but just to access the resource containing the function invocation information.

If I interpreted this paragraph correctly, the `authDef` should not be used to invoke the function but rather the resource (the spec file) instead.

I'm +1000 to change the wording here and reuse the `authDef` for invocation.

**Comment by cdavernas** [comment]
@ricardozanini Ah, I missed that paragraph, which I did not write btw, though I did the auth PR. I always had in mind auth for both declaring doc and function invocation.
+1000 too to fix that misleading paragraph.

**Comment by ricardozanini** [comment]
@cdavernas, I'm sending a PR.

**Comment by fjtirado** [comment]
I would actually create two different structures, one called authInfo, that contains the authorization information (client id and client secret for oauth2 client credential grant type, api key and api prefix for api, user and password for basic, token for bearer..  and authDef, that will contain the  metadata information (token,  refreshURL and grant type for oauth2, paramName and location for apikey). 
Reason is that, when you have the open definition, that metadata information is in the open api file. So authRef can be used for reading any uri (including legacy rest) while for openApi we just need authInfo. 
My point is that we need to diferentiate between resources potentially protected (any external uri read by the flow, where you do not have any clue about the authorization type) and openapi invocations (where you know the authorization type and you need the credentials)

**Comment by cdavernas** [comment]
@fjtirado I disagree. You are only retaining the OpenApi use case, but auth can be applied to GRPC, basic rest, AsyncApi (which has a basic auth definition too), OData and GraphQL. Relying solely on OpenApi spec is IMO gonna make those useless when secured, simply because those protocols do not describe (or describe poorly) auth.
Relying in on single auth is imho both practical, intuitive and easy to implement, as shown in previous links.

**Comment by fjtirado** [comment]
I forgot to mention than for gRPC or other function types different than OpenAPi, we will need an authDef. So, Im basically proposing to have four additional optional fields, which are specified as needed. If you want to protect both the spec file (gRPC, OpenApi...) and the function calls done thorugh this spec file, you will have as most 4 fields specified (three for OpenAPI)
Another option is to merge authCredentials and authDef in just one structure with two fields (one for credentials and one for def, def is only needed if the resource does not contain that info), so in the function definition rather than four you will have two fields, one to protect the resource and another to protect the function call.

**Comment by ricardozanini** [comment]
@cdavernas @tsurdilo what do you think about @fjtirado proposal? I will open a PR with the suggested changes, let me know if you have any comments.

**Comment by fjtirado** [comment]
Just an example of what I have in mind (using one structure for credentials and def)

Lets say we are calling an openapi service which definition file can be retrieved using basic authorizaton and which definition define oauth2 to actually invoke the service

we will have 
```
{
   "functions": [
      {
         "name": "HelloWorldFunction",
         "operation": "https://secure.resources.com/myapi.json#helloWorld",
         "resourceAuthRef": "My Basic Auth"  
         "invocationAuthRef": "My Oauth Auth"
      }
   ]
}

```
and then
{
```
auth: [
  {
    "name": "My Basic Auth",
     "schema" : "basic",
     "credentials": {
        "username" : "javierito",
        "password" : "$SECRET.javierito.password"
      } 
  }, 
  { 
   "name": "My Oauth Auth"
   "scheme": "Oauth2",
   "credentials": {
      "clientId" : "javierito",
      "clientSecret" : "$SECRET.javierito.secret}"
   }
]
}

```
The rest of information for performing the oath2 call will be on the open api definition. Now lets assume that we are not using openAPI and we want to include all the required info for oauth2. Then, we will use something like this for the oauth2 definition
```
  { 
   "name": "My Oauth Auth"
   "scheme": "Oauth2",
   "credentials": {
      "clientId" : "javierito",
      "clientSecret" : "$SECRET.javierito.secret}"
   }, 
   "properties": {
     "grantType": "clientCredentials",
      "tokenURL": "https:www.givemethetoken.com/token",
      "refreshURL": "https:www.givemethetoken.com/refresh",
  }
}
```

**Comment by fjtirado** [comment]
@ricardozanini  we are also also differentiating between properties and credentials, inside the auth definition (but yes, this is essentially the same as having all properties in the same level and optionally filling them)

**Comment by cdavernas** [comment]
@fjtirado Thanks, I think it's a great idea, overall. 
I have, however, the following comments:
- I would not split the `properties` into two properties, as I think it's not required and would certainly be confusing to new users of the spec.
- I would propose to find a way to allow user specifying the `authRef` only once, if the same is used for both resource access and function invocation 
Here's what I'd propose (though I don't like the terminology I'm using):

**Configuring a function to use the same auth definition for both resource access and function invocation:**
```
...
functions:
  - name: MySecuredFunction
    operation: https://secure.resources.com/myapi.json#helloWorld
    auth: My ApiKey Auth 
...
```

**Configuring a function to use two different auth definition for resource access and function invocation:**
```
...
functions:
  - name: MySecuredFunction
    operation: https://secure.resources.com/myapi.json#helloWorld
    auth:
      resource: My ApiKey Auth
      invocation: My Basic Auth
...
```

This way, we would allow for "simple" use of the `authRef` (similar to what's already in the spec) AND allow further granularity, too (which was a great suggestion btw, many thanks), all that by using the same mechanism we use elsewhere with union types.

@ricardozanini @fjtirado WDYT?

**Comment by fjtirado** [comment]
@cdavernas 
I liked the approach, but I think `auth: My ApiKey Auth `should only apply to function call (yes, I know, thats the opposite of what the spec is saying now, but it is probably the most typical case)
Having credentials separated from properties clearly differentiate between fixed information (king of strucuture) and the credentials, but I think is a minor detail in any case (having all of them together and specying only the needed ones will also work )

**Comment by cdavernas** [comment]
> I liked the approach, but I think auth: My ApiKey Auth should only apply to function call (yes, I know, thats the opposite of what the spec is saying now, but it is probably the most typical case)

It's only my opinion, but I think setting the `auth` value using a string should apply to both resource and function invocation, considering that the most reliable usage of OpenAPI is code-first generation, in which case the documentation is hosted by the app it describes (which, btw, was the original purpose of the Swagger spec)

> Having credentials separated from properties clearly differentiate between fixed information (structural) and the credentials (the proof of that is that the openapi spec include the former but cannot include the latter), but I think is a minor detail in any case (having all of them together and specying only the needed ones will also work )

Yes, I see what you mean, and it does make sense. I'll, however, stand my ground on this one, as I really believe "splitting" the properties would loose in readability without really adding further value, as most of the `properties` fields are marked as optional anyways.

**Comment by fjtirado** [comment]
The problem with auth applying to both is that Im not sure if is very frequent to use the same auth scheme for the resource and the call. If that is the case, lets go for it.

**Comment by ricardozanini** [comment]
I think it's impossible to know. My only concern is this:

```yaml
functions:
  - name: MySecuredFunction1
     operation: https://secure.resources.com/myapi.json#helloWorld
     auth: My ApiKey Auth 
- name: MySecuredFunction2
     operation: https://secure.resources.com/myapi.json#holaMundo
     auth: My ApiKey Auth 
```

Same resource, how do I describe it? Twice? If only one is defined, should I consider the one with or without?

Maybe the original proposal was to define a auth definition for the function invocation, not the resource. The resource should be unique.

In this case, if we proceed the way we settle here (`auth: { invocation: {}, resource: {} }` then I will describe in the PR that if the resource has the auth defined in one of the functions, that one is assumed to be the credential.

In this example:

```yaml
functions:
  - name: MySecuredFunction1
     operation: https://secure.resources.com/myapi.json#helloWorld
     auth: My ApiKey Auth 
- name: MySecuredFunction2
     operation: https://secure.resources.com/myapi.json#holaMundo
```

We would use `auth` to fetch the resource, so users won't need to replicate.
