### ISSUE TITLE
Missing/Broken links for extension context attributes

### ISSUE THREAD

**Issue by VicNgu** [serverlessworkflow/specification#616]
**What happened**:
The hyperlink for [extension context attributes](https://github.com/cloudevents/spec/blob/master/spec.md#extension-context-attributes) is broken throughout the spec.

**What you expected to happen**:
The hyperlink to work. Looks like there is no section for these details in the spec.

**How to reproduce it**:
Click on any of the hyperlinks for extension context attributes.

**Anything else we need to know?**:

**Environment**:
- Specification version used: master

**Comment by ricardozanini** [comment]
Hi @VicNgu! Thanks for reporting it, I'll send a PR to fix it.
