### ISSUE TITLE
Add support for a new 'process' action type

### ISSUE THREAD

**Issue by cdavernas** [serverlessworkflow/specification#619]
**What would you like to be added**:

Add support for a 'process' action type, which would allow users to actually run simple shell/bash commands

**Why is this needed**:

In some case, users might have no other choice than to run bash commands, for example to install a self-signed certificate in a worker's isolated computing unit.

**Comment by cdavernas** [comment]
@tsurdilo @ricardozanini What do you guys think? If I've your green light, I'll work ASAP on a PR to address that ;)

**Comment by cdavernas** [comment]
> What are the security implications? Adding a process action can result in a security breach. Some users might not want to have it enabled by default. I can see implementations not implementing or having to add an option to disable process actions. This way, we might lose the interoperability "no, process action we don't work with." I'm okay with this assumption, btw. We need to clarify.

+100, I totally agree. Security implications are however minimal in a Docker context, for example.

> This action sounds like an infrastructure requirement. Are we going down this path?

No, absolutely not! If I ever do, please shoot me out of my misery 😆 I just had a couple of real-life scenario where such this would have saved the team from developing a dedicated FaaS.

But yeah, it's probably a very bad idea nonetheless, mainly for cross-platform concerns. As a matter of fact, most commands are different in Windows, Linux and Mac. Hell, even escaping rules are different in Windows if you run in Powershell or in classic Cmd.

Just wanted to put it out there, in case we can find a way to do that in a proper, clean and sustainable way.

**Comment by cdavernas** [comment]
> Would it make sense to use functions type "custom" to run scripts?

@tsurdilo WDYT?

**Comment by tsurdilo** [comment]
@cdavernas i kinda like what Argo is doing: https://github.com/argoproj/argo-workflows/blob/master/examples/scripts-bash.yaml#L29

**Comment by cdavernas** [comment]
Yeah looks nice!

Are you proposing to use the image part of it, too?

**Comment by tsurdilo** [comment]
@cdavernas the question is, where is this command going to run?

**Comment by cdavernas** [comment]
Well, imo should run in something containerized, so we can address both the security and cross compatibility concerns at once. In that case, 'process' could be understood as 'container' execution result. I'm not sure, though, if that's not putting too much weight on implementations, as well as make the spec a bit too technical.
However, I defintly can imagine something of the like:
```
name: MyProcess
kind: process
operation: ubuntu:latest:wget
```

And call it like:

```
...
functionRef:
  refName: MyProcess
  arguments:
    - "http://test.com"
    - "--no-cache"
```
