### ISSUE TITLE
Specification and Using multiple Data filters section: Error in Workflow definition ?

### ISSUE THREAD

**Issue by radtriste** [serverlessworkflow/specification#630]
https://github.com/serverlessworkflow/specification/blob/v0.8/specification.md#using-multiple-data-filters (same on `main`)

Event action is calling greeint function:
```json
                "actions":[
                    {
                        "functionRef": {
                            "refName": "greetingFunction",
                            "arguments": {
                                "greeting": "${ .spanish } ",
                                "customerName": "${ .customerInfo.name } "
                            }
                        },
                        "actionDataFilter": {
                            "fromStateData": "${ .hello }",
                            "results": "${ .greetingMessageResult }",
                            "toStateData": "${ .finalCustomerGreeting }"
                        }
                    }
                ]
```

We have the action data filter using the `"fromStateData": "${ .hello }",`
which means the data for the action is
```json
{
    "english": "Hello",
    "spanish": "Hola",
    "german": "Hallo",
    "russian": "Здравствуйте"
}
```

How is that possible that we use the `customerInfo` data into the function arguments, whereas, AFAIU, it is not in the current data for the action ?

**Comment by ricardozanini** [comment]
Yeah, it sounds like a bug. In the writing, it is stated:

> (3) Event state performs its actions: Before the first action is executed, its actionDataFilter is invoked. Its "fromStateData" **expression filters the current state data to select from its data that should be available to action arguments**. In this example it selects the "hello" property from the current state data. At this point the action is executed. We assume that for this example "greetingFunction" returns:

And the action arguments are expecting `customerInfo` property. So it should be corrected as:

```json
{
   "actions":[
      {
         "functionRef":{
            "refName":"greetingFunction",
            "arguments":{
               "greeting":"${ .hello.spanish } ",
               "customerName":"${ .customerInfo.name } "
            }
         },
         "actionDataFilter":{
            "fromStateData":"${ { hello, customerInfo } }",
            "results":"${ .greetingMessageResult }",
            "toStateData":"${ .finalCustomerGreeting }"
         }
      }
   ]
}
```

_additional brackets added for GH formmating_

**Comment by radtriste** [comment]
I will provide a PR then for the fix

I saw also some other small issues in the doc that I will correct in the same PR, if you are ok with that>

**Comment by tsurdilo** [comment]
@radtriste @ricardozanini 


        "fromStateData":"${ { hello, customer } }", 

would be the same this as the state data after the state filter is applied so think just remove fromStateData in the action filter
is better in this case


Also 
       "customerName": "${ .customerInfo.name } " 

should be 

        ${ .customer.name }

**Comment by ricardozanini** [comment]
@tsurdilo 
> think just remove fromStateData in the action filter is better in this case

Not necessarily. I think the filter example is fine, and the `fromStateData` action filter segregates the language from the `hello` attribute. It's not the most complex and smart example but it will do. :)
