### ISSUE TITLE
Reinstate weekly calls

### ISSUE THREAD

**Issue by cdavernas** [serverlessworkflow/specification#642]
**What would you like to be added**:

Weekly calls to be reinstated, on a platform we control (as opposed to the SW's Zoom, which's access apparently got lost)

**Why is this needed**:

- Discuss upcoming features
- Vote on conflictual PRs
- Vote on budget assignment
- Promote implementations
- ...

**Comment by ricardozanini** [comment]
+1

**Comment by antmendoza** [comment]
+1

Honestly, I feel more disconnected/less motivated since we don't do the calls. It is okay for me whether it is every week, every two weeks, or whatever.

**Comment by tsurdilo** [comment]
Not sure why we need an issue for this but ok :) yes +100.

**Comment by cdavernas** [comment]
@tsurdilo I opened an issue to keep track of required changes (on the website and all), fearing that we'd let it slide otherwise ;)

**Comment by tsurdilo** [comment]
> @tsurdilo I opened an issue to keep track of required changes (on the website and all), fearing that we'd let it slide/would forget about it, otherwise ;)

I get the hint :) Working on it now

**Comment by tsurdilo** [comment]
https://github.com/serverlessworkflow/specification#weekly-meetings
