### ISSUE TITLE
Update governance model

### ISSUE THREAD

**Issue by cdavernas** [serverlessworkflow/specification#644]
**What would you like to be added**:

Update/define the governance model by defining some kind of community, vote-based decision making on breaking changes/issues deemed "controversial".

Create a new tag, such as `Up to vote` and/or `Controversial` to mark issues requiring debate/vote on a meeting call

**Why is this needed**:

Ensure that breaking and/or controversial changes are backed up by both implementers and users, and by the community in a wider sense.

Vote sessions, if any is required, could be held in a monthly fashion to ensure that voters can make a documented decision.

Vote privilege should IMO only be given to some kind of privileged users, such as contributor - or even maintainer.

**Comment by tsurdilo** [comment]
Great idea and def something that we need to come up with and try to enforce.
