### ISSUE TITLE
Enforce action name

### ISSUE THREAD

**Issue by JBBianchi** [serverlessworkflow/specification#685]
**What would you like to be added**:
The name of actions to be `required`.

**Why is this needed**:
The name is a human, comprehensible way of working. When reviewing the activities of a workflow, knowing that "Action[2]" was a success doesn't really speak to the user. It requires to have the definition under the eyes, count the actions to find the one we are speaking about. Having it named will improve readability and maintainability of workflows and their activities.

**Comment by ricardozanini** [comment]
+1

**Comment by tsurdilo** [comment]
This is done i believe as part of the error handling updates pr.

**Comment by JBBianchi** [comment]
This also applies to other item types like `branch`.

A name should be unique within the scope of its parent but not the whole workflow.

**Comment by ricardozanini** [comment]
As agreed in the meeting call, within the same state, we should guarantee action uniqueness

**Comment by tsurdilo** [comment]
Yes branch names are also going to be enforced as part of error handling updates.

**Comment by jaliyaudagedara** [comment]
Seems this suggested hasn't moved to the specification yet. Should we update the spec?
