### ISSUE TITLE
Use more ubiquitous duration expressions

### ISSUE THREAD

**Issue by cdavernas** [serverlessworkflow/specification#687]
**What would you like to be added**:

Use more ubiquitous duration expressions, such as `00:05:00` instead of `PT5M`. 

I know that the suggested format does not support concepts such as days, weeks, months, etc., but in most case it won't come of use and damage the readability of a flow.

In order to keep features in place, and still allow for greater readability, I woul suggest defining a top-level 'durationFormat' property, to allow the user to select the duration ISO she wants to use.

**Why is this needed**:

Makes the spec more ubiquitous and human readable, using a well-known format rather than a more obscure ISO, which can be rebuking and/or counter intuitive to some people.

**Comment by tsurdilo** [comment]
Do we want to define our own time and duration format? 
ISO 8601 makes sense and we use it all over the place and it has existing libs that use it. 
I think for a runtime it's perfectly ok to support whatever format they want and then translate it to ISO 8601 or whatever they use, think thats totally fair.

**Comment by cdavernas** [comment]
@tsurdilo No, we do not want to use our own format. I don't recall the ISO, but `{HH}:{MM}:{SS}` is perfectly standard.

It's not a runtime issue, as the duration must be parsed either case. IMO, it's a spec ubiquitousness issue.

**Comment by JBBianchi** [comment]
`{HH}:{MM}:{SS}` doesn't work for everything though. Let's say you want a duration of 1 month, the said duration in hours varies from a month to another.

**Comment by cdavernas** [comment]
> I know that the suggested format does not support concepts such as days, weeks, months, etc., but in most case it won't come of use and damage the readability of a flow.

@JBBianchi  As said ;)

**Comment by ricardozanini** [comment]
We can still support ISO 8601 and have an attribute indicating if the definition is `duration` or `time`. We keep it as it is for `duration` (the default).

For `time`, we then use again ISO 8601 form: `Thh:mm:ss.sss`, so `T00:10:00.000` for ten minutes. 

@cdavernas wdyt?

**Comment by cdavernas** [comment]
@ricardozanini sounds good to me!

**Comment by ricardozanini** [comment]
I'd stay away from "proprietary formats" to avoid lock in.

**Comment by fjtirado** [comment]
@ricardozanini 
 we should not use time for duration either. I understand the need for compromise solutions sometimes, but what Charles is requesting here is to be able to use something different than the standard because he does not like it (a valid point, there are definitely users that do not like it)
I agree with @tsurdilo, we should not define a new standard and I agree with you, we should not allow custom formats. The backdoor here is to allow propietary extensions for duration is the standard is not good for your business.
