### ISSUE TITLE
Revise definition and use of runBefore (workflow exec timeout)

### ISSUE THREAD

**Issue by tsurdilo** [serverlessworkflow/specification#699]
Currently runBefore is only available for workflow exec timeout: https://github.com/serverlessworkflow/specification/blob/main/schema/timeouts.json#L62

We need to look into extending this to other timeouts.

**Comment by cdavernas** [comment]
@tsurdilo I believe the timeouts and retries need a complete overhaul, which will be initiated by your error handling PR. So I would wait to push that change.

**Comment by tsurdilo** [comment]
ok
