### ISSUE TITLE
Rename `dataInputSchema`

### ISSUE THREAD

**Issue by cdavernas** [serverlessworkflow/specification#705]
**What would you like to be added**:

Rename the workflow top-level `dataInputSchema` to `inputDataSchema`.

**Why is this needed**:

For ubiquity purpose, especially considering the addition of an output data schema.

IMHO , the current nomenclature is at best inaccurate.

**Comment by fjtirado** [comment]
@cdavernas I agree, incoporating this to https://github.com/serverlessworkflow/specification/pull/696
