### ISSUE TITLE
Define specific rules when merging action output by default

### ISSUE THREAD

**Issue by cdavernas** [serverlessworkflow/specification#712]
**What would you like to be added**:

Define specific rules when merging action output by default

**Why is this needed**:

So far, the spec mandates that the output of an action without `toState` data filter should be merged back 'as is' into the state data. 
Problem is, if the output of said action is not an object, merging it into state data will effectilvely fault the whole workflow: all evaluations will fail.

Image for instance an action that returns, say, an array or, why not, an integer. Your state was the following beforehand:

```json
{
  "someName": "someValue"
}
```

After the action, the state data would be:

```json
[
 1,
 2,
 3
]
```

Or why not something like:

```json
125
```

Which would result in all further actions to fail. Consider, for example, a next action with a `fromState` data filter => BOOM.

What I propose is that the action output be merged back "as-is" ONLY if/when it's an object. If it's an array or a value type (string, bool, int, ...), it should instead be merged back into a 'actionOuput' property, for example. The name of that property could be based on the name of the action, such as `myActionOutput`.

WDYT?

**Comment by fjtirado** [comment]
@cdavernas, what we did in Kogito for those cases is to merge the non object json node with a "response" name.

**Comment by cdavernas** [comment]
> what we did in Kogito for those cases is to merge the non object json node with a "response" name.

Common sense indeed, but it would imho be nice to specify that in the spec so that users don't "discover" inconsistencies amongst runtimes.

**Comment by ricardozanini** [comment]
Oh sure thing, I agree entirely with you. I remember we brought this to discussion, but didn't go further, so we did it by ourselves
