### ISSUE TITLE
In all examples, the "version" field does not have a ","

### ISSUE THREAD

**Issue by whuanle** [serverlessworkflow/specification#714]
URL:
[https://github.com/serverlessworkflow/specification/blob/main/examples/README.md#Hello-World-Example](https://github.com/serverlessworkflow/specification/blob/main/examples/README.md#Hello-World-Example)

![image](https://user-images.githubusercontent.com/2189761/202656729-5dd5eed0-8cff-4385-91e0-f2e6633398e2.png)
![image](https://user-images.githubusercontent.com/2189761/202657066-6a919eec-23b4-42c6-aec0-1fddf5de9a5b.png)

**Comment by cdavernas** [comment]
@tsurdilo Related to #324. Any update on this? If not, @ricardozanini and I could do the work, as adveritised in related issue ;)

**Comment by lsytj0413** [comment]
@whuanle The 'version' field in all examples have add ",", PTAL
