### ISSUE TITLE
Support: add faas function type

### ISSUE THREAD

**Issue by walterlife** [serverlessworkflow/specification#735]
**What would you like to be added**:
function type adds **faas** type, which is used to orchestrate faas services, such as [OpenFunction](https://github.com/OpenFunction/OpenFunction),or other cloud faas service

**Why is this needed**:
now funtion type already support rest, asyncapi, rpc, graphql, odata, expression, or custom，although these types can meet most scenarios, in the cloud-native FaaS scenario, these types cannot currently support FaaS services well. So I think it is necessary to add a new type: faas, which is used to support FaaS service orchestration.

**Comment by cdavernas** [comment]
@walterlife you can support Faas out of the box with rest/openapi function (that's what I do with OpenFaas for instance). More than that and we land on a minefield, as Faas is not a standard or a specific tech, but rather a high level concept that would anyways use one of the tech we support to contact the gateway.

What you are asking for is basically a quality of life wrapper around the API that one FaaS provider might supply. As said, the easiest way to do so is with OpenApi, should the gateway supply it or not. If for some reason that's out of your way, then you probably should look into creating an extension 😉

**Comment by walterlife** [comment]
> 
@cdavernas Thanks for answering.I understand that the current faas does not have a more universal standard.
ok, i use rest type to achieve my purpose
