### ISSUE TITLE
Request to add Workflow Runtime implementation

### ISSUE THREAD

**Issue by walterlife** [serverlessworkflow/specification#736]
Request to add the Workflow Runtime implementation: [serverlessworkflow-go](https://github.com/apache/incubator-eventmesh/tree/master/eventmesh-workflow-go). After EventMesh is successfully hatched in Apache, it will have a separate code warehouse under Apache.
Below is the architecture.
<img width="800" alt="WeChatWorkScreenshot_9d48be6f-47e7-4ce6-bd82-1b21ebc9efde" src="https://user-images.githubusercontent.com/8448852/206418644-8c644445-a5d5-4ef4-bf28-d223e2d3c196.png">

**Comment by ricardozanini** [comment]
Nice! I see you are using the Go SDK. We are on the verge of upgrading to the 0.8 spec version. What are your plans? We can add it to the website. Or are you talking about donating it to the Serverless Workflow organization, like we have [Synapse](https://github.com/serverlessworkflow/synapse)?

**Comment by walterlife** [comment]
> 
Thanks reply.
yeah,recently, I also noticed that SW released spec 8.0.
Parsing dsl here depends on [go sdk](https://github.com/serverlessworkflow/sdk-go).In the near future, I also plan to participate in the contribution of go-sdk and upgrade the spec to v0.8.
Because the current project is contributed to ASF, it may not be shared with the Serverless Workflow organization again. Currently I am also integrating EDA/FaaS/BaaS, and plan to use it as a serverless workflow industry standard solution. So I also request that it can be added to the serverless workflow website as a runtime solution.

**Comment by tsurdilo** [comment]
For adding to website please provide:

Logo (png if possible)
Title text (like name of project/company/etc)
Short text description

**Comment by tsurdilo** [comment]
Oh you mean to the "Execute your production workflows" section?

For that the project has to be part of the SW org (github repo), we can discuss details if you need of what that means.

**Comment by tsurdilo** [comment]
@ricardozanini can we go through these two sections on website in one of our meets? Maybe we can come up with a better approach to this where we can showcase all runtimes for SW somehow better.

**Comment by walterlife** [comment]
> 
Thanks reply.
Yes, add to  "Execute your production workflows" section.
But now the project has been contributed to ASF, it may not be shared with the Serverless Workflow organization again.
I wonder if there is any other better way to present this project？

**Comment by walterlife** [comment]
> @ricardozanini can we go through these two sections on website in one of our meets? Maybe we can come up with a better approach to this where we can showcase all runtimes for SW somehow better.

@tsurdilo  Thanks reply.
Yes, add to "Execute your production workflows" section.
But now the project has been contributed to ASF, it may not be shared with the Serverless Workflow organization again.
I wonder if there is any other better way to present this project？

**Comment by walterlife** [comment]
> Oh you mean to the "Execute your production workflows" section?
> 
> For that currently the runtime project has to be part of the SW org (github repo), we can discuss details if you need of what that means.
> 
> We could change/update that section to add cncf sister projects that use SW, that would be really cool.

@tsurdilo  Thanks reply.
Yes, add to "Execute your production workflows" section.
But now the project has been contributed to ASF, it may not be shared with the Serverless Workflow organization again.
I wonder if there is any other better way to present this project？

**Comment by tsurdilo** [comment]
Definitely want to add it (would be nice if your project had a readme tho hehe). Lets either revise the section "Execute your production workflows" or add a new one, will discuss w/ team and let you know..either way please give 
a proper logo, project name and description so can cut/paste it when we add.

**Comment by walterlife** [comment]
> Definitely want to add it (would be nice if your project had a readme tho hehe). Lets either revise the section "Execute your production workflows" or add a new one, will discuss w/ team and let you know..either way please give a project logo, project name and description so can cut/paste it when we add.

Thanks. I add readme file in project.
Ok, I will to prepare these materials, and synchronize them to this issue.

**Comment by qqeasonchen** [comment]
It would be really nice to see the EventMesh-workflow-go runtime join the SW.

**Comment by ricardozanini** [comment]
> @ricardozanini can we go through these two sections on website in one of our meets? Maybe we can come up with a better approach to this where we can showcase all runtimes for SW somehow better.

Added to our meeting notes for next Thu: https://docs.google.com/document/d/1SY9_n7vcRabmP8xELBP8lmwz14AscPzJq6AL86dbcCY/edit#

**Comment by walterlife** [comment]
> > Definitely want to add it (would be nice if your project had a readme tho hehe). Lets either revise the section "Execute your production workflows" or add a new one, will discuss w/ team and let you know..either way please give a project logo, project name and description so can cut/paste it when we add.
> 
> Thanks. I add readme file in project. Ok, I will to prepare these materials, and synchronize them to this issue.

@tsurdilo synchronize these materials.Thanks.
Project logo: http://rmpvudky7.bkt.clouddn.com/EM.png
Project name: EventMesh Workflow
Project Description: EventMesh Workflow is a cloud vendor-independent, cloud-native-oriented Serverless Workflow Runtime based on Serverless Workflow specification, and provides durability, reliability, scalability, and observability capabilities.

**Comment by qqeasonchen** [comment]
I am very happy to see that the implementation of EventMesh-workflow can be added to the community, looking forward to the progress of the update.

**Comment by ricardozanini** [comment]
@walterlife @qqeasonchen I think you can open a PR and update/add a card in the website front page: https://github.com/serverlessworkflow/serverlessworkflow.github.io

**Comment by tsurdilo** [comment]
I can do the pr today np,
@walterlife  http://rmpvudky7.bkt.clouddn.com/EM.png gives 404, can you provide updated link to logo?

Also @ricardozanini I will add this to the "Execute your production workflows" section, do you want to add Kogito there too so we can just do both with same update? If you do pls provide same info as walter did :)

**Comment by walterlife** [comment]
@tsurdilo sorry, I reuploaded the picture: https://sw-1251681900.cos.ap-singapore.myqcloud.com/em.png

**Comment by walterlife** [comment]
> @walterlife @qqeasonchen I think you can open a PR and update/add a card in the website front page: https://github.com/serverlessworkflow/serverlessworkflow.github.io

@ricardozanini Okey, this issue: https://github.com/serverlessworkflow/serverlessworkflow.github.io/issues/182

**Comment by ricardozanini** [comment]
> I can do the pr today np, @walterlife http://rmpvudky7.bkt.clouddn.com/EM.png gives 404, can you provide updated link to logo?
> 
> Also @ricardozanini I will add this to the "Execute your production workflows" section, do you want to add Kogito there too so we can just do both with same update? If you do pls provide same info as walter did :)

oh please! that would be great!!

**Comment by ricardozanini** [comment]
@tsurdilo here you go:

Project logo: 
Project name: Kogito Serverless Workflow
Project Description: Kogito Serverless Workflow is a tool for building cloud-native workflow applications. You can use Kogito to do the services and events orchestration and choreography. Currently, with Kogito, you can integrate with services and events in your architecture using CloudEvents, synchronous and asynchronous REST invocations, and many other industry-standard components.

If we were to add a link, please use this one: https://kiegroup.github.io/kogito-docs/serverlessworkflow/latest/index.html

**Comment by tsurdilo** [comment]
Thanks @ricardozanini @walterlife working on it

**Comment by tsurdilo** [comment]
@walterlife @ricardozanini done, check website. thanks.

**Comment by tsurdilo** [comment]
will close this issue, please feel to reopen it if there is anything else that needs to be done.

**Comment by qqeasonchen** [comment]
@tsurdilo hi, EventMesh had just graduated from the Apache incubator, and the parent project home had been transferred to https://github.com/apache/eventmesh, and the workflow runtime home had been transferred to https://github.com/apache/eventmesh-workflow,  I'm wondering if you can help update the two links in the https://serverlessworkflow.io/, thank you.
