### ISSUE TITLE
Request to establish a ServerlessWorkflow community in China

### ISSUE THREAD

**Issue by walterlife** [serverlessworkflow/specification#737]
Hello friends, I am very happy to participate in the community communication of ServerlessWorkflow. I am also the author of [ServerlessWorkflow Golang Runtime](https://github.com/apache/incubator-eventmesh/tree/master/eventmesh-workflow-go). 
Now I want to establish a ServerlessWorkflow community in China. The main tasks include: co-construction of ServerlessWorkflow Spec, Spec Document translation, evangelism promotion, cooperation with various cloud vendors in China, and promotion of ServerlessWorkflow products in Chinese technology companies. At present, I am also working in Tencent China, and I am promoting the unification of Serverless Workflow Spec in the company. The ultimate goal is to realize the Serverless Workflow products that serve the Tencent’s internal business.
Here I would like to ask, if I start to do this, what processes are required in the early stage, and whether this is in line with the vision and goals of the community, or whether the community supports this approach. I personally hope to contribute to the promotion and evolution of Serverless Workflow.Looking forward to hearing from the community, thank you.

**Comment by tsurdilo** [comment]
> I am very happy to participate in the community communication of ServerlessWorkflow

We are happy you would like to participate. Welcome!

>  want to establish a ServerlessWorkflow community in China

This would be awesome imo! Let us know how we can help. 

> working in Tencent China, and I am promoting the unification of Serverless Workflow Spec in the company

Can you give us more info? Are there any parts of Tencent that are currently using SW? What do you see the major use case(s) at Tencent for it? 

> The ultimate goal is to realize the Serverless Workflow products that serve the Tencent’s internal business.

Looking forward to learning more about it.

> what processes are required in the early stage, and whether this is in line with the vision and goals of the community, or whether the community supports this approach

100%, we always welcome anyone who wants to be part of and promote our projects. The process is pretty easy, start contributing to our projects as you can and your time allows. Be proactive and let us know how we can help you get started. 
Be yourself and have fun. 

> I personally hope to contribute to the promotion and evolution of Serverless Workflow.

Thank you! Again, let us know how we can help with this.

**Comment by walterlife** [comment]
Thanks reply.
>want to establish a ServerlessWorkflow community in China.

The current plan is to set up a separate website in China, such as serverlessworkflow.cn. Later, with the promotion and popularization of serverlessworkflow in China, I also have the ideas to promote the establishment of serverlessworkflow summit, which is mainly to connect communities or technology companies to share best practice experiences around serverlessworkflow. Of course, I am also very happy to interact with the ServerlessWorkflow community.

>Can you give us more info? Are there any parts of Tencent that are currently using SW? What do you see the major use case(s) at Tencent for it?

Currently, in the field of content automation processing (various content processing components, such as machine audit, manual audit, quality judgment, data field processing and etc.), it provides Lego-Style component orchestration capabilities. It is currently in the stage of architecture upgrade, and is already in the stage of integrating Serverless Workflow.

>The ultimate goal is to realize the Serverless Workflow products that serve the Tencent’s internal business.

At present, there are many workflow engines in Tencent, and I believe that other companies should be similar to this situation. Most of them are business self-developed, state machine-oriented DAG engines. I want to be able to promote a unified standard within the company in the field of serverless workflow, using Serverless Workflow Sepc.

> 100%, we always welcome anyone who wants to be part of and promote our projects. The process is pretty easy, start contributing to our projects as you can and your time allows. Be proactive and let us know how we can help you get started.
Be yourself and have fun.

I am very grateful for the support of the community. After that, I will also actively participate in regular community meetings, and I will keep pace with you in time if there is progress.

**Comment by ricardozanini** [comment]
@walterlife about this:

> The current plan is to set up a separate website in China, such as serverlessworkflow.cn, or add a docs-cn sub-warehouse under the github repo. Later, with the promotion and popularization of serverlessworkflow in China, I also have the ideas to promote the establishment of serverlessworkflow summit, which is mainly to connect communities or technology companies to share best practice experiences around serverlessworkflow. Of course, I am also very happy to interact with the ServerlessWorkflow community.

I believe creating a separate website is counter-intuitive. As discussed in the Slack channel, let's try to have everything in the same domain/website. We can easily redirect users based on their location and have the option to change the language as Kubernetes docs do.

**Comment by jinrongluo** [comment]
@walterlife @tsurdilo @ricardozanini @yzhao244 
Hi friends, my name is Alex Luo. I am working in Huawei Canada. Yuri @yzhao244  and myself are very happy to participate in the Serverless Workflow community.  We have a similar goal to promote Serverless Workflow Spec in the company internally, and in the OpenSource Developer community in China. Currently at Huawei there are two products are using Serverless Workflow Specification.

1. Huawei Cloud ROMA Connect, https://www.huaweicloud.com/intl/en-us/product/roma.html.
 Huawei Cloud ROMA Connect is the Enterprise grade integration platform as a Service (EiPaaS). It has public cloud, private cloud and hybrid cloud offerings.  As a full-stack application & data integration platform, It provides data, API, message, and device integration to allow interconnection between cloud and on-premises applications, helping enterprises achieve digital transformation.

ROMA Connect offers ROMA Business Flow Service (https://www.huaweicloud.com/intl/en-us/product/roma/romaflow.html). ROMA BFS is a low-code /no-code integration flow service, and we are using Serverless Workflow Specification to define the Business Flow. I am contributing to ROMA Connect.

2.  Huawei Cloud FunctionGraph, https://www.huaweicloud.com/intl/en-us/product/functiongraph.html
FunctionGraph allows you to run your code without provisioning or managing servers, while ensuring high availability and scalability. Serverless Workflow Specification is also used in Huawei Cloud Function Flow Service (FaaS) as well. It uses SW model to define the Function orchestration flow and execute it in the Function Flow engine. Yuri @yzhao244 contributed to Function Flow Service.

**Comment by tsurdilo** [comment]
hi @jinrongluo thanks for sharing and welcome!!! looking forward to working with you

**Comment by tsurdilo** [comment]
@jinrongluo lets work in adding thede projects on project website

**Comment by jinrongluo** [comment]
@tsurdilo Thanks for your warm welcome.

We are thinking to contribute to the extension of the Spec. More detail will come.

**Comment by walterlife** [comment]
> @walterlife about this:
> 
> > The current plan is to set up a separate website in China, such as serverlessworkflow.cn, or add a docs-cn sub-warehouse under the github repo. Later, with the promotion and popularization of serverlessworkflow in China, I also have the ideas to promote the establishment of serverlessworkflow summit, which is mainly to connect communities or technology companies to share best practice experiences around serverlessworkflow. Of course, I am also very happy to interact with the ServerlessWorkflow community.
> 
> I believe creating a separate website is counter-intuitive. As discussed in the Slack channel, let's try to have everything in the same domain/website. We can easily redirect users based on their location and have the option to change the language as Kubernetes docs do.

hello, @ricardozanini Is there any development work here that I can assist with, or can I start Chinese document translation on the existing basis?

**Comment by ricardozanini** [comment]
What are you planning to translate? The website or the specification? About the website, I believe you can start it based on what we have. So we can figure out a strategy using the current tech stack we use in the serverlessworkflow.io repo.

About the spec, I'm migrating it to Antora so that we can translate to Chinese later.

**Comment by lsytj0413** [comment]
@walterlife  I would like to join ServerlessWorkflow community in China. If there is any help wanted, I can help as much as i can.

**Comment by tsurdilo** [comment]
thanks @lsytj0413 !!

**Comment by walterlife** [comment]
> @walterlife I would like to join ServerlessWorkflow community in China. If there is any help wanted, I can help as much as i can.
@lsytj0413 thanks! Is it convenient to add WeChat? My wechat: 13136178586
