### ISSUE TITLE
is it true that state transition can be triggered in two ways, one is to use transition keyword, another is to use event?

### ISSUE THREAD

**Issue by elim19** [serverlessworkflow/specification#743]
for example, here is the state definition:
![image](https://user-images.githubusercontent.com/123845880/215297712-16d15383-237d-43d0-8ee8-738d2968f225.png)

I have two questions:
1. is it true that there are two ways to transition to state b
1.1 state a is complete
1.2 event OrderCreatedEvent is triggered
either one will trigger state b to happen?

2. is it true that if state b is triggered by events, it will trigger function b2Event, if not, it will trigger b1Event?

**Comment by lsytj0413** [comment]
ACK 2:

- You don't define `type` of state b, if it's `event`, it can't have action property.

**Comment by lsytj0413** [comment]
ACK 1:

- no, if the state b is not the starting state, when state a is completed and transition to state b, we must wait the Event is triggered before action is execute.

**Comment by elim19** [comment]
> ACK 2:
> 
> * You don't define `type` of state b, if it's `event`, it can't have action property.

Is this understanding correct?
if state type is event, it can only be triggered by certain event
it state type is operation, it can only be triggered by state transition from another state

**Comment by tsurdilo** [comment]
curently a non-starting event state is blocking meaning when reached is awaiting one of the onevents defs to start executing associate actions. so the transition is taken from a to b as soon as a completes

**Comment by lsytj0413** [comment]
> > ACK 2:
> > 
> > * You don't define `type` of state b, if it's `event`, it can't have action property.
> 
> Is this understanding correct? if state type is event, it can only be triggered by certain event it state type is operation, it can only be triggered by state transition from another state

I think so.

**Comment by elim19** [comment]
> > > ACK 2:
> > > 
> > > * You don't define `type` of state b, if it's `event`, it can't have action property.
> > 
> > 
> > Is this understanding correct? if state type is event, it can only be triggered by certain event it state type is operation, it can only be triggered by state transition from another state
> 
> I think so.

@lsytj0413 ，can serverlessworkflow define transiting to a state if certain event is triggered no matter what current state is? for example,
if OrderCreatedEvent is triggered, workflow will transit to state b no matter what current state is?
![image](https://user-images.githubusercontent.com/123845880/215314262-a9c2461e-e0a5-4c69-b99d-2e95efe179d5.png)

**Comment by lsytj0413** [comment]
> @lsytj0413 ，can serverlessworkflow define transiting to a state if certain event is triggered no matter what current state is?
> 
> for example, current this workflow define need to reach state c first, then it will check if OrderCreatedEvent is triggered and transit to b, but if current state is not c, it won't work. Is it possible if OrderCreatedEvent is triggered, workflow will transit to state b no matter what current state is?
> 
> ![image](https://user-images.githubusercontent.com/123845880/215314379-53350f6a-d737-43e5-b5db-b38556bcb9c7.png)

As far as i known, there is no way to cancel a state executing (expect timeout), so serverlessworkflow can't archieve your scenario. (It's like an Intermediate Event in bpmn)
