### ISSUE TITLE
Can event be reused if it is not triggered the first time?

### ISSUE THREAD

**Issue by elim19** [serverlessworkflow/specification#744]
Consider this situation:

1. state A depends on two events(eventA and eventB), exclusive is false, and timeout period is 10 minutes. if both events are triggered, state A will transit to state B; if timeout, it will transit to state C
2. only eventA is triggered in 10 minutes, so the state A transit to state C
3. after several state transition, workflow transit to state A again, this time only eventB is triggered, will state A transit to state B? because in step2 eventA is already triggered

**Comment by elim19** [comment]
also for state which has event state type, if event is triggered 3 times, is this mean there will be 3 state instance running?

**Comment by tsurdilo** [comment]
think of event state as for example workflow.await(duration, condition). The condition defines as the onEvents structure and the exclusive prop as you mentioned. 

for 3 no, each "entry" into a state is a new state invocation. so the condition mentioned before is applied again

**Comment by tsurdilo** [comment]
@elim19 just fyi we have a discussion board too https://github.com/serverlessworkflow/specification/discussions
that might be better suited for question than opening issues (might be easier)

**Comment by elim19** [comment]
> for state which has event state type, if event is triggered 3 times, is this mean there will be 3 state instance running?

@tsurdilo , are you saying, the event must be triggered after workflow.await(duration, condition) is called, so if it is triggered before you call workflow.await(duration, condition), it will be ignored?
