### ISSUE TITLE
Add `actionMode` property to Parallel State and ForEach State

### ISSUE THREAD

**Issue by lsytj0413** [serverlessworkflow/specification#753]
**What would you like to be added**:

There's multi state can perform multi actions, and `Event`、`Operation` state also have `actionMode` property to pecifies how actions are to be performed (in sequence or in parallel)，but `Parallel`、`ForEach` state doesn't have.

**Why is this needed**:

- To make all state with multi actions having the same behavior
- Define how action is performed in `Parallel` & `ForEach` state

**Comment by fjtirado** [comment]
In my opinion, all actions on a parallel state branch or in a foreach statement should be sequential.
