### ISSUE TITLE
Is the specification so complex that it can be used in practice

### ISSUE THREAD

**Issue by golimix** [serverlessworkflow/specification#783]
the DSL is so complex , can be used in practice ? 这个DSL如此复杂, 能够用于生产实践吗?

**Comment by cdavernas** [comment]
What do you mean? Of course it can, and that's why there's already a plethora of implementations of it.

Sorry if I'm not catching your drift ;)

**Comment by ricardozanini** [comment]
Hi @golimix like @cdavernas commented, why do you think the DSL is complex? Can you point an example and where can we improve?
