### ISSUE TITLE
Events and event correlation question

### ISSUE THREAD

**Issue by brampurnot** [serverlessworkflow/specification#791]
Hi all!

I have a use-case and I'm struggling to find the correct way of doing this. We have a cron job that runs every 15 minutes which calls an API. That API executes some logic which can take a bit of time; it's very difficult to predict how long it takes before it has all the data but it can be between 5 minutes and 5 hours. Therefore we are using events to signal back that the data was received and that the rest of the workflow can continue. 

Chances are that we have multiple workflow instances running at this point in time. So I was thinking of using correlations to make sure the correct workflow instance is consuming the correct event. However I'm not sure how this can be done. It would actually mean that we need some kind of unique identifier (like the workflow instance ID for example) or some kind of UUID that gets generated in the workflow instance. This unique ID can then be defined as the correlation ID and which can then be passed on to the function so that it can be passed on when generating the event. 

I would expect that this is a basic use-case but I'm struggling a bit to understand how this can be achieved. 

Any help is appreciated!
Bram

**Comment by cdavernas** [comment]
Your function could return something like an UUID that you'd store in the state data and compare it with the correlation key used in the callback event. 

At this point in time, however, the spec does not allow setting a correlation key name, meaning you can only have one active correlation per workflow per correlation attribute name. This is a known issue, and I'm confident the (very simple) fix will make it to 0.9.

**Comment by brampurnot** [comment]
Addressing this in the synapse GitHub.
