### ISSUE TITLE
Bug in `functions` schema

### ISSUE THREAD

**Issue by jscheid** [serverlessworkflow/specification#794]
**What seems off**:

The `functions` key isn't nested inside `properties` here:
https://github.com/serverlessworkflow/specification/blob/8a7152e0931a5f41a1c4abaf344d7ce1fd92410f/schema/functions.json#L6

I think it is meant to be?

**What you expected to be**:

Nested inside `properties`.

**Anything else we need to know?**:

It might be a good idea to run all the schemas through a strict validator. ajv's strict mode would fit the bill, it reports:

```
Error: strict mode: unknown keyword: "functions" 
```

**Environment**:

- Specification version used:

**Comment by ricardozanini** [comment]
Which spec version? Main? Yes, we are missing a CI to validate our schemas indeed.

**Comment by jscheid** [comment]
Just follow my link and click "blame" to see it was introduced in bb5fa9f2f5a1ca2508faa776bd89ef68cd886dbd. No idea which spec versions that covers, 0.6+?

**Comment by ricardozanini** [comment]
The `functions` is a parent object defined in a separate file. So when validating, one should use all the files including in https://github.com/serverlessworkflow/specification/tree/main/schema directory. I have a few SDKs using these files to validate and generate workflows, and no one has reported a bug like this before. Do you mind giving more details of how are you validating on your end? 

I'll try to do something on my side too using AJV.

**Comment by jscheid** [comment]
Ah, I see, if you use `workflow.json` then the reference resolves correctly.

I got confused because `functions.json` contains top-level keys `type` and `required` so it _looks_ like you could use it as a standalone schema, but these settings aren't actually ever used since the top level isn't referenced anywhere, correct? Instead `functions.json` is a "library" useful only when referenced from `workflow.json`.

You could consider removing these top-level keys, and perhaps adding a comment, to make it more clear that the file isn't meant to be used standalone.

**Comment by ricardozanini** [comment]
But then I would lose the `functions.json` independent file.

**Comment by ricardozanini** [comment]
@jscheid @cdavernas I made the `oneOf` work:

```json
"oneOf": [
    {
      "type": "string",
      "format": "uri",
      "description": "URI to a resource containing function definitions (json or yaml)"
    },
    {
      "type": "array",
      "description": "Workflow function definitions",
      "items": {
        "type": "object",
        "$ref": "#/definitions/function"
      },
      "additionalItems": false,
      "minItems": 1
    }
  ]
```

Just had to remove `type`.

**Comment by ricardozanini** [comment]
> But arent't you moving the `oneOf` in the validation instead then ? Because if I understand, the function definition would be either `{ "ref": "an-uri" }` or `{ "name": "my-func", "type": "rest", ... }`

In this case, we can add all the properties and require everything (like `name`, `type`, `operation`) only when `ref` is null.
