### ISSUE TITLE
Typo in use case figures

### ISSUE THREAD

**Issue by iakkus** [serverlessworkflow/specification#81]
**What happened**:
[Use case figures](https://github.com/serverlessworkflow/specification/tree/master/usecases) have a typo on the "Serverless Workflow" box, but it reads "Severless Workflow".

**Comment by iakkus** [comment]
Actually, it reads "Severless Worflow".

**Comment by tsurdilo** [comment]
@iakkus :) good catch. I will update the images soon. Thanks!

**Comment by tsurdilo** [comment]
Pull Request: https://github.com/serverlessworkflow/specification/pull/93

**Comment by tsurdilo** [comment]
@iakkus PR in place, please review it when you can. Thanks.

**Comment by tsurdilo** [comment]
Solved by commit https://github.com/serverlessworkflow/specification/commit/0f9fba4b4b3afe59abd2a70b9e1a9c68092852a2

Thanks @iakkus for reporting@
