### ISSUE TITLE
ProducedEvent.contextAttributes defined as object type but example definition shows that it is array type

### ISSUE THREAD

**Issue by Maslino** [serverlessworkflow/specification#811]
**What seems off**:

ProducedEvent.contextAttributes is defined as object type but example definition shows that it is an array of objects.

```json
{
    "eventRef": "provisioning-complete-event",
    "data": "${ .provisionedOrders }",
    "contextAttributes": [{
         "buyerId": "${ .buyerId }"
     }]
 }
```

**What you expected to be**:

The ProducedEvent.contextAttributes example should be corrected.

**Anything else we need to know?**:

**Environment**:

- Specification version used:

**Comment by cdavernas** [comment]
Thanks for reporting, there's a bug in the definition example as they should indeed be of object/map type.
Care to submit a PR to fix it?
