### ISSUE TITLE
Event data should accepts json object with expressions not just a single expression as string. 

### ISSUE THREAD

**Issue by fjtirado** [serverlessworkflow/specification#815]
Field `data` on [EventRef](https://github.com/serverlessworkflow/specification/blob/main/specification.md#eventref-definition) definition is of type string. However arguments of a [FunctionRef](https://github.com/serverlessworkflow/specification/blob/main/specification.md#functionref-definition) are of type object. 

**What would you like to be added**:
Field data should  behave as fields arguments. 

**Why is this needed**:
In order to be able to build a json object to be passed as data of the cloud event, as it is currently done for function arguments.

**Comment by ricardozanini** [comment]
Closing since this is already implemented in the current main branch. SDKs might release alpha versions targeting the upcoming 0.9 version.
