### ISSUE TITLE
EventTimeout supporting expression

### ISSUE THREAD

**Issue by fjtirado** [serverlessworkflow/specification#816]
**What would you like to be added**:
Currently, [timeouts](https://github.com/serverlessworkflow/specification/blob/main/specification.md#workflow-timeout-definition) are required to be ISO 8601 string. That makes sense but it would be nice to add the possibility of that ISO 8601 string to be the result of evaluating an expression. 

**Why is this needed**:
This will allow defining a recurrent timeout as a conts in the header of the file and then refer to it later on in several places. Hence, if the timeout has to change later, you can change it in just one place. 

See example

```
  "constants": {"duration":"PT5S"}

  "timeouts": {
        "eventTimeout": "$CONST.duration"
      }

```

**Comment by ricardozanini** [comment]
The PR should cover:

- Update the spec schema
- Update the docs
