### ISSUE TITLE
Examples README samples are broken

### ISSUE THREAD

**Issue by JBBianchi** [serverlessworkflow/specification#822]
**What seems off**:
The include of example sample seems to break the readme layout:
![image](https://github.com/serverlessworkflow/specification/assets/72747835/bebf2f73-7093-446f-bb24-68218f42c028)

**What you expected to be**:
The layout to be nice and clean.

**Comment by ricardozanini** [comment]
Hey @JBBianchi thanks for reporting it! Are you willing to fix it? :D

**Comment by JBBianchi** [comment]
Yes, it's just a line return that needs to be added.

**Comment by RamiKassouf** [comment]
It's broken again

**Comment by ricardozanini** [comment]
@JBBianchi is this fixed?

**Comment by JBBianchi** [comment]
It looks like the workflow to hydrate the readme is broken: https://github.com/serverlessworkflow/specification/actions/workflows/examples-readme-hydration.yml

Either because the BOT_PAT secret is missing or the bot doesn't have the rights one the repository.

**Comment by ricardozanini** [comment]
That's weird, I'll take a look later

**Comment by JBBianchi** [comment]
I think it would be a good thing to fix the bot config. Even if the examples are dropped with the next version, we'll still need a functioning bot in the future.

**Comment by cdavernas** [comment]
@ricardozanini Can you please address that?

**Comment by ricardozanini** [comment]
Closing this since we don't have this pipeline nor the examples README anymore.

**Comment by cdavernas** [comment]
I think this must be fixed on 0.9.0

**Comment by ricardozanini** [comment]
@cdavernas I'll reopen but it might stale. I'd keep it close and if there's momentum we'll notice since the CI will fail, then we can fix it. I'm investing my time on 1.0.0 atm. Feel free to reopen.

**Comment by cdavernas** [comment]
> I'm investing my time on 1.0.0 atm
Not shit! 😆 Me too 🎉
