### ISSUE TITLE
Timeout expiration behaviour, transition to an specific state, not the regular one

### ISSUE THREAD

**Issue by fjtirado** [serverlessworkflow/specification#825]
**What would you like to be added**:

All the event timeouts configured for callback, event and switch states, should allow the definition of a timeout that, instead of moving to the next state defined in the transition property (or the equivalent property, depending on the state), can transition to a configurable state and then return the execution to the original state.

The reason for this change request is to allow executing validation tasks while another task is in pending state.

Additionally, these trigger-based states can be executed more than once, until a configured limit is reached (maybe similar to the retry definition, but not evaluated after failures of services)

**Why is this needed**:

**Comment by cdavernas** [comment]
@fjtirado this is addressed by the error refactor PR. Timeout should produce an error, which can they be handled as you see fit.

**Comment by fjtirado** [comment]
It is addressed by https://github.com/serverlessworkflow/specification/issues/770
