### ISSUE TITLE
Provide .NET SDK

### ISSUE THREAD

**Issue by tomkerkhove** [serverlessworkflow/specification#83]
**What would you like to be added**:
Provide .NET SDK

**Why is this needed**:
To support customers building .NET applications.

**Comment by ricardozanini** [comment]
Hi @tomkerkhove! Do you have plans to work on it?

**Comment by tomkerkhove** [comment]
Building the SDK you mean or? If so, unfortunately I don't have the bandwidth for that.

**Comment by tsurdilo** [comment]
Will close this issue for now. It can be re-opened when we start working on this sdk.
