### ISSUE TITLE
Upcoming new DSL for 1.0.0-alpha1 version release

### ISSUE THREAD

**Issue by ricardozanini** [serverlessworkflow/specification#843]
**What would you like to be added**:
This umbrella issue is for discussions and links to previous issues, summarizing the upcoming new DSL.

- **Version 0.9.0** will be released as an evolution of 0.8 and will be maintained as long as the community shows interest. It will serve as a transitional version for runtimes already stable on 0.8. Adding new features to it will not be a priority, and it will be treated as a legacy version.

- **Version 1.0.0-alpha1** is a comprehensive refactor of the entire specification, retaining only standards integration. Its core will undergo significant changes, and the interpretation of nodes will be substantially altered. Many open issues will be addressed in this new version, allowing us to close the existing ones, remove them from the 0.9 milestone, and link them here. This will provide stakeholders with a clear understanding of the roadmap.

**Comment by cdavernas** [comment]
Closed by #847
