### ISSUE TITLE
Move the DSL to dedicated repository

### ISSUE THREAD

**Issue by cdavernas** [serverlessworkflow/specification#845]
**What would you like to be added**:

Move the DSL to a dedicated repository, to avoid confusion, or rename the `specification` one to `dsl`.

For now, the repository `specification` contains a `specification.md` that defines the DSL. It's just a matter of semantics, but maybe we should take the opportunity of 1.0.0 to do so.

**Why is this needed**:

Lack of clarity. Not great for SEO. 

Even path to specification file is confusing IMHO: https://github.com/serverlessworkflow/specification/specification.md.

**Comment by ricardozanini** [comment]
I think we followed the same semantics from CloudEvents Spec: https://github.com/cloudevents/spec

But seeing there repo now, I can see that's pretty different. Maybe we can use it as a reference? 

DSL in a new repo would be more difficult to send PRs changing the spec, no? We would have to send two PRs. Maybe using folders to split the files?

Also a `spec.md` huge file is hard to maintain. I think we should consider breaking it into sections to ease contributions.

**Comment by cdavernas** [comment]
I'm closing, as it's irrelevant for now.

Let's reopen it in the future, once we've addressed more pressing issues, if we feel it really/still matters.

> Also a spec.md huge file is hard to maintain. I think we should consider breaking it into sections to ease contributions.

I followed your suggestion and have split the docs into [dsl](dsl.md) and [dsl reference](dsl-reference.md). It breathes imo a little bit more.
