### ISSUE TITLE
Translate examples from JSON to YAML in 1.0.0-alpha1 DSL

### ISSUE THREAD

**Issue by cdavernas** [serverlessworkflow/specification#850]
**What would you like to be added**:

Translate/optimize pre `1.0.0-alpha1` examples.

Examples, like everything else, should be written in YAML, for the sake of readability and to leverage at best the new syntax.

**Why is this needed**:

Provide, in addition to `/ctk/features` a good variety of examples.

**Comment by ricardozanini** [comment]
Depends on:

- #861

**Comment by ricardozanini** [comment]
@cdavernas I think we can slowly add examples to the `examples` dir as we progress fixing schema bugs like in #863.

I'll hold this for now once we create a tool to migrate from version 0.8 to 1.0.0. So we can use the former examples to test the tooling. :)

**Comment by cdavernas** [comment]
@ricardozanini @JBBianchi @fjtirado the examples we have introduced should fo the trick, right? If so, can I close as completed?

**Comment by fjtirado** [comment]
@cdavernas In my opinion, we can close that one and add additional examples as we see fit. 
Maybe, we can add one that use more complex jq expressions, but I understand thats also controversial, becuase JQ is just one expression language and this is not a jq tutorial

**Comment by ricardozanini** [comment]
We can close this. As soon as I start working on the migration tool, I can revisit the old samples in the 0.9 branch.
