### ISSUE TITLE
Add Print Task

### ISSUE THREAD

**Issue by fjtirado** [serverlessworkflow/specification#856]
**What would you like to be added**:
A print task to be able to print message to the standard output

Using literal
```
do: 
   debug: Hello world!

```      
Using expression (typically jq interpolation, since we should NOT support interpolation by ouselves)
```
do: 
   debug:  ${Hello \(.input.name)!}
```

Its up to every implementation decide how debug should be disabled (there is the possibility of adding the option of enable/disable at the header of the definition file, but I think this should be dynamic and enforcing that is kind of static)

**Why is this needed**:
It might be useful for debugging. Users are using [custom sysout ](https://sonataflow.org/serverlessworkflow/latest/core/custom-functions-support.html#con-func-sysout) extensively, so I guess it will be good to include in the spec some way to print messages to console

**Comment by cdavernas** [comment]
@fjtirado Should we leave this issue opened, as we closed #859 ?
