### ISSUE TITLE
Remove Shell Process

### ISSUE THREAD

**Issue by cdavernas** [serverlessworkflow/specification#860]
**What would you like to be added**:

Remove the shell process, as suggested by @fjtirado in https://github.com/serverlessworkflow/specification/pull/859.

**Why is this needed**:

- Is not portable if not restricted to a specific OS
- There is, by definition, an isolation concern when using commands, even though runtimes can easily choose to solve them by... using containers, for example.
- The exact same functionality can be achieved in a fully isolated and portable way using containers, making it, at best, redundant.

**Comment by fjtirado** [comment]
I believe we all  agree our goal should be to achieve full portability of spec files across implementors. 
Thats why I think we need to replace shell, which have security, portability and performance implications, by a set of simple task which are universal and might be used to compose another more complex task.
Then, implementors can implement these single task the way they see fit (using shell, an operating system call or using a portable language library)
We might start with a small set and then add new ones base on user feedback.
One lame example. 
"dump": has as arguments a message (which is a literal string or an expr), a destination: stdout, stderr or file path (expressed as an array to avoid SO dependant operation) and that just append the stirng to stdout, stderr or file path. 
Im noy saying that is really needed (thats a different discussion) but an example of iteaction with the underlying file system we might want to support in the spec.

**Comment by fjtirado** [comment]
Maybe the conclusion is that these set of task size is zero ;) and we can just remove shell ;). But probably we need a "primitive" to create, read from, write to and delete files (logging is just a special case of write)

**Comment by ricardozanini** [comment]
@cdavernas Maybe moving this one to extensions instead of removing it?

**Comment by cdavernas** [comment]
> @cdavernas Maybe moving this one to extensions instead of removing it?

Unhappilly, I don't think that it would address the feature set nor the issues at hand, which can by the way be extended to `scripts`.

Removing `shell` and/or `script` is IMHO a bad idea, as we would drastically reduce the ability for less technical authors to painlessly achieve a lot of use cases.

I am therefore taking the freedom to close this issue in favor of #998, and will eventually reopen it depending on the outcome of said issue.
