### ISSUE TITLE
flowDirective schema does not support task names

### ISSUE THREAD

**Issue by matthias-pichler** [serverlessworkflow/specification#862]
**What seems off**:

the schema for the flow directive is:

```json
{
  "flowDirective": {
    "type": "string",
    "enum": [
      "continue",
      "exit",
      "end"
    ],
    "default": "continue"
  }
}
```

while the docs mention that one can also specify the name of a task: https://github.com/serverlessworkflow/specification/blob/v1.0.0-alpha1/dsl.md#task-flow

and since `flowDirective` is also used in the schema for the `switch` task the examples would not pass validation: https://github.com/serverlessworkflow/specification/blob/v1.0.0-alpha1/dsl-reference.md#switch

**What you expected to be**:

```json
{
  "flowDirective": {
    "anyOf": [
      {
        "type": "string",
        "enum": [
          "continue",
          "exit",
          "end"
        ],
        "default": "continue"
      },
      {
        "type": "string"
      }
    ]
  }
}
```

**Anything else we need to know?**:

**Environment**:

- Specification version used: 1.0.0-alpha1

**Comment by ricardozanini** [comment]
Thanks @matthias-pichler-warrify! I'll take a look at it today.
