### ISSUE TITLE
[PROPOSAL] - Protect main branch against CI failures

### ISSUE THREAD

**Issue by ricardozanini** [serverlessworkflow/specification#881]
**What would you like to be added**:
Recently, was merged a PR where the CI had a failure. It was easy to miss because the green "merge" button was there and every reviewer had approved. 

To prevent this from happening again, I'll turn on the branch rule protection for this repository. Please see the attached screenshot for the details.

![Screenshot 2024-06-03 at 12 24 25](https://github.com/serverlessworkflow/specification/assets/1538000/6835850e-b6df-4574-b030-813e92b551ca)

**Comment by ricardozanini** [comment]
@cdavernas I need your +1

**Comment by cdavernas** [comment]
@ricardozanini you have it!

**Comment by ricardozanini** [comment]
Done.
