### ISSUE TITLE
Task to transition to a specific task

### ISSUE THREAD

**Issue by brampurnot** [serverlessworkflow/specification#913]
Hi all,

we have been experimenting in our project with this standard starting from v0.0.8. We just discovered the changes in 1.0.0 and seem to be able to migrate over to it without any big problems. It even makes our project easier. 

Nevertheless there is one gap. In some of our workflows, we have the possibility to transition back to a previous task. This so-called go-to task, allows us to execute a specific task and based on the outcome, we can either move forward or re-execute a previous task (or tasks) again. 

Is this something that you guys can help us understanding of how something like this could be achieved here or whether or not this might be an enhancement for future releases? 

In the previous versions (0.0.8), we could easily do this via the transition property. 

Thanks,
Bram

**Comment by cdavernas** [comment]
Hello @brampurnot! Happy to hear you are liking the new version! 
You can easily do what you are looking for, using:
`then: previousTaskName`. 
It actually is kind of the same than the previous version's transition keyword. 
To transition to a specific task based on previous task's output, you'd typically use a switch task.
I hope this answers your question and addresses your use case!

**Comment by brampurnot** [comment]
Great! I probably missed that then. Thanks for the quick response. 

Bram

**Comment by cdavernas** [comment]
@brampurnot With pleasure! Glad to help! Don't hesitate to ask if you have any other question!
