### ISSUE TITLE
Specify context of task.if expression

### ISSUE THREAD

**Issue by matthias-pichler-warrify** [serverlessworkflow/specification#921]
**What would you like to be added**:

I think we should specify what the runtime context (i.e. value of `.` in jq) is of the [`if` expression of a task](https://github.com/serverlessworkflow/specification/blob/main/dsl-reference.md#properties-1). I understand it to be the task input. 

**Why is this needed**:

This removes ambiguity for both implementors and authors.

**Comment by cdavernas** [comment]
> I understand it to be the task input.

Exactly, that's my understanding too!
