### ISSUE TITLE
$ref vs additionalProperties.$ref

### ISSUE THREAD

**Issue by JBBianchi** [serverlessworkflow/specification#933]
In the JSON Schema, I noticed two different ways of inheriting from a schema:

**$ref**
[properties/input](https://github.com/serverlessworkflow/specification/blob/main/schema/workflow.yaml#L37)
```yaml
  input:
    $ref: '#/$defs/input'
    description: Configures the workflow's input.
```

**additionalProperties.$ref**
[properties/use/properties/authentications](https://github.com/serverlessworkflow/specification/blob/main/schema/workflow.yaml#L43)
```yaml
      authentications:
        type: object
        additionalProperties:
          $ref: '#/$defs/authenticationPolicy'
        description: The workflow's reusable authentication policies.
```

Does it imply a different behavior ? If not, shouldn't we rely on the "shorter one" ($ref) ?

**Comment by cdavernas** [comment]
> Does it imply a different behavior ? If not, shouldn't we rely on the "shorter one" ($ref) ?

Yes, it theoretically does: the first sample defines that the object should match exactly the referenced schema, whereas the second defines that the object can have additional properties that, if set, must match the referenced schema.

In practice, though, AFAIK we should use the first, shorter schema, as the second only applies to more "exotic" use cases that I don't believe we have in the current state of the spec

**Comment by matthias-pichler-warrify** [comment]
```yaml
      authentications:
        type: object
        additionalProperties:
          $ref: '#/$defs/authenticationPolicy'
        description: The workflow's reusable authentication policies.
```

this does not represent an inheritance relationship. Roughly: 

the first schema states that the `input` field **IS** of type `$defs/input`

the second schema states that `authentications` **HAS** properties that themselves are of type `$defs/authenticationPolicy`. You can try and change the occurrences any way and I can promise that the examples will no longer validate against the schema 👍

**Comment by JBBianchi** [comment]
Thanks for your input folks, it makes sense now that you shine a light on it :)
