### ISSUE TITLE
Introduce the `metadata` property to `tasks` and other concepts

### ISSUE THREAD

**Issue by ricardozanini** [serverlessworkflow/specification#945]
**What would you like to be added**:
As discussed in #928, there are a few use cases where metadata information is useful such as when designing a graphical interface for representing the DSL.

This field **must not** change the behavior of the workflow in runtime. For example: adding additional properties to a function call that only the given implementation would understand. The metadata information must describe **static** information regarding the workflow definition, not changing in any matter its behavior.

**Why is this needed**:
Several times users and community members faced a situation where some dynamic data could be added to the DSL to facilitate some parts of an implementation and there was no room for it in the current DSL version.

Apart from the obvious include to the `task` object, other parts of the DSL must be assessed.

**Comment by cdavernas** [comment]
@matthias-pichler-warrify you are totally right. AFAIR, we had agreed on `metadata` indeed, as we should avoid abbreviations whenever possible. Plus, `mera` is now archi bloated, thanks to Zuckerberg 🤣

**Comment by ricardozanini** [comment]
We can use `metadata`, but I remember @matthias-pichler-warrify bringing the arg regarding the word usage in JSON spec.

**Comment by matthias-pichler-warrify** [comment]
> We can use metadata, but I remember @matthias-pichler-warrify bringing the arg regarding the word usage in JSON spec.

I am fine with either. I brought up JSON:API more for the concept 👍
