### ISSUE TITLE
Add $runtime argument for implementation specific information

### ISSUE THREAD

**Issue by matthias-pichler-warrify** [serverlessworkflow/specification#950]
**What would you like to be added**:

As discussed in #932 we will introduce a new runtime expression argument called `$runtime` that holds implementation specific information. It will include the following standard fields for now:

- `$runtime.name` ... the name of the runtime (e.g. Synapse, Sonanta, ...)
- `$runtime.version` ... the version of the runtime (e.g. commit sha, image hash, (semantic) version, ...)
- `$runtime.metadata` ... custom values that be set by implementors (e.g. tenantId, account, ...) alternatively we could use `$runtime.implementation`?

## Future Additions

The following fields can be added in the future but haven't been decided yet:

### Current Time

- `$runtime.now.iso8601`
- `$runtime.now.epochMillis`
- `$runtime.now.epochNanos`

### Execution start times

An alternative proposed by @cdavernas was `$workflow.startedAt` ... which I prefer and propose in #951

- `$runtime.executionStart.iso8601`
- `$runtime.executionStart.epochMillis`
- `$runtime.executionStart.epochNanos`

### Task start times

An alternative proposed by @cdavernas was `$task.startedAt` ... which I prefer  and propose in #951

- `$runtime.taskStart.iso8601`
- `$runtime.taskStart.epochMillis`
- `$runtime.taskStart.epochNanos`

### Operating System (suggested by @fjtirado )

- `$runtime.os` ... Personally not a fan because it might not always make sense/be known and might have unclear semantics inside `run.container` tasks

**Why is this needed**:

See #932

**Comment by fjtirado** [comment]
@JBBianchi Hey, I also suggested currentTime ;)
About operating system, I think is part of the shell and container discussion. We are assuming there is a shell available (that's the way to extend the functionality) and we are assuming containers can be run. So I definitely see there will be an operating system, running shells and containers.

**Comment by matthias-pichler-warrify** [comment]
I left out some of the things we haven't reached consensus on. We can discuss and potentially add them in the future 👍

Regarding run.shell: I thought this was going to be removed?

Regarding run.container: the os is either known from the image or can be determined by the code inside the container

Regarding currentTime: I think it is better suited for the $task and $workflow arguments.

**Comment by fjtirado** [comment]
@matthias-pichler-warrify Agree with the currenttime being on workflow and task objects.
