### ISSUE TITLE
Standard error types with duplicate https scheme

### ISSUE THREAD

**Issue by matthias-pichler-warrify** [serverlessworkflow/specification#954]
**What seems off**:

Why are error types specified with a repeated `https` at the beginning: https://github.com/serverlessworkflow/specification/blob/main/dsl-reference.md#standard-error-types? E.g `https://https://serverlessworkflow.io/spec/1.0.0/errors/validation`

**What you expected to be**:

Since the format is specified as a `uri-template` in the schema I would expect a valid URI

**Anything else we need to know?**:

Why are the error types of format `uri-template` and not `uri` in the first place? Because the context against which the template should be evaluated isn't documented either

**Environment**:

- Specification version used: `1.0.0-alpha2`

**Comment by cdavernas** [comment]
It's a typo, good catch!
