### ISSUE TITLE
Allow accesing current date and time in expressions. 

### ISSUE THREAD

**Issue by fjtirado** [serverlessworkflow/specification#970]
**What would you like to be added**:

Now that we have a runtime object, it would be great if users can access current date in expressions

Therefore, I propose to add `$runtime.now.iso8601`, `$runtime.now.epochMillis` and `$runtime.now.epochNanos`

**Why is this needed**:

**Comment by JBBianchi** [comment]
Just out of curiosity, how would it differ from `now` in jq our `new Date()` in js ?

**Comment by fjtirado** [comment]
In nothing, I did not know now existin in JQ
